AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  License: Apache-2.0
Description: "Deploys the environment stack for the Foodhouse application."
Parameters:
  EnvId:
    Type: String
    Description: Environment Id (used to namespace resources)
    AllowedPattern: "[a-z][a-z0-9]{2,19}"
    ConstraintDescription: Must be lower case letters between 3 and 20 characters.
  InfraArtifactsBucket:
    Type: String
    Description: The bucket where the infra artifacts are stored (specifically the cloudformation templates).
  InfraReleaseHash:
    Type: String
    Description: The id of the cloudformation templates to use for nested stacks. In CD this will be set to the git sha for the current commi
  UsersImageTag:
    Type: String
    Description: This is the docker image and tag (image:tag) that should be deployed for the users service.
  ProductsImageTag:
    Type: String
    Description: This is the docker image and tag (image:tag) that should be deployed for the products service.
  OrdersImageTag:
    Type: String
    Description: This is the docker image and tag (image:tag) that should be deployed for the orders service.
  JsonproxyImageTag:
    Type: String
    Description: This is the docker image and tag (image:tag) that should be deployed for the json proxy service.
  ReleaseTarget:
    Type: String
    Description: |
      The git branch (or tag) that is being be deployed to this environment.
      This is used for tagging resources in the environment for information and debugging purposes.
  DomainName:
    Type: String
    Description: The domain name for the environment.

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref EnvId

  # VpcStack set up VPC with 2 AZs.
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        IsDevelopmentGrade: true
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
        - Key: ReleaseTarget
          Value: !Ref "ReleaseTarget"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/aws-cloudformation-templates/core-components/vpc.yaml",
          ],
        ]

  #  RdsStack nested stack deploys the Rds instance..
  RdsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [VpcStack]
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        IsDevelopmentGrade: true
        VpcId: !GetAtt VpcStack.Outputs.VPC
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        PublicSubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPublic,
              !GetAtt VpcStack.Outputs.SubnetBPublic,
            ],
          ]
        LambdaS3BucketName: !Ref InfraArtifactsBucket
        LambdaS3KeyPrefix:
          !Join [
            "",
            [
              "cloudformation/",
              !Ref InfraReleaseHash,
              "/aws-cloudformation-templates",
            ],
          ]
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/aws-cloudformation-templates/core-components/rds.yaml",
          ],
        ]

  EcsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        VpcId: !GetAtt VpcStack.Outputs.VPC
        PrivateSubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        AdditionalNodeSecurityGroupIds: !GetAtt RdsStack.Outputs.ClientSecurityGroupId
        NumPrivateNodes: 1
        InstanceType: t2.micro
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
        - Key: ReleaseTarget
          Value: !Ref "ReleaseTarget"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/aws-cloudformation-templates/core-components/ecs.yaml",
          ],
        ]

  # WebCert deploys the web certificates.
  WebCert:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref "DomainName"
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
        - !Sub "api.${DomainName}"
        - !Sub "pgadmin.${DomainName}"
        - !Sub "admindashboard.${DomainName}"
      ValidationMethod: DNS
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"

  # LoadBalancerStack deploys the default load balancer.
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [VpcStack, WebCert]
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        VPC: !GetAtt VpcStack.Outputs.VPC
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPublic,
              !GetAtt VpcStack.Outputs.SubnetBPublic,
            ],
          ]
        CertificateArn: !Ref WebCert
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/aws-cloudformation-templates/core-components/load_balancer.yaml",
          ],
        ]

  EcsSecurityGroupALBports:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !GetAtt EcsStack.Outputs.EcsSecurityGroupId
      IpProtocol: tcp
      FromPort: 80
      ToPort: 61000
      SourceSecurityGroupId: !GetAtt LoadBalancerStack.Outputs.LoadBalancerSecurityGroupId

  ThirdPartySecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/components/third_party_secrets.yaml",
          ],
        ]

  UsersStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - RdsStack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        Image: !Ref UsersImageTag
        VPC: !GetAtt VpcStack.Outputs.VPC
        LogGroupName: !Ref LogGroup
        ClusterArn: !GetAtt EcsStack.Outputs.ClusterArn
        DbAdminSecretArn: !GetAtt "RdsStack.Outputs.AdminSecretArn"
        TwilioClientSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.TwilioClientSecretArn"
        FirebaseServiceAccountSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.FirebaseServiceAccountSecretArn"
        GoogleChatClientSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.GoogleChatClientSecretArn"
        FirebaseSdkSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.FirebaseSdkSecretArn"
        InfoBipClientSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.InfoBipClientSecretArn"
        NexahClientSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.NexahClientSecretArn"
        DomainName: !Ref DomainName
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        CustomResourcesServiceToken: !GetAtt RdsStack.Outputs.DatabaseInitLambdaArn
        DesiredCount: 1
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/services/users.yaml",
          ],
        ]


  ProductsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - RdsStack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        Image: !Ref ProductsImageTag
        VPC: !GetAtt VpcStack.Outputs.VPC
        LogGroupName: !Ref LogGroup
        ClusterArn: !GetAtt EcsStack.Outputs.ClusterArn
        DbAdminSecretArn: !GetAtt "RdsStack.Outputs.AdminSecretArn"
        DomainName: !Ref DomainName
        UsersHostPort: "users:80" 
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        CustomResourcesServiceToken: !GetAtt RdsStack.Outputs.DatabaseInitLambdaArn
        DesiredCount: 1
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/services/products.yaml",
          ],
        ]

  OrdersStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - RdsStack
      - ThirdPartySecretsStack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        Image: !Ref OrdersImageTag
        VPC: !GetAtt VpcStack.Outputs.VPC
        LogGroupName: !Ref LogGroup
        ClusterArn: !GetAtt EcsStack.Outputs.ClusterArn
        DbAdminSecretArn: !GetAtt "RdsStack.Outputs.AdminSecretArn"
        CampaySecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.CampaySecretArn"
        SmtpSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.SmtpSecretArn"
        CompanyInfoArn: !GetAtt "ThirdPartySecretsStack.Outputs.CompanyInfoArn"
        DomainName: !Ref DomainName
        # TODO: Get this from users stack
        UsersHostPort: "users:80" 
        #TODO: Get this from products stack
        ProductsHostPort: "products:80"
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        CustomResourcesServiceToken: !GetAtt RdsStack.Outputs.DatabaseInitLambdaArn
        DesiredCount: 1
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/services/orders.yaml",
          ],
        ]


  JsonproxyStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - RdsStack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        Image: !Ref JsonproxyImageTag
        VPC: !GetAtt VpcStack.Outputs.VPC
        LogGroupName: !Ref LogGroup
        ClusterArn: !GetAtt EcsStack.Outputs.ClusterArn
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        DesiredCount: 1
        DomainName: !Ref DomainName
        LoadBalancerCanonicalHostedZoneID: !GetAtt LoadBalancerStack.Outputs.LoadBalancerCanonicalHostedZoneID
        LoadBalancerDNSName: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNSName
        HttpsListener: !GetAtt LoadBalancerStack.Outputs.HttpsListener
        FirebaseServiceAccountSecretArn: !GetAtt "ThirdPartySecretsStack.Outputs.FirebaseServiceAccountSecretArn"
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/services/jsonproxy.yaml",
          ],
        ]

  PgAdminStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - RdsStack
    Properties:
      Parameters:
        EnvId: !Ref "EnvId"
        VPC: !GetAtt VpcStack.Outputs.VPC
        LogGroupName: !Ref LogGroup
        ClusterArn: !GetAtt EcsStack.Outputs.ClusterArn
        SubnetIds:
          !Join [
            ",",
            [
              !GetAtt VpcStack.Outputs.SubnetAPrivate,
              !GetAtt VpcStack.Outputs.SubnetBPrivate,
            ],
          ]
        DomainName: !Ref DomainName
        LoadBalancerCanonicalHostedZoneID: !GetAtt LoadBalancerStack.Outputs.LoadBalancerCanonicalHostedZoneID
        LoadBalancerDNSName: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNSName
        HttpsListener: !GetAtt LoadBalancerStack.Outputs.HttpsListener
      Tags:
        - Key: EnvId
          Value: !Ref "EnvId"
      TemplateURL:
        !Join [
          "",
          [
            "https://s3.amazonaws.com/",
            !Ref "InfraArtifactsBucket",
            "/cloudformation/",
            !Ref "InfraReleaseHash",
            "/services/pgadmin.yaml",
          ],
        ]
