import { Colors } from '@/constants';
import { StyleSheet } from 'react-native';

export const agentOrderDetailsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light['bg'],
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 16,
    zIndex: 10,
    padding: 4,
  },
  header: {
    backgroundColor: Colors.primary[500],
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.light[10],
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: Colors.light[10],
    opacity: 0.8,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  section: {
    backgroundColor: Colors.light[10],
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.grey['border'],
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: Colors.dark[0],
  },
  orderInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  orderLabel: {
    fontSize: 14,
    color: Colors.grey['61'],
  },
  orderValue: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.dark[0],
  },
  statusBadge: {
    backgroundColor: Colors.primary[500] + '20',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    color: Colors.primary[500],
    fontSize: 12,
    fontWeight: '600',
  },
  locationCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  locationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primary[500] + '20',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  locationInfo: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 12,
    color: Colors.grey['61'],
    marginBottom: 4,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  itemText: {
    fontSize: 14,
    color: Colors.dark[0],
    marginLeft: 4,
  },
  locationAddress: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.dark[0],
    lineHeight: 20,
  },
  securityCodeSection: {
    backgroundColor: Colors.gold + '20',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    alignItems: 'center',
  },
  securityCodeLabel: {
    fontSize: 14,
    color: Colors.grey['61'],
    marginBottom: 8,
  },
  securityCode: {
    fontSize: 32,
    fontWeight: 'bold',
    color: Colors.dark[0],
    letterSpacing: 4,
  },
  button: {
    backgroundColor: Colors.primary[500],
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: Colors.light[10],
    fontSize: 16,
    fontWeight: '600',
  },
  buttonSecondary: {
    backgroundColor: Colors.grey['fa'],
    borderWidth: 1,
    borderColor: Colors.grey['border'],
  },
  buttonSecondaryText: {
    color: Colors.dark[0],
  },
  deliveryFee: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.success,
    marginTop: 8,
  },
  errorText: {
    color: Colors.error,
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: Colors.light[10],
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
  },
  modalClose: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.dark[0],
    marginBottom: 8,
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 14,
    color: Colors.grey['61'],
    marginBottom: 24,
    textAlign: 'center',
  },
  codeInput: {
    width: '100%',
    height: 60,
    borderWidth: 2,
    borderColor: Colors.primary[500],
    borderRadius: 12,
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 12,
    color: Colors.dark[0],
    marginBottom: 12,
  },
  codeHint: {
    fontSize: 12,
    color: Colors.grey['61'],
    marginBottom: 24,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  cancelButton: {
    flex: 1,
    backgroundColor: Colors.grey['e1'],
  },
  cancelButtonText: {
    color: Colors.dark[0],
    fontSize: 16,
    fontWeight: '600',
  },
});
