// Code generated by MockGen. DO NOT EDIT.
// Source: ./sqlc (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination sqlc/mocks/querier.go -package mocks ./sqlc Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/foodhouse/foodhouseapp/orders/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateDeliveryPoint mocks base method.
func (m *MockQuerier) CreateDeliveryPoint(ctx context.Context, arg sqlc.CreateDeliveryPointParams) (sqlc.DeliveryPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeliveryPoint", ctx, arg)
	ret0, _ := ret[0].(sqlc.DeliveryPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeliveryPoint indicates an expected call of CreateDeliveryPoint.
func (mr *MockQuerierMockRecorder) CreateDeliveryPoint(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeliveryPoint", reflect.TypeOf((*MockQuerier)(nil).CreateDeliveryPoint), ctx, arg)
}

// CreateOrder mocks base method.
func (m *MockQuerier) CreateOrder(ctx context.Context, arg sqlc.CreateOrderParams) (sqlc.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, arg)
	ret0, _ := ret[0].(sqlc.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockQuerierMockRecorder) CreateOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockQuerier)(nil).CreateOrder), ctx, arg)
}

// CreateOrderAuditLog mocks base method.
func (m *MockQuerier) CreateOrderAuditLog(ctx context.Context, arg sqlc.CreateOrderAuditLogParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderAuditLog", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderAuditLog indicates an expected call of CreateOrderAuditLog.
func (mr *MockQuerierMockRecorder) CreateOrderAuditLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderAuditLog", reflect.TypeOf((*MockQuerier)(nil).CreateOrderAuditLog), ctx, arg)
}

// CreatePayment mocks base method.
func (m *MockQuerier) CreatePayment(ctx context.Context, arg sqlc.CreatePaymentParams) (sqlc.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, arg)
	ret0, _ := ret[0].(sqlc.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockQuerierMockRecorder) CreatePayment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockQuerier)(nil).CreatePayment), ctx, arg)
}

// GetOrderByOrderNumber mocks base method.
func (m *MockQuerier) GetOrderByOrderNumber(ctx context.Context, orderNumber int64) (sqlc.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByOrderNumber", ctx, orderNumber)
	ret0, _ := ret[0].(sqlc.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByOrderNumber indicates an expected call of GetOrderByOrderNumber.
func (mr *MockQuerierMockRecorder) GetOrderByOrderNumber(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByOrderNumber", reflect.TypeOf((*MockQuerier)(nil).GetOrderByOrderNumber), ctx, orderNumber)
}

// GetPaymentById mocks base method.
func (m *MockQuerier) GetPaymentById(ctx context.Context, id string) (sqlc.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentById", ctx, id)
	ret0, _ := ret[0].(sqlc.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentById indicates an expected call of GetPaymentById.
func (mr *MockQuerierMockRecorder) GetPaymentById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentById", reflect.TypeOf((*MockQuerier)(nil).GetPaymentById), ctx, id)
}

// GetUserOrderBySecretKey mocks base method.
func (m *MockQuerier) GetUserOrderBySecretKey(ctx context.Context, arg sqlc.GetUserOrderBySecretKeyParams) (sqlc.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrderBySecretKey", ctx, arg)
	ret0, _ := ret[0].(sqlc.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrderBySecretKey indicates an expected call of GetUserOrderBySecretKey.
func (mr *MockQuerierMockRecorder) GetUserOrderBySecretKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrderBySecretKey", reflect.TypeOf((*MockQuerier)(nil).GetUserOrderBySecretKey), ctx, arg)
}

// ListDeliveryPoints mocks base method.
func (m *MockQuerier) ListDeliveryPoints(ctx context.Context, arg sqlc.ListDeliveryPointsParams) ([]sqlc.DeliveryPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeliveryPoints", ctx, arg)
	ret0, _ := ret[0].([]sqlc.DeliveryPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeliveryPoints indicates an expected call of ListDeliveryPoints.
func (mr *MockQuerierMockRecorder) ListDeliveryPoints(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeliveryPoints", reflect.TypeOf((*MockQuerier)(nil).ListDeliveryPoints), ctx, arg)
}

// ListFarmerOrders mocks base method.
func (m *MockQuerier) ListFarmerOrders(ctx context.Context, arg sqlc.ListFarmerOrdersParams) ([]sqlc.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFarmerOrders", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFarmerOrders indicates an expected call of ListFarmerOrders.
func (mr *MockQuerierMockRecorder) ListFarmerOrders(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFarmerOrders", reflect.TypeOf((*MockQuerier)(nil).ListFarmerOrders), ctx, arg)
}

// ListOrderAuditLogs mocks base method.
func (m *MockQuerier) ListOrderAuditLogs(ctx context.Context, orderNumber int64) ([]sqlc.OrdersAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderAuditLogs", ctx, orderNumber)
	ret0, _ := ret[0].([]sqlc.OrdersAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrderAuditLogs indicates an expected call of ListOrderAuditLogs.
func (mr *MockQuerierMockRecorder) ListOrderAuditLogs(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderAuditLogs", reflect.TypeOf((*MockQuerier)(nil).ListOrderAuditLogs), ctx, orderNumber)
}

// ListUserOrders mocks base method.
func (m *MockQuerier) ListUserOrders(ctx context.Context, arg sqlc.ListUserOrdersParams) ([]sqlc.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserOrders", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserOrders indicates an expected call of ListUserOrders.
func (mr *MockQuerierMockRecorder) ListUserOrders(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserOrders", reflect.TypeOf((*MockQuerier)(nil).ListUserOrders), ctx, arg)
}

// ReviewOrder mocks base method.
func (m *MockQuerier) ReviewOrder(ctx context.Context, arg sqlc.ReviewOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReviewOrder indicates an expected call of ReviewOrder.
func (mr *MockQuerierMockRecorder) ReviewOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewOrder", reflect.TypeOf((*MockQuerier)(nil).ReviewOrder), ctx, arg)
}

// UpdateOrderStatus mocks base method.
func (m *MockQuerier) UpdateOrderStatus(ctx context.Context, arg sqlc.UpdateOrderStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockQuerierMockRecorder) UpdateOrderStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateOrderStatus), ctx, arg)
}

// UpdatePaymentStatus mocks base method.
func (m *MockQuerier) UpdatePaymentStatus(ctx context.Context, arg sqlc.UpdatePaymentStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockQuerierMockRecorder) UpdatePaymentStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockQuerier)(nil).UpdatePaymentStatus), ctx, arg)
}
