// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: products.proto

package productsgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Products_CreateCategory_FullMethodName     = "/productsgrpc.Products/CreateCategory"
	Products_UpdateCategory_FullMethodName     = "/productsgrpc.Products/UpdateCategory"
	Products_DeleteCategory_FullMethodName     = "/productsgrpc.Products/DeleteCategory"
	Products_CreateProduct_FullMethodName      = "/productsgrpc.Products/CreateProduct"
	Products_UpdateProduct_FullMethodName      = "/productsgrpc.Products/UpdateProduct"
	Products_DeleteProduct_FullMethodName      = "/productsgrpc.Products/DeleteProduct"
	Products_ListProducts_FullMethodName       = "/productsgrpc.Products/ListProducts"
	Products_ListFarmerProducts_FullMethodName = "/productsgrpc.Products/ListFarmerProducts"
	Products_GetProduct_FullMethodName         = "/productsgrpc.Products/GetProduct"
	Products_GetFarmerProduct_FullMethodName   = "/productsgrpc.Products/GetFarmerProduct"
	Products_ListCategories_FullMethodName     = "/productsgrpc.Products/ListCategories"
	Products_HealthCheck_FullMethodName        = "/productsgrpc.Products/HealthCheck"
	Products_CreateProductName_FullMethodName  = "/productsgrpc.Products/CreateProductName"
	Products_DeleteProductName_FullMethodName  = "/productsgrpc.Products/DeleteProductName"
	Products_CreatePriceType_FullMethodName    = "/productsgrpc.Products/CreatePriceType"
	Products_PublishProduct_FullMethodName     = "/productsgrpc.Products/PublishProduct"
	Products_UnPublishProduct_FullMethodName   = "/productsgrpc.Products/UnPublishProduct"
	Products_DeletePriceType_FullMethodName    = "/productsgrpc.Products/DeletePriceType"
	Products_ListProductNames_FullMethodName   = "/productsgrpc.Products/ListProductNames"
	Products_ListPriceTypes_FullMethodName     = "/productsgrpc.Products/ListPriceTypes"
	Products_SumProductAmounts_FullMethodName  = "/productsgrpc.Products/SumProductAmounts"
	Products_GetProductStats_FullMethodName    = "/productsgrpc.Products/GetProductStats"
	Products_GetDeliveryFee_FullMethodName     = "/productsgrpc.Products/GetDeliveryFee"
)

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductsClient interface {
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	ListFarmerProducts(ctx context.Context, in *ListFarmerProductsRequest, opts ...grpc.CallOption) (*ListFarmerProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	GetFarmerProduct(ctx context.Context, in *GetFarmerProductRequest, opts ...grpc.CallOption) (*GetFarmerProductResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	CreateProductName(ctx context.Context, in *CreateProductNameRequest, opts ...grpc.CallOption) (*CreateProductNameResponse, error)
	DeleteProductName(ctx context.Context, in *DeleteProductNameRequest, opts ...grpc.CallOption) (*DeleteProductNameResponse, error)
	CreatePriceType(ctx context.Context, in *CreatePriceTypeRequest, opts ...grpc.CallOption) (*CreatePriceTypeResponse, error)
	PublishProduct(ctx context.Context, in *PublishProductRequest, opts ...grpc.CallOption) (*PublishProductResponse, error)
	UnPublishProduct(ctx context.Context, in *UnPublishProductRequest, opts ...grpc.CallOption) (*UnPublishProductResponse, error)
	DeletePriceType(ctx context.Context, in *DeletePriceTypeRequest, opts ...grpc.CallOption) (*DeletePriceTypeResponse, error)
	ListProductNames(ctx context.Context, in *ListProductNamesRequest, opts ...grpc.CallOption) (*ListProductNamesResponse, error)
	ListPriceTypes(ctx context.Context, in *ListPriceTypesRequest, opts ...grpc.CallOption) (*ListPriceTypesResponse, error)
	SumProductAmounts(ctx context.Context, in *SumProductAmountsRequest, opts ...grpc.CallOption) (*SumProductAmountsResponse, error)
	GetProductStats(ctx context.Context, in *GetProductStatsRequest, opts ...grpc.CallOption) (*GetProductStatsResponse, error)
	GetDeliveryFee(ctx context.Context, in *GetDeliveryFeeRequest, opts ...grpc.CallOption) (*GetDeliveryFeeResponse, error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, Products_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, Products_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, Products_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, Products_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, Products_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, Products_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, Products_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ListFarmerProducts(ctx context.Context, in *ListFarmerProductsRequest, opts ...grpc.CallOption) (*ListFarmerProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFarmerProductsResponse)
	err := c.cc.Invoke(ctx, Products_ListFarmerProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, Products_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetFarmerProduct(ctx context.Context, in *GetFarmerProductRequest, opts ...grpc.CallOption) (*GetFarmerProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFarmerProductResponse)
	err := c.cc.Invoke(ctx, Products_GetFarmerProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, Products_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Products_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) CreateProductName(ctx context.Context, in *CreateProductNameRequest, opts ...grpc.CallOption) (*CreateProductNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductNameResponse)
	err := c.cc.Invoke(ctx, Products_CreateProductName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeleteProductName(ctx context.Context, in *DeleteProductNameRequest, opts ...grpc.CallOption) (*DeleteProductNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductNameResponse)
	err := c.cc.Invoke(ctx, Products_DeleteProductName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) CreatePriceType(ctx context.Context, in *CreatePriceTypeRequest, opts ...grpc.CallOption) (*CreatePriceTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePriceTypeResponse)
	err := c.cc.Invoke(ctx, Products_CreatePriceType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) PublishProduct(ctx context.Context, in *PublishProductRequest, opts ...grpc.CallOption) (*PublishProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishProductResponse)
	err := c.cc.Invoke(ctx, Products_PublishProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) UnPublishProduct(ctx context.Context, in *UnPublishProductRequest, opts ...grpc.CallOption) (*UnPublishProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnPublishProductResponse)
	err := c.cc.Invoke(ctx, Products_UnPublishProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) DeletePriceType(ctx context.Context, in *DeletePriceTypeRequest, opts ...grpc.CallOption) (*DeletePriceTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePriceTypeResponse)
	err := c.cc.Invoke(ctx, Products_DeletePriceType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ListProductNames(ctx context.Context, in *ListProductNamesRequest, opts ...grpc.CallOption) (*ListProductNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductNamesResponse)
	err := c.cc.Invoke(ctx, Products_ListProductNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) ListPriceTypes(ctx context.Context, in *ListPriceTypesRequest, opts ...grpc.CallOption) (*ListPriceTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPriceTypesResponse)
	err := c.cc.Invoke(ctx, Products_ListPriceTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) SumProductAmounts(ctx context.Context, in *SumProductAmountsRequest, opts ...grpc.CallOption) (*SumProductAmountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumProductAmountsResponse)
	err := c.cc.Invoke(ctx, Products_SumProductAmounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetProductStats(ctx context.Context, in *GetProductStatsRequest, opts ...grpc.CallOption) (*GetProductStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductStatsResponse)
	err := c.cc.Invoke(ctx, Products_GetProductStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetDeliveryFee(ctx context.Context, in *GetDeliveryFeeRequest, opts ...grpc.CallOption) (*GetDeliveryFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryFeeResponse)
	err := c.cc.Invoke(ctx, Products_GetDeliveryFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
// All implementations must embed UnimplementedProductsServer
// for forward compatibility.
type ProductsServer interface {
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	ListFarmerProducts(context.Context, *ListFarmerProductsRequest) (*ListFarmerProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetFarmerProduct(context.Context, *GetFarmerProductRequest) (*GetFarmerProductResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	CreateProductName(context.Context, *CreateProductNameRequest) (*CreateProductNameResponse, error)
	DeleteProductName(context.Context, *DeleteProductNameRequest) (*DeleteProductNameResponse, error)
	CreatePriceType(context.Context, *CreatePriceTypeRequest) (*CreatePriceTypeResponse, error)
	PublishProduct(context.Context, *PublishProductRequest) (*PublishProductResponse, error)
	UnPublishProduct(context.Context, *UnPublishProductRequest) (*UnPublishProductResponse, error)
	DeletePriceType(context.Context, *DeletePriceTypeRequest) (*DeletePriceTypeResponse, error)
	ListProductNames(context.Context, *ListProductNamesRequest) (*ListProductNamesResponse, error)
	ListPriceTypes(context.Context, *ListPriceTypesRequest) (*ListPriceTypesResponse, error)
	SumProductAmounts(context.Context, *SumProductAmountsRequest) (*SumProductAmountsResponse, error)
	GetProductStats(context.Context, *GetProductStatsRequest) (*GetProductStatsResponse, error)
	GetDeliveryFee(context.Context, *GetDeliveryFeeRequest) (*GetDeliveryFeeResponse, error)
	mustEmbedUnimplementedProductsServer()
}

// UnimplementedProductsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductsServer struct{}

func (UnimplementedProductsServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedProductsServer) UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedProductsServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedProductsServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductsServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductsServer) DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductsServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductsServer) ListFarmerProducts(context.Context, *ListFarmerProductsRequest) (*ListFarmerProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFarmerProducts not implemented")
}
func (UnimplementedProductsServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductsServer) GetFarmerProduct(context.Context, *GetFarmerProductRequest) (*GetFarmerProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFarmerProduct not implemented")
}
func (UnimplementedProductsServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedProductsServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedProductsServer) CreateProductName(context.Context, *CreateProductNameRequest) (*CreateProductNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductName not implemented")
}
func (UnimplementedProductsServer) DeleteProductName(context.Context, *DeleteProductNameRequest) (*DeleteProductNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductName not implemented")
}
func (UnimplementedProductsServer) CreatePriceType(context.Context, *CreatePriceTypeRequest) (*CreatePriceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePriceType not implemented")
}
func (UnimplementedProductsServer) PublishProduct(context.Context, *PublishProductRequest) (*PublishProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishProduct not implemented")
}
func (UnimplementedProductsServer) UnPublishProduct(context.Context, *UnPublishProductRequest) (*UnPublishProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnPublishProduct not implemented")
}
func (UnimplementedProductsServer) DeletePriceType(context.Context, *DeletePriceTypeRequest) (*DeletePriceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePriceType not implemented")
}
func (UnimplementedProductsServer) ListProductNames(context.Context, *ListProductNamesRequest) (*ListProductNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductNames not implemented")
}
func (UnimplementedProductsServer) ListPriceTypes(context.Context, *ListPriceTypesRequest) (*ListPriceTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPriceTypes not implemented")
}
func (UnimplementedProductsServer) SumProductAmounts(context.Context, *SumProductAmountsRequest) (*SumProductAmountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SumProductAmounts not implemented")
}
func (UnimplementedProductsServer) GetProductStats(context.Context, *GetProductStatsRequest) (*GetProductStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductStats not implemented")
}
func (UnimplementedProductsServer) GetDeliveryFee(context.Context, *GetDeliveryFeeRequest) (*GetDeliveryFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryFee not implemented")
}
func (UnimplementedProductsServer) mustEmbedUnimplementedProductsServer() {}
func (UnimplementedProductsServer) testEmbeddedByValue()                  {}

// UnsafeProductsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductsServer will
// result in compilation errors.
type UnsafeProductsServer interface {
	mustEmbedUnimplementedProductsServer()
}

func RegisterProductsServer(s grpc.ServiceRegistrar, srv ProductsServer) {
	// If the following call pancis, it indicates UnimplementedProductsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Products_ServiceDesc, srv)
}

func _Products_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ListFarmerProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFarmerProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ListFarmerProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ListFarmerProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ListFarmerProducts(ctx, req.(*ListFarmerProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetFarmerProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFarmerProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetFarmerProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_GetFarmerProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetFarmerProduct(ctx, req.(*GetFarmerProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_CreateProductName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CreateProductName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_CreateProductName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CreateProductName(ctx, req.(*CreateProductNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeleteProductName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeleteProductName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_DeleteProductName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeleteProductName(ctx, req.(*DeleteProductNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_CreatePriceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePriceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).CreatePriceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_CreatePriceType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).CreatePriceType(ctx, req.(*CreatePriceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_PublishProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).PublishProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_PublishProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).PublishProduct(ctx, req.(*PublishProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_UnPublishProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnPublishProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).UnPublishProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_UnPublishProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).UnPublishProduct(ctx, req.(*UnPublishProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_DeletePriceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePriceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).DeletePriceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_DeletePriceType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).DeletePriceType(ctx, req.(*DeletePriceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ListProductNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ListProductNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ListProductNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ListProductNames(ctx, req.(*ListProductNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_ListPriceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPriceTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).ListPriceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_ListPriceTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).ListPriceTypes(ctx, req.(*ListPriceTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_SumProductAmounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumProductAmountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).SumProductAmounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_SumProductAmounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).SumProductAmounts(ctx, req.(*SumProductAmountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetProductStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetProductStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_GetProductStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetProductStats(ctx, req.(*GetProductStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetDeliveryFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetDeliveryFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Products_GetDeliveryFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetDeliveryFee(ctx, req.(*GetDeliveryFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Products_ServiceDesc is the grpc.ServiceDesc for Products service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Products_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "productsgrpc.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _Products_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _Products_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _Products_DeleteCategory_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _Products_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _Products_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _Products_DeleteProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _Products_ListProducts_Handler,
		},
		{
			MethodName: "ListFarmerProducts",
			Handler:    _Products_ListFarmerProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _Products_GetProduct_Handler,
		},
		{
			MethodName: "GetFarmerProduct",
			Handler:    _Products_GetFarmerProduct_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _Products_ListCategories_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Products_HealthCheck_Handler,
		},
		{
			MethodName: "CreateProductName",
			Handler:    _Products_CreateProductName_Handler,
		},
		{
			MethodName: "DeleteProductName",
			Handler:    _Products_DeleteProductName_Handler,
		},
		{
			MethodName: "CreatePriceType",
			Handler:    _Products_CreatePriceType_Handler,
		},
		{
			MethodName: "PublishProduct",
			Handler:    _Products_PublishProduct_Handler,
		},
		{
			MethodName: "UnPublishProduct",
			Handler:    _Products_UnPublishProduct_Handler,
		},
		{
			MethodName: "DeletePriceType",
			Handler:    _Products_DeletePriceType_Handler,
		},
		{
			MethodName: "ListProductNames",
			Handler:    _Products_ListProductNames_Handler,
		},
		{
			MethodName: "ListPriceTypes",
			Handler:    _Products_ListPriceTypes_Handler,
		},
		{
			MethodName: "SumProductAmounts",
			Handler:    _Products_SumProductAmounts_Handler,
		},
		{
			MethodName: "GetProductStats",
			Handler:    _Products_GetProductStats_Handler,
		},
		{
			MethodName: "GetDeliveryFee",
			Handler:    _Products_GetDeliveryFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products.proto",
}
