// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo (interfaces: OrdersRepo)
//
// Generated by this command:
//
//	mockgen -destination repo/mocks/repo.go -package mocks ./repo OrdersRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/foodhouse/foodhouseapp/orders/db/sqlc"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersRepo is a mock of OrdersRepo interface.
type MockOrdersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepoMockRecorder
	isgomock struct{}
}

// MockOrdersRepoMockRecorder is the mock recorder for MockOrdersRepo.
type MockOrdersRepoMockRecorder struct {
	mock *MockOrdersRepo
}

// NewMockOrdersRepo creates a new mock instance.
func NewMockOrdersRepo(ctrl *gomock.Controller) *MockOrdersRepo {
	mock := &MockOrdersRepo{ctrl: ctrl}
	mock.recorder = &MockOrdersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepo) EXPECT() *MockOrdersRepoMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockOrdersRepo) Begin(ctx context.Context) (sqlc.Querier, pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(sqlc.Querier)
	ret1, _ := ret[1].(pgx.Tx)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Begin indicates an expected call of Begin.
func (mr *MockOrdersRepoMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockOrdersRepo)(nil).Begin), ctx)
}

// Do mocks base method.
func (m *MockOrdersRepo) Do() sqlc.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do")
	ret0, _ := ret[0].(sqlc.Querier)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockOrdersRepoMockRecorder) Do() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockOrdersRepo)(nil).Do))
}
