// This file is auto-generated by @hey-api/openapi-ts

export type ProductsCreateCategoryBody = {
  name?: string;
  image?: string;
};

export type ProductsCreatePriceTypeBody = {
  name?: string;
  categoryId?: string;
  deliveryFeePerUnit?: typesAmount;
};

export type ProductsCreateProductBody = {
  categoryId?: string;
  name?: string;
  unitTypeId?: string;
  amount?: typesAmount;
  description?: string;
  image?: string;
  wholeSale?: boolean;
  deliveryFeePerUnit?: typesAmount;
};

export type ProductsCreateProductNameBody = {
  name?: string;
  categoryId?: string;
};

export type productsgrpcCategory = {
  id?: string;
  name?: string;
  slug?: string;
  createdBy?: string;
  productCount?: string;
  image?: string;
};

export type productsgrpcCreateCategoryResponse = {
  category?: productsgrpcCategory;
};

export type productsgrpcCreatePriceTypeResponse = {
  priceType?: productsgrpcPriceType;
};

export type productsgrpcCreateProductNameResponse = {
  productName?: productsgrpcProductName;
};

export type productsgrpcCreateProductResponse = {
  product?: productsgrpcProduct;
};

export type productsgrpcDeleteCategoryResponse = unknown;

export type productsgrpcDeletePriceTypeResponse = unknown;

export type productsgrpcDeleteProductNameResponse = unknown;

export type productsgrpcDeleteProductResponse = {
  message?: string;
};

export type productsgrpcGetDeliveryFeeResponse = {
  amount?: typesAmount;
  farmerId?: string;
};

export type productsgrpcGetFarmerProductResponse = {
  product?: productsgrpcProduct;
};

export type productsgrpcGetProductResponse = {
  product?: productsgrpcProduct;
};

export type productsgrpcGetProductStatsResponse = {
  data?: Array<productsgrpcStatItem>;
};

export type productsgrpcHealthCheckResponse = unknown;

export type productsgrpcListCategoriesResponse = {
  categories?: Array<productsgrpcCategory>;
};

export type productsgrpcListFarmerProductsResponse = {
  products?: Array<productsgrpcProduct>;
  nextKey?: string;
};

export type productsgrpcListPriceTypesResponse = {
  priceTypes?: Array<productsgrpcPriceType>;
};

export type productsgrpcListProductNamesResponse = {
  productNames?: Array<productsgrpcProductName>;
};

export type productsgrpcListProductsResponse = {
  products?: Array<productsgrpcProduct>;
  nextKey?: string;
};

export type productsgrpcPriceType = {
  id?: string;
  name?: string;
  slug?: string;
  categoryId?: string;
  deliveryFeePerUnit?: typesAmount;
};

export type productsgrpcProduct = {
  id?: string;
  category?: productsgrpcCategory;
  name?: string;
  unitType?: string;
  amount?: typesAmount;
  description?: string;
  image?: string;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
  deliveryFeePerUnit?: typesAmount;
  isApproved?: boolean;
};

export type productsgrpcProductName = {
  name?: string;
  slug?: string;
  categoryId?: string;
};

export type productsgrpcPublishProductResponse = unknown;

export type productsgrpcStatItem = {
  title?: string;
  value?: number;
  change?: number;
  description?: string;
};

export type productsgrpcSumProductAmountsResponse = {
  total?: number;
};

export type productsgrpcUnPublishProductResponse = unknown;

export type productsgrpcUpdateCategoryResponse = unknown;

export type productsgrpcUpdateProductResponse = {
  message?: string;
};

export type ProductsPublishProductBody = unknown;

export type ProductsUnPublishProductBody = unknown;

export type ProductsUpdateCategoryBody = {
  name?: string;
  image?: string;
};

export type ProductsUpdateProductBody = {
  categoryId?: string;
  name?: string;
  unitType?: string;
  amount?: typesAmount;
  description?: string;
  image?: string;
  wholeSale?: boolean;
};

export type protobufAny = {
  [key: string]: unknown;
};

export type rpcStatus = {
  code?: number;
  message?: string;
  details?: Array<protobufAny>;
};

export type typesAmount = {
  value?: number;
  currencyIsoCode?: string;
};

export type typesPoint = {
  lon?: number;
  lat?: number;
  address?: string;
};

export type ProductsCreateCategoryData = {
  body: ProductsCreateCategoryBody;
  path: {
    userId: string;
  };
};

export type ProductsCreateCategoryResponse = productsgrpcCreateCategoryResponse;

export type ProductsCreateCategoryError = rpcStatus;

export type ProductsCreatePriceTypeData = {
  body: ProductsCreatePriceTypeBody;
  path: {
    userId: string;
  };
};

export type ProductsCreatePriceTypeResponse =
  productsgrpcCreatePriceTypeResponse;

export type ProductsCreatePriceTypeError = rpcStatus;

export type ProductsCreateProductNameData = {
  body: ProductsCreateProductNameBody;
  path: {
    userId: string;
  };
};

export type ProductsCreateProductNameResponse =
  productsgrpcCreateProductNameResponse;

export type ProductsCreateProductNameError = rpcStatus;

export type ProductsDeleteCategoryData = {
  path: {
    categoryId: string;
    userId: string;
  };
};

export type ProductsDeleteCategoryResponse = productsgrpcDeleteCategoryResponse;

export type ProductsDeleteCategoryError = rpcStatus;

export type ProductsUpdateCategoryData = {
  body: ProductsUpdateCategoryBody;
  path: {
    categoryId: string;
    userId: string;
  };
};

export type ProductsUpdateCategoryResponse = productsgrpcUpdateCategoryResponse;

export type ProductsUpdateCategoryError = rpcStatus;

export type ProductsDeleteProductNameData = {
  path: {
    name: string;
    userId: string;
  };
};

export type ProductsDeleteProductNameResponse =
  productsgrpcDeleteProductNameResponse;

export type ProductsDeleteProductNameError = rpcStatus;

export type ProductsDeletePriceTypeData = {
  path: {
    priceTypeId: string;
    userId: string;
  };
};

export type ProductsDeletePriceTypeResponse =
  productsgrpcDeletePriceTypeResponse;

export type ProductsDeletePriceTypeError = rpcStatus;

export type ProductsPublishProductData = {
  body: ProductsPublishProductBody;
  path: {
    productId: string;
    userId: string;
  };
};

export type ProductsPublishProductResponse = productsgrpcPublishProductResponse;

export type ProductsPublishProductError = rpcStatus;

export type ProductsUnPublishProductData = {
  body: ProductsUnPublishProductBody;
  path: {
    productId: string;
    userId: string;
  };
};

export type ProductsUnPublishProductResponse =
  productsgrpcUnPublishProductResponse;

export type ProductsUnPublishProductError = rpcStatus;

export type ProductsListCategoriesResponse = productsgrpcListCategoriesResponse;

export type ProductsListCategoriesError = rpcStatus;

export type ProductsHealthCheckResponse = productsgrpcHealthCheckResponse;

export type ProductsHealthCheckError = rpcStatus;

export type ProductsListPriceTypesData = {
  query?: {
    categoryId?: string;
  };
};

export type ProductsListPriceTypesResponse = productsgrpcListPriceTypesResponse;

export type ProductsListPriceTypesError = rpcStatus;

export type ProductsListProductNamesData = {
  query?: {
    categoryId?: string;
  };
};

export type ProductsListProductNamesResponse =
  productsgrpcListProductNamesResponse;

export type ProductsListProductNamesError = rpcStatus;

export type ProductsListProductsData = {
  query?: {
    categoryId?: string;
    count?: number;
    createdBy?: string;
    isApproved?: boolean;
    "maxAmount.currencyIsoCode"?: string;
    "maxAmount.value"?: number;
    "minAmount.currencyIsoCode"?: string;
    "minAmount.value"?: number;
    search?: string;
    startKey?: string;
    "userLocation.address"?: string;
    "userLocation.lat"?: number;
    "userLocation.lon"?: number;
  };
};

export type ProductsListProductsResponse = productsgrpcListProductsResponse;

export type ProductsListProductsError = rpcStatus;

export type ProductsGetProductData = {
  path: {
    productId: string;
  };
};

export type ProductsGetProductResponse = productsgrpcGetProductResponse;

export type ProductsGetProductError = rpcStatus;

export type ProductsListFarmerProductsData = {
  path: {
    userId: string;
  };
  query?: {
    categoryId?: string;
    count?: number;
    "maxAmount.currencyIsoCode"?: string;
    "maxAmount.value"?: number;
    "minAmount.currencyIsoCode"?: string;
    "minAmount.value"?: number;
    search?: string;
    startKey?: string;
  };
};

export type ProductsListFarmerProductsResponse =
  productsgrpcListFarmerProductsResponse;

export type ProductsListFarmerProductsError = rpcStatus;

export type ProductsCreateProductData = {
  body: ProductsCreateProductBody;
  path: {
    userId: string;
  };
};

export type ProductsCreateProductResponse = productsgrpcCreateProductResponse;

export type ProductsCreateProductError = rpcStatus;

export type ProductsDeleteProductData = {
  path: {
    productId: string;
    userId: string;
  };
};

export type ProductsDeleteProductResponse = productsgrpcDeleteProductResponse;

export type ProductsDeleteProductError = rpcStatus;

export type ProductsGetFarmerProductData = {
  path: {
    productId: string;
    userId: string;
  };
};

export type ProductsGetFarmerProductResponse =
  productsgrpcGetFarmerProductResponse;

export type ProductsGetFarmerProductError = rpcStatus;

export type ProductsUpdateProductData = {
  body: ProductsUpdateProductBody;
  path: {
    productId: string;
    userId: string;
  };
};

export type ProductsUpdateProductResponse = productsgrpcUpdateProductResponse;

export type ProductsUpdateProductError = rpcStatus;
