// This file is auto-generated by @hey-api/openapi-ts

export type protobufAny = {
    [key: string]: unknown;
};

export type rpcStatus = {
    code?: number;
    message?: string;
    details?: Array<protobufAny>;
};

export type typesAmount = {
    value?: number;
    currencyIsoCode?: string;
};

export type typesPoint = {
    lon?: number;
    lat?: number;
    address?: string;
};

export type UsersCompleteRegistrationBody = {
    firstName?: string;
    lastName?: string;
    email?: string;
    address?: string;
    profileImage?: string;
    locationCoordinates?: typesPoint;
};

export type UsersCreateSubscriptionBody = {
    title?: string;
    description?: string;
    duration?: string;
    amount?: number;
    currencyIsoCode?: string;
};

export type UsersGrantAdminBody = {
    phoneNumber?: string;
    residenceCountryIsoCode?: string;
};

export type usersgrpcActivateUserSubscriptionResponse = unknown;

/**
 * Request and response messages for gRPC methods.
 */
export type usersgrpcAdditionalFactor = {
    factorType?: usersgrpcFactorType;
    requestId?: string;
    factorHint?: string;
};

export type usersgrpcAuthenticateRequest = {
    factors?: Array<usersgrpcAuthFactor>;
};

export type usersgrpcAuthenticateResponse = {
    loginComplete?: boolean;
    additionalFactor?: usersgrpcAdditionalFactor;
    tokens?: usersgrpcTokens;
    userId?: string;
};

export type usersgrpcAuthFactor = {
    type?: usersgrpcFactorType;
    id?: string;
    secretValue?: string;
};

export type usersgrpcChangePasswordRequest = {
    newPassword?: string;
    emailFactor?: usersgrpcAuthFactor;
};

export type usersgrpcChangePasswordResponse = {
    message?: string;
};

export type usersgrpcCompleteRegistrationResponse = {
    message?: string;
};

export type usersgrpcCreateSubscriptionResponse = {
    subscription?: usersgrpcSubscription;
};

export type usersgrpcDeleteSubscriptionResponse = {
    message?: string;
};

export type usersgrpcDeleteUserPaymentMethodResponse = {
    message?: string;
};

export type usersgrpcDeleteUserSubscriptionResponse = unknown;

export type usersgrpcFactorType = 'FACTOR_TYPE_UNSPECIFIED' | 'FACTOR_TYPE_EMAIL_PASSWORD' | 'FACTOR_TYPE_SMS_OTP' | 'FACTOR_TYPE_EMAIL_OTP';

export type usersgrpcGetFarmerByIDResponse = {
    user?: usersgrpcUser;
};

export type usersgrpcGetUserActiveSubscriptionResponse = {
    userSubscription?: usersgrpcUserSubscription;
};

export type usersgrpcGetUserByIDResponse = {
    user?: usersgrpcUser;
};

export type usersgrpcGetUserPaymentMethodsByUserIDResponse = {
    userPaymentMethods?: Array<usersgrpcUserPaymentMethod>;
};

export type usersgrpcGetUserSubscriptionByIDResponse = {
    userSubscription?: usersgrpcUserSubscription;
};

export type usersgrpcGetUserSubscriptionsResponse = {
    userSubscriptions?: Array<usersgrpcUserSubscription>;
};

export type usersgrpcGrantAdminResponse = {
    message?: string;
};

export type usersgrpcHealthCheckResponse = unknown;

export type usersgrpcLastOtpForFactorResponse = {
    otp?: string;
};

export type usersgrpcListUsersResponse = {
    users?: Array<usersgrpcUser>;
    nextKey?: string;
};

export type usersgrpcOtpIntent = 'OTP_INTENT_UNSPECIFIED' | 'OTP_INTENT_LOGIN' | 'OTP_INTENT_RESET_PASSWORD' | 'OTP_INTENT_SIGNUP';

export type usersgrpcPaymentMethod = {
    method?: string;
    methodId?: string;
};

export type usersgrpcRefreshAccessTokenRequest = {
    refreshToken?: string;
};

export type usersgrpcRefreshAccessTokenResponse = {
    accessToken?: string;
};

export type usersgrpcRevokeRefreshTokenRequest = {
    refreshToken?: string;
};

export type usersgrpcRevokeRefreshTokenResponse = {
    message?: string;
};

export type usersgrpcSendEmailOtpRequest = {
    email?: string;
    intent?: usersgrpcOtpIntent;
};

export type usersgrpcSendEmailOtpResponse = {
    requestId?: string;
};

export type usersgrpcSendSignupSmsOtpRequest = {
    phoneNumber?: string;
    intent?: usersgrpcOtpIntent;
};

export type usersgrpcSendSignUpSmsOtpResponse = {
    requestId?: string;
};

export type usersgrpcSendSmsOtpRequest = {
    phoneNumber?: string;
    intent?: usersgrpcOtpIntent;
};

export type usersgrpcSendSmsOtpResponse = {
    requestId?: string;
};

export type usersgrpcSignupRequest = {
    phoneFactor?: usersgrpcAuthFactor;
    residenceCountryIsoCode?: string;
    password?: string;
    userType?: usersgrpcUserType;
    email?: string;
};

export type usersgrpcSignupResponse = {
    userId?: string;
    tokens?: usersgrpcTokens;
};

export type usersgrpcSubscribeResponse = {
    userSubscription?: usersgrpcUserSubscription;
};

export type usersgrpcSubscription = {
    id?: string;
    title?: string;
    description?: string;
    duration?: string;
    amount?: typesAmount;
};

export type usersgrpcTokens = {
    accessToken?: string;
    refreshToken?: string;
};

export type usersgrpcUpdateSubscriptionResponse = {
    subscription?: usersgrpcSubscription;
};

export type usersgrpcUser = {
    userId?: string;
    role?: usersgrpcUserRole;
    phoneNumber?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    residenceCountryIsoCode?: string;
    locationCoordinates?: typesPoint;
    profileImage?: string;
    address?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type usersgrpcUserPaymentMethod = {
    id?: string;
    userId?: string;
    paymentMethod?: usersgrpcPaymentMethod;
    createdAt?: string;
};

export type usersgrpcUserRole = 'USER_ROLE_UNSPECIFIED' | 'USER_ROLE_FARMER' | 'USER_ROLE_BUYER' | 'USER_ROLE_ADMIN';

export type usersgrpcUserSubscription = {
    id?: string;
    subscription?: usersgrpcSubscription;
    userId?: string;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    expiresAt?: string;
};

export type usersgrpcUserType = 'USER_TYPE_UNSPECIFIED' | 'USER_TYPE_FARMER' | 'USER_TYPE_BUYER';

export type usersgrpcVerifyOtpRequest = {
    authFactor?: usersgrpcAuthFactor;
};

export type usersgrpcVerifyOtpResponse = {
    valid?: boolean;
};

export type UsersSubscribeBody = {
    subscriptionId?: string;
    amount?: number;
    currencyIsoCode?: string;
    paymentMethod?: usersgrpcPaymentMethod;
};

export type UsersUpdateSubscriptionBody = {
    title?: string;
    description?: string;
    duration?: string;
    amount?: number;
    currencyIsoCode?: string;
};

export type UsersCreateSubscriptionData = {
    body: UsersCreateSubscriptionBody;
    path: {
        adminUserId: string;
    };
};

export type UsersCreateSubscriptionResponse = (usersgrpcCreateSubscriptionResponse);

export type UsersCreateSubscriptionError = (rpcStatus);

export type UsersDeleteSubscriptionData = {
    path: {
        adminUserId: string;
        subscriptionId: string;
    };
};

export type UsersDeleteSubscriptionResponse = (usersgrpcDeleteSubscriptionResponse);

export type UsersDeleteSubscriptionError = (rpcStatus);

export type UsersUpdateSubscriptionData = {
    body: UsersUpdateSubscriptionBody;
    path: {
        adminUserId: string;
        subscriptionId: string;
    };
};

export type UsersUpdateSubscriptionResponse = (usersgrpcUpdateSubscriptionResponse);

export type UsersUpdateSubscriptionError = (rpcStatus);

export type UsersGrantAdminData = {
    body: UsersGrantAdminBody;
    path: {
        adminUserId: string;
    };
};

export type UsersGrantAdminResponse = (usersgrpcGrantAdminResponse);

export type UsersGrantAdminError = (rpcStatus);

export type UsersListUsersData = {
    path: {
        adminUserId: string;
    };
    query?: {
        /**
         * Number of users to retrieve
         */
        count?: number;
        /**
         * keyword search for the users (could be name, or email)
         */
        search?: string;
        /**
         * Key for pagination, indicating where to start the list
         */
        startKey?: string;
    };
};

export type UsersListUsersResponse = (usersgrpcListUsersResponse);

export type UsersListUsersError = (rpcStatus);

export type UsersRevokeRefreshTokenData = {
    body: usersgrpcRevokeRefreshTokenRequest;
};

export type UsersRevokeRefreshTokenResponse = (usersgrpcRevokeRefreshTokenResponse);

export type UsersRevokeRefreshTokenError = (rpcStatus);

export type UsersAuthenticateData = {
    body: usersgrpcAuthenticateRequest;
};

export type UsersAuthenticateResponse = (usersgrpcAuthenticateResponse);

export type UsersAuthenticateError = (rpcStatus);

export type UsersChangePasswordData = {
    body: usersgrpcChangePasswordRequest;
};

export type UsersChangePasswordResponse = (usersgrpcChangePasswordResponse);

export type UsersChangePasswordError = (rpcStatus);

export type UsersHealthCheckResponse = (usersgrpcHealthCheckResponse);

export type UsersHealthCheckError = (rpcStatus);

export type UsersLastOtpForFactorData = {
    query?: {
        factor?: string;
    };
};

export type UsersLastOtpForFactorResponse = (usersgrpcLastOtpForFactorResponse);

export type UsersLastOtpForFactorError = (rpcStatus);

export type UsersRefreshAccessTokenData = {
    body: usersgrpcRefreshAccessTokenRequest;
};

export type UsersRefreshAccessTokenResponse = (usersgrpcRefreshAccessTokenResponse);

export type UsersRefreshAccessTokenError = (rpcStatus);

export type UsersSendEmailOtpData = {
    body: usersgrpcSendEmailOtpRequest;
};

export type UsersSendEmailOtpResponse = (usersgrpcSendEmailOtpResponse);

export type UsersSendEmailOtpError = (rpcStatus);

export type UsersSendSignupSmsOtpData = {
    body: usersgrpcSendSignupSmsOtpRequest;
};

export type UsersSendSignupSmsOtpResponse = (usersgrpcSendSignUpSmsOtpResponse);

export type UsersSendSignupSmsOtpError = (rpcStatus);

export type UsersSendSmsOtpData = {
    body: usersgrpcSendSmsOtpRequest;
};

export type UsersSendSmsOtpResponse = (usersgrpcSendSmsOtpResponse);

export type UsersSendSmsOtpError = (rpcStatus);

export type UsersSignupData = {
    body: usersgrpcSignupRequest;
};

export type UsersSignupResponse = (usersgrpcSignupResponse);

export type UsersSignupError = (rpcStatus);

export type UsersVerifyOtpData = {
    body: usersgrpcVerifyOtpRequest;
};

export type UsersVerifyOtpResponse = (usersgrpcVerifyOtpResponse);

export type UsersVerifyOtpError = (rpcStatus);

export type UsersCompleteRegistrationData = {
    body: UsersCompleteRegistrationBody;
    path: {
        userId: string;
    };
};

export type UsersCompleteRegistrationResponse = (usersgrpcCompleteRegistrationResponse);

export type UsersCompleteRegistrationError = (rpcStatus);

export type UsersDeleteUserPaymentMethodData = {
    path: {
        paymentMethodId: string;
        /**
         * UUID as string
         */
        userId: string;
    };
};

export type UsersDeleteUserPaymentMethodResponse = (usersgrpcDeleteUserPaymentMethodResponse);

export type UsersDeleteUserPaymentMethodError = (rpcStatus);

export type UsersGetUserByIdData = {
    path: {
        /**
         * ID of the user to fetch
         */
        userId: string;
    };
};

export type UsersGetUserByIdResponse = (usersgrpcGetUserByIDResponse);

export type UsersGetUserByIdError = (rpcStatus);

export type UsersSubscribeData = {
    body: UsersSubscribeBody;
    path: {
        userId: string;
    };
};

export type UsersSubscribeResponse = (usersgrpcSubscribeResponse);

export type UsersSubscribeError = (rpcStatus);

export type UsersGetUserActiveSubscriptionData = {
    path: {
        userId: string;
    };
};

export type UsersGetUserActiveSubscriptionResponse = (usersgrpcGetUserActiveSubscriptionResponse);

export type UsersGetUserActiveSubscriptionError = (rpcStatus);

export type UsersGetUserSubscriptionsData = {
    path: {
        userId: string;
    };
};

export type UsersGetUserSubscriptionsResponse = (usersgrpcGetUserSubscriptionsResponse);

export type UsersGetUserSubscriptionsError = (rpcStatus);

export type UsersGetUserSubscriptionByIdData = {
    path: {
        userId: string;
        userSubscriptionId: string;
    };
};

export type UsersGetUserSubscriptionByIdResponse = (usersgrpcGetUserSubscriptionByIDResponse);

export type UsersGetUserSubscriptionByIdError = (rpcStatus);

export type UsersGetUserPaymentMethodsByUserIdData = {
    path: {
        /**
         * UUID as string
         */
        userId: string;
    };
};

export type UsersGetUserPaymentMethodsByUserIdResponse = (usersgrpcGetUserPaymentMethodsByUserIDResponse);

export type UsersGetUserPaymentMethodsByUserIdError = (rpcStatus);

export type UsersGetFarmerByIdData = {
    path: {
        /**
         * ID of the farmer to be fetched
         */
        farmerId: string;
        /**
         * ID of the user fetching the farmer
         */
        userId: string;
    };
};

export type UsersGetFarmerByIdResponse = (usersgrpcGetFarmerByIDResponse);

export type UsersGetFarmerByIdError = (rpcStatus);