// This file is auto-generated by @hey-api/openapi-ts

export type ProductsCreateCategoryBody = {
    name?: string;
};

export type ProductsCreatePriceTypeBody = {
    name?: string;
    categoryId?: string;
};

export type ProductsCreateProductBody = {
    categoryId?: string;
    name?: string;
    unitType?: string;
    amount?: typesAmount;
    description?: string;
    image?: string;
    wholeSale?: boolean;
};

export type ProductsCreateProductNameBody = {
    name?: string;
    categoryId?: string;
};

export type productsgrpcCategory = {
    id?: string;
    name?: string;
    slug?: string;
    createdBy?: string;
};

export type productsgrpcCreateCategoryResponse = {
    category?: productsgrpcCategory;
};

export type productsgrpcCreatePriceTypeResponse = {
    priceType?: productsgrpcPriceType;
};

export type productsgrpcCreateProductNameResponse = {
    productName?: productsgrpcProductName;
};

export type productsgrpcCreateProductResponse = {
    product?: productsgrpcProduct;
};

export type productsgrpcDeletePriceTypeResponse = unknown;

export type productsgrpcDeleteProductNameResponse = unknown;

export type productsgrpcDeleteProductResponse = {
    message?: string;
};

export type productsgrpcGetFarmerProductResponse = {
    product?: productsgrpcProduct;
};

export type productsgrpcGetProductResponse = {
    product?: productsgrpcProduct;
};

export type productsgrpcGetProductStatsResponse = {
    data?: Array<productsgrpcStatItem>;
};

export type productsgrpcHealthCheckResponse = unknown;

export type productsgrpcListCategoriesResponse = {
    categories?: Array<productsgrpcCategory>;
};

export type productsgrpcListFarmerProductsResponse = {
    products?: Array<productsgrpcProduct>;
    nextKey?: string;
};

export type productsgrpcListPriceTypesByCategoryResponse = {
    priceTypes?: Array<productsgrpcPriceType>;
};

export type productsgrpcListProductNamesByCategoryResponse = {
    productNames?: Array<productsgrpcProductName>;
};

export type productsgrpcListProductsResponse = {
    products?: Array<productsgrpcProduct>;
    nextKey?: string;
};

export type productsgrpcPriceType = {
    id?: string;
    name?: string;
    slug?: string;
    categoryId?: string;
};

export type productsgrpcProduct = {
    id?: string;
    category?: productsgrpcCategory;
    name?: string;
    unitType?: productsgrpcPriceType;
    amount?: typesAmount;
    description?: string;
    image?: string;
    createdBy?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type productsgrpcProductName = {
    name?: string;
    slug?: string;
    categoryId?: string;
};

export type productsgrpcStatItem = {
    title?: string;
    value?: number;
    change?: number;
    description?: string;
};

export type productsgrpcSumProductAmountsResponse = {
    total?: number;
};

export type productsgrpcUpdateProductResponse = {
    message?: string;
};

export type ProductsUpdateProductBody = {
    categoryId?: string;
    name?: string;
    unitType?: string;
    amount?: typesAmount;
    description?: string;
    image?: string;
    wholeSale?: boolean;
};

export type protobufAny = {
    [key: string]: unknown;
};

export type rpcStatus = {
    code?: number;
    message?: string;
    details?: Array<protobufAny>;
};

export type typesAmount = {
    value?: number;
    currencyIsoCode?: string;
};

export type ProductsCreateCategoryData = {
    body: ProductsCreateCategoryBody;
    path: {
        userId: string;
    };
};

export type ProductsCreateCategoryResponse = (productsgrpcCreateCategoryResponse);

export type ProductsCreateCategoryError = (rpcStatus);

export type ProductsCreatePriceTypeData = {
    body: ProductsCreatePriceTypeBody;
    path: {
        userId: string;
    };
};

export type ProductsCreatePriceTypeResponse = (productsgrpcCreatePriceTypeResponse);

export type ProductsCreatePriceTypeError = (rpcStatus);

export type ProductsCreateProductNameData = {
    body: ProductsCreateProductNameBody;
    path: {
        userId: string;
    };
};

export type ProductsCreateProductNameResponse = (productsgrpcCreateProductNameResponse);

export type ProductsCreateProductNameError = (rpcStatus);

export type ProductsDeleteProductNameData = {
    path: {
        name: string;
        userId: string;
    };
};

export type ProductsDeleteProductNameResponse = (productsgrpcDeleteProductNameResponse);

export type ProductsDeleteProductNameError = (rpcStatus);

export type ProductsDeletePriceTypeData = {
    path: {
        priceTypeId: string;
        userId: string;
    };
};

export type ProductsDeletePriceTypeResponse = (productsgrpcDeletePriceTypeResponse);

export type ProductsDeletePriceTypeError = (rpcStatus);

export type ProductsListCategoriesResponse = (productsgrpcListCategoriesResponse);

export type ProductsListCategoriesError = (rpcStatus);

export type ProductsHealthCheckResponse = (productsgrpcHealthCheckResponse);

export type ProductsHealthCheckError = (rpcStatus);

export type ProductsListProductsData = {
    query?: {
        categoryId?: string;
        count?: number;
        createdBy?: string;
        'maxAmount.currencyIsoCode'?: string;
        'maxAmount.value'?: number;
        'minAmount.currencyIsoCode'?: string;
        'minAmount.value'?: number;
        search?: string;
        startKey?: string;
    };
};

export type ProductsListProductsResponse = (productsgrpcListProductsResponse);

export type ProductsListProductsError = (rpcStatus);

export type ProductsListPriceTypesByCategoryData = {
    path: {
        categoryId: string;
    };
};

export type ProductsListPriceTypesByCategoryResponse = (productsgrpcListPriceTypesByCategoryResponse);

export type ProductsListPriceTypesByCategoryError = (rpcStatus);

export type ProductsListProductNamesByCategoryData = {
    path: {
        categoryId: string;
    };
};

export type ProductsListProductNamesByCategoryResponse = (productsgrpcListProductNamesByCategoryResponse);

export type ProductsListProductNamesByCategoryError = (rpcStatus);

export type ProductsGetProductData = {
    path: {
        productId: string;
    };
};

export type ProductsGetProductResponse = (productsgrpcGetProductResponse);

export type ProductsGetProductError = (rpcStatus);

export type ProductsListFarmerProductsData = {
    path: {
        userId: string;
    };
    query?: {
        categoryId?: string;
        count?: number;
        'maxAmount.currencyIsoCode'?: string;
        'maxAmount.value'?: number;
        'minAmount.currencyIsoCode'?: string;
        'minAmount.value'?: number;
        search?: string;
        startKey?: string;
    };
};

export type ProductsListFarmerProductsResponse = (productsgrpcListFarmerProductsResponse);

export type ProductsListFarmerProductsError = (rpcStatus);

export type ProductsCreateProductData = {
    body: ProductsCreateProductBody;
    path: {
        userId: string;
    };
};

export type ProductsCreateProductResponse = (productsgrpcCreateProductResponse);

export type ProductsCreateProductError = (rpcStatus);

export type ProductsDeleteProductData = {
    path: {
        productId: string;
        userId: string;
    };
};

export type ProductsDeleteProductResponse = (productsgrpcDeleteProductResponse);

export type ProductsDeleteProductError = (rpcStatus);

export type ProductsGetFarmerProductData = {
    path: {
        productId: string;
        userId: string;
    };
};

export type ProductsGetFarmerProductResponse = (productsgrpcGetFarmerProductResponse);

export type ProductsGetFarmerProductError = (rpcStatus);

export type ProductsUpdateProductData = {
    body: ProductsUpdateProductBody;
    path: {
        productId: string;
        userId: string;
    };
};

export type ProductsUpdateProductResponse = (productsgrpcUpdateProductResponse);

export type ProductsUpdateProductError = (rpcStatus);