// Code generated by MockGen. DO NOT EDIT.
// Source: ./sms_sender.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_sms_sender.go -package=mocks -source=./sms_sender.go SmsSender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSmsSender is a mock of SmsSender interface.
type MockSmsSender struct {
	ctrl     *gomock.Controller
	recorder *MockSmsSenderMockRecorder
	isgomock struct{}
}

// MockSmsSenderMockRecorder is the mock recorder for MockSmsSender.
type MockSmsSenderMockRecorder struct {
	mock *MockSmsSender
}

// NewMockSmsSender creates a new mock instance.
func NewMockSmsSender(ctrl *gomock.Controller) *MockSmsSender {
	mock := &MockSmsSender{ctrl: ctrl}
	mock.recorder = &MockSmsSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsSender) EXPECT() *MockSmsSenderMockRecorder {
	return m.recorder
}

// SendSms mocks base method.
func (m *MockSmsSender) SendSms(ctx context.Context, toPhoneNumber, message string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSms", ctx, toPhoneNumber, message)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendSms indicates an expected call of SendSms.
func (mr *MockSmsSenderMockRecorder) SendSms(ctx, toPhoneNumber, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSms", reflect.TypeOf((*MockSmsSender)(nil).SendSms), ctx, toPhoneNumber, message)
}
