// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from '@hey-api/client-axios';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { OrdersCreateDeliveryPointData, OrdersCreateDeliveryPointError, OrdersCreateDeliveryPointResponse, OrdersConfirmPaymentData, OrdersListFarmerOrdersData, OrdersCreateOrderData, OrdersCreateOrderError, OrdersCreateOrderResponse, OrdersInitiatePaymentData, OrdersInitiatePaymentError, OrdersInitiatePaymentResponse, OrdersListDeliveryCitiesData, OrdersListDeliveryPointsData, OrdersListUserOrdersData, OrdersApproveOrderData, OrdersApproveOrderError, OrdersApproveOrderResponse, OrdersDispatchOrderData, OrdersDispatchOrderError, OrdersDispatchOrderResponse, OrdersGetOrderDetailsData, OrdersCheckPaymentStatusData, OrdersConfirmDeliveryData, OrdersConfirmDeliveryError, OrdersConfirmDeliveryResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client, ordersCreateDeliveryPoint, ordersConfirmPayment, ordersHealthCheck, ordersListFarmerOrders, ordersCreateOrder, ordersInitiatePayment, ordersListDeliveryCities, ordersListDeliveryPoints, ordersListUserOrders, ordersApproveOrder, ordersDispatchOrder, ordersGetOrderDetails, ordersCheckPaymentStatus, ordersConfirmDelivery } from '../sdk.gen';

type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};

export const ordersCreateDeliveryPointQueryKey = (options: OptionsLegacyParser<OrdersCreateDeliveryPointData>) => [
    createQueryKey('ordersCreateDeliveryPoint', options)
];

export const ordersCreateDeliveryPointOptions = (options: OptionsLegacyParser<OrdersCreateDeliveryPointData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersCreateDeliveryPoint({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersCreateDeliveryPointQueryKey(options)
    });
};

export const ordersCreateDeliveryPointMutation = (options?: Partial<OptionsLegacyParser<OrdersCreateDeliveryPointData>>) => {
    const mutationOptions: UseMutationOptions<OrdersCreateDeliveryPointResponse, AxiosError<OrdersCreateDeliveryPointError>, OptionsLegacyParser<OrdersCreateDeliveryPointData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await ordersCreateDeliveryPoint({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersConfirmPaymentQueryKey = (options?: OptionsLegacyParser<OrdersConfirmPaymentData>) => [
    createQueryKey('ordersConfirmPayment', options)
];

export const ordersConfirmPaymentOptions = (options?: OptionsLegacyParser<OrdersConfirmPaymentData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersConfirmPayment({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersConfirmPaymentQueryKey(options)
    });
};

export const ordersHealthCheckQueryKey = (options?: OptionsLegacyParser) => [
    createQueryKey('ordersHealthCheck', options)
];

export const ordersHealthCheckOptions = (options?: OptionsLegacyParser) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersHealthCheck({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersHealthCheckQueryKey(options)
    });
};

export const ordersListFarmerOrdersQueryKey = (options: OptionsLegacyParser<OrdersListFarmerOrdersData>) => [
    createQueryKey('ordersListFarmerOrders', options)
];

export const ordersListFarmerOrdersOptions = (options: OptionsLegacyParser<OrdersListFarmerOrdersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersListFarmerOrders({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersListFarmerOrdersQueryKey(options)
    });
};

export const ordersCreateOrderQueryKey = (options: OptionsLegacyParser<OrdersCreateOrderData>) => [
    createQueryKey('ordersCreateOrder', options)
];

export const ordersCreateOrderOptions = (options: OptionsLegacyParser<OrdersCreateOrderData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersCreateOrder({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersCreateOrderQueryKey(options)
    });
};

export const ordersCreateOrderMutation = (options?: Partial<OptionsLegacyParser<OrdersCreateOrderData>>) => {
    const mutationOptions: UseMutationOptions<OrdersCreateOrderResponse, AxiosError<OrdersCreateOrderError>, OptionsLegacyParser<OrdersCreateOrderData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await ordersCreateOrder({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersInitiatePaymentQueryKey = (options: OptionsLegacyParser<OrdersInitiatePaymentData>) => [
    createQueryKey('ordersInitiatePayment', options)
];

export const ordersInitiatePaymentOptions = (options: OptionsLegacyParser<OrdersInitiatePaymentData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersInitiatePayment({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersInitiatePaymentQueryKey(options)
    });
};

export const ordersInitiatePaymentMutation = (options?: Partial<OptionsLegacyParser<OrdersInitiatePaymentData>>) => {
    const mutationOptions: UseMutationOptions<OrdersInitiatePaymentResponse, AxiosError<OrdersInitiatePaymentError>, OptionsLegacyParser<OrdersInitiatePaymentData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await ordersInitiatePayment({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersListDeliveryCitiesQueryKey = (options: OptionsLegacyParser<OrdersListDeliveryCitiesData>) => [
    createQueryKey('ordersListDeliveryCities', options)
];

export const ordersListDeliveryCitiesOptions = (options: OptionsLegacyParser<OrdersListDeliveryCitiesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersListDeliveryCities({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersListDeliveryCitiesQueryKey(options)
    });
};

export const ordersListDeliveryPointsQueryKey = (options: OptionsLegacyParser<OrdersListDeliveryPointsData>) => [
    createQueryKey('ordersListDeliveryPoints', options)
];

export const ordersListDeliveryPointsOptions = (options: OptionsLegacyParser<OrdersListDeliveryPointsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersListDeliveryPoints({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersListDeliveryPointsQueryKey(options)
    });
};

export const ordersListUserOrdersQueryKey = (options: OptionsLegacyParser<OrdersListUserOrdersData>) => [
    createQueryKey('ordersListUserOrders', options)
];

export const ordersListUserOrdersOptions = (options: OptionsLegacyParser<OrdersListUserOrdersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersListUserOrders({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersListUserOrdersQueryKey(options)
    });
};

export const ordersApproveOrderMutation = (options?: Partial<OptionsLegacyParser<OrdersApproveOrderData>>) => {
    const mutationOptions: UseMutationOptions<OrdersApproveOrderResponse, AxiosError<OrdersApproveOrderError>, OptionsLegacyParser<OrdersApproveOrderData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await ordersApproveOrder({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersDispatchOrderMutation = (options?: Partial<OptionsLegacyParser<OrdersDispatchOrderData>>) => {
    const mutationOptions: UseMutationOptions<OrdersDispatchOrderResponse, AxiosError<OrdersDispatchOrderError>, OptionsLegacyParser<OrdersDispatchOrderData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await ordersDispatchOrder({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersGetOrderDetailsQueryKey = (options: OptionsLegacyParser<OrdersGetOrderDetailsData>) => [
    createQueryKey('ordersGetOrderDetails', options)
];

export const ordersGetOrderDetailsOptions = (options: OptionsLegacyParser<OrdersGetOrderDetailsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersGetOrderDetails({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersGetOrderDetailsQueryKey(options)
    });
};

export const ordersCheckPaymentStatusQueryKey = (options: OptionsLegacyParser<OrdersCheckPaymentStatusData>) => [
    createQueryKey('ordersCheckPaymentStatus', options)
];

export const ordersCheckPaymentStatusOptions = (options: OptionsLegacyParser<OrdersCheckPaymentStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await ordersCheckPaymentStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersCheckPaymentStatusQueryKey(options)
    });
};

export const ordersConfirmDeliveryMutation = (options?: Partial<OptionsLegacyParser<OrdersConfirmDeliveryData>>) => {
    const mutationOptions: UseMutationOptions<OrdersConfirmDeliveryResponse, AxiosError<OrdersConfirmDeliveryError>, OptionsLegacyParser<OrdersConfirmDeliveryData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await ordersConfirmDelivery({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};