// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderNumber      int64              `json:"order_number"`
	DeliveryLocation pgtype.Point       `json:"delivery_location"`
	PriceValue       *int64             `json:"price_value"`
	PriceCurrency    *string            `json:"price_currency"`
	Status           string             `json:"status"`
	Rating           pgtype.Numeric     `json:"rating"`
	Review           string             `json:"review"`
	Product          *string            `json:"product"`
	CreatedBy        *string            `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OrdersAudit struct {
	ID             int32              `json:"id"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	OrderNumber    int64              `json:"order_number"`
	Actor          string             `json:"actor"`
	Action         string             `json:"action"`
	Reason         string             `json:"reason"`
	Before         []byte             `json:"before"`
	After          []byte             `json:"after"`
}
