// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (delivery_location, price_value, price_currency, status, product, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at
`

type CreateOrderParams struct {
	DeliveryLocation pgtype.Point `json:"delivery_location"`
	PriceValue       *int64       `json:"price_value"`
	PriceCurrency    *string      `json:"price_currency"`
	Status           string       `json:"status"`
	Product          *string      `json:"product"`
	CreatedBy        *string      `json:"created_by"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.DeliveryLocation,
		arg.PriceValue,
		arg.PriceCurrency,
		arg.Status,
		arg.Product,
		arg.CreatedBy,
	)
	var i Order
	err := row.Scan(
		&i.OrderNumber,
		&i.DeliveryLocation,
		&i.PriceValue,
		&i.PriceCurrency,
		&i.Status,
		&i.Rating,
		&i.Review,
		&i.Product,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderAuditLog = `-- name: CreateOrderAuditLog :exec
INSERT INTO orders_audit
    (
        order_number,
        event_timestamp,
        actor,
        action,
        reason,
        before,
        after
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOrderAuditLogParams struct {
	OrderNumber    int64              `json:"order_number"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	Actor          string             `json:"actor"`
	Action         string             `json:"action"`
	Reason         string             `json:"reason"`
	Before         []byte             `json:"before"`
	After          []byte             `json:"after"`
}

func (q *Queries) CreateOrderAuditLog(ctx context.Context, arg CreateOrderAuditLogParams) error {
	_, err := q.db.Exec(ctx, createOrderAuditLog,
		arg.OrderNumber,
		arg.EventTimestamp,
		arg.Actor,
		arg.Action,
		arg.Reason,
		arg.Before,
		arg.After,
	)
	return err
}

const getOrderByOrderNumber = `-- name: GetOrderByOrderNumber :one
SELECT order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at FROM orders WHERE order_number = $1
`

func (q *Queries) GetOrderByOrderNumber(ctx context.Context, orderNumber int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.OrderNumber,
		&i.DeliveryLocation,
		&i.PriceValue,
		&i.PriceCurrency,
		&i.Status,
		&i.Rating,
		&i.Review,
		&i.Product,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrders = `-- name: GetUserOrders :many
SELECT order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at FROM orders 
WHERE created_by = $1
AND 
  ($2::timestamptz = '0001-01-01 00:00:00+00'::timestamptz OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3::int
`

type GetUserOrdersParams struct {
	CreatedBy     *string   `json:"created_by"`
	CreatedBefore time.Time `json:"created_before"`
	Count         int32     `json:"count"`
}

func (q *Queries) GetUserOrders(ctx context.Context, arg GetUserOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getUserOrders, arg.CreatedBy, arg.CreatedBefore, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderNumber,
			&i.DeliveryLocation,
			&i.PriceValue,
			&i.PriceCurrency,
			&i.Status,
			&i.Rating,
			&i.Review,
			&i.Product,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewOrder = `-- name: ReviewOrder :exec
UPDATE orders SET review = $1, rating = $2 WHERE order_number = $3
`

type ReviewOrderParams struct {
	Review      string         `json:"review"`
	Rating      pgtype.Numeric `json:"rating"`
	OrderNumber int64          `json:"order_number"`
}

func (q *Queries) ReviewOrder(ctx context.Context, arg ReviewOrderParams) error {
	_, err := q.db.Exec(ctx, reviewOrder, arg.Review, arg.Rating, arg.OrderNumber)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE order_number = $1
`

type UpdateOrderStatusParams struct {
	OrderNumber int64  `json:"order_number"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.OrderNumber, arg.Status)
	return err
}
