// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    delivery_location, 
    price_value, 
    price_currency, 
    status, 
    product, 
    created_by, 
    secret_key, 
    product_owner,
    payout_phone_number,
    rating, 
    review
)
VALUES (
    $1::point,    -- Enforcing as POINT (casting delivery_location)
    $2::bigint,         -- Enforcing as BIGINT
    $3::varchar(3),  -- Enforcing as VARCHAR(3)
    $4::text,                -- Enforcing as TEXT
    $5::text,               -- Enforcing as TEXT
    $6::varchar(36),     -- Enforcing as VARCHAR(36)
    $7::varchar(6),      -- Enforcing as VARCHAR(6)
    $8::varchar(36),   -- Enforcing as VARCHAR(36)
    $9::varchar(36), 
    1, -- Default rating
    '' -- Default review
)
RETURNING order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at, secret_key, product_owner, payout_phone_number
`

type CreateOrderParams struct {
	DeliveryLocation  pgtype.Point `json:"delivery_location"`
	PriceValue        int64        `json:"price_value"`
	PriceCurrency     string       `json:"price_currency"`
	Status            string       `json:"status"`
	Product           string       `json:"product"`
	CreatedBy         string       `json:"created_by"`
	SecretKey         string       `json:"secret_key"`
	ProductOwner      string       `json:"product_owner"`
	PayoutPhoneNumber string       `json:"payout_phone_number"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.DeliveryLocation,
		arg.PriceValue,
		arg.PriceCurrency,
		arg.Status,
		arg.Product,
		arg.CreatedBy,
		arg.SecretKey,
		arg.ProductOwner,
		arg.PayoutPhoneNumber,
	)
	var i Order
	err := row.Scan(
		&i.OrderNumber,
		&i.DeliveryLocation,
		&i.PriceValue,
		&i.PriceCurrency,
		&i.Status,
		&i.Rating,
		&i.Review,
		&i.Product,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretKey,
		&i.ProductOwner,
		&i.PayoutPhoneNumber,
	)
	return i, err
}

const createOrderAuditLog = `-- name: CreateOrderAuditLog :exec
INSERT INTO orders_audit
    (
        order_number,
        event_timestamp,
        actor,
        action,
        reason,
        before,
        after
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOrderAuditLogParams struct {
	OrderNumber    int64              `json:"order_number"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	Actor          string             `json:"actor"`
	Action         string             `json:"action"`
	Reason         string             `json:"reason"`
	Before         []byte             `json:"before"`
	After          []byte             `json:"after"`
}

func (q *Queries) CreateOrderAuditLog(ctx context.Context, arg CreateOrderAuditLogParams) error {
	_, err := q.db.Exec(ctx, createOrderAuditLog,
		arg.OrderNumber,
		arg.EventTimestamp,
		arg.Actor,
		arg.Action,
		arg.Reason,
		arg.Before,
		arg.After,
	)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_number, price_value, price_currency, status, external_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_number, price_value, price_currency, status, external_ref, order_secret_key
`

type CreatePaymentParams struct {
	OrderNumber   int64   `json:"order_number"`
	PriceValue    *int64  `json:"price_value"`
	PriceCurrency *string `json:"price_currency"`
	Status        string  `json:"status"`
	ExternalRef   string  `json:"external_ref"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderNumber,
		arg.PriceValue,
		arg.PriceCurrency,
		arg.Status,
		arg.ExternalRef,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.PriceValue,
		&i.PriceCurrency,
		&i.Status,
		&i.ExternalRef,
		&i.OrderSecretKey,
	)
	return i, err
}

const getOrderByOrderNumber = `-- name: GetOrderByOrderNumber :one
SELECT order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at, secret_key, product_owner, payout_phone_number FROM orders WHERE order_number = $1
`

func (q *Queries) GetOrderByOrderNumber(ctx context.Context, orderNumber int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.OrderNumber,
		&i.DeliveryLocation,
		&i.PriceValue,
		&i.PriceCurrency,
		&i.Status,
		&i.Rating,
		&i.Review,
		&i.Product,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretKey,
		&i.ProductOwner,
		&i.PayoutPhoneNumber,
	)
	return i, err
}

const getPaymentByExternalReference = `-- name: GetPaymentByExternalReference :one
SELECT id, order_number, price_value, price_currency, status, external_ref, order_secret_key from payments WHERE external_ref = $1
LIMIT 1
`

func (q *Queries) GetPaymentByExternalReference(ctx context.Context, externalRef string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByExternalReference, externalRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.PriceValue,
		&i.PriceCurrency,
		&i.Status,
		&i.ExternalRef,
		&i.OrderSecretKey,
	)
	return i, err
}

const getUserOrderBySecretKey = `-- name: GetUserOrderBySecretKey :one
SELECT order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at, secret_key, product_owner, payout_phone_number FROM orders WHERE secret_key = $1 AND created_by = $2
`

type GetUserOrderBySecretKeyParams struct {
	SecretKey *string `json:"secret_key"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) GetUserOrderBySecretKey(ctx context.Context, arg GetUserOrderBySecretKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getUserOrderBySecretKey, arg.SecretKey, arg.CreatedBy)
	var i Order
	err := row.Scan(
		&i.OrderNumber,
		&i.DeliveryLocation,
		&i.PriceValue,
		&i.PriceCurrency,
		&i.Status,
		&i.Rating,
		&i.Review,
		&i.Product,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretKey,
		&i.ProductOwner,
		&i.PayoutPhoneNumber,
	)
	return i, err
}

const listFarmerOrders = `-- name: ListFarmerOrders :many
SELECT order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at, secret_key, product_owner, payout_phone_number FROM orders 
WHERE product_owner = $1
AND 
  ($2::timestamptz = '0001-01-01 00:00:00+00'::timestamptz OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3::int
`

type ListFarmerOrdersParams struct {
	ProductOwner  *string   `json:"product_owner"`
	CreatedBefore time.Time `json:"created_before"`
	Count         int32     `json:"count"`
}

func (q *Queries) ListFarmerOrders(ctx context.Context, arg ListFarmerOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listFarmerOrders, arg.ProductOwner, arg.CreatedBefore, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderNumber,
			&i.DeliveryLocation,
			&i.PriceValue,
			&i.PriceCurrency,
			&i.Status,
			&i.Rating,
			&i.Review,
			&i.Product,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretKey,
			&i.ProductOwner,
			&i.PayoutPhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderAuditLogs = `-- name: ListOrderAuditLogs :many
SELECT id, event_timestamp, order_number, actor, action, reason, before, after from orders_audit WHERE order_number = $1
`

func (q *Queries) ListOrderAuditLogs(ctx context.Context, orderNumber int64) ([]OrdersAudit, error) {
	rows, err := q.db.Query(ctx, listOrderAuditLogs, orderNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersAudit{}
	for rows.Next() {
		var i OrdersAudit
		if err := rows.Scan(
			&i.ID,
			&i.EventTimestamp,
			&i.OrderNumber,
			&i.Actor,
			&i.Action,
			&i.Reason,
			&i.Before,
			&i.After,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT order_number, delivery_location, price_value, price_currency, status, rating, review, product, created_by, created_at, updated_at, secret_key, product_owner, payout_phone_number FROM orders 
WHERE created_by = $1
AND 
  ($2::timestamptz = '0001-01-01 00:00:00+00'::timestamptz OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3::int
`

type ListUserOrdersParams struct {
	CreatedBy     *string   `json:"created_by"`
	CreatedBefore time.Time `json:"created_before"`
	Count         int32     `json:"count"`
}

func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUserOrders, arg.CreatedBy, arg.CreatedBefore, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderNumber,
			&i.DeliveryLocation,
			&i.PriceValue,
			&i.PriceCurrency,
			&i.Status,
			&i.Rating,
			&i.Review,
			&i.Product,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretKey,
			&i.ProductOwner,
			&i.PayoutPhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewOrder = `-- name: ReviewOrder :exec
UPDATE orders SET review = $1, rating = $2 WHERE order_number = $3
`

type ReviewOrderParams struct {
	Review      string         `json:"review"`
	Rating      pgtype.Numeric `json:"rating"`
	OrderNumber int64          `json:"order_number"`
}

func (q *Queries) ReviewOrder(ctx context.Context, arg ReviewOrderParams) error {
	_, err := q.db.Exec(ctx, reviewOrder, arg.Review, arg.Rating, arg.OrderNumber)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE order_number = $1
`

type UpdateOrderStatusParams struct {
	OrderNumber int64  `json:"order_number"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.OrderNumber, arg.Status)
	return err
}

const updatePaymentStatusByExternalReference = `-- name: UpdatePaymentStatusByExternalReference :exec
UPDATE payments SET status = $2 WHERE external_ref = $1
`

type UpdatePaymentStatusByExternalReferenceParams struct {
	ExternalRef string `json:"external_ref"`
	Status      string `json:"status"`
}

func (q *Queries) UpdatePaymentStatusByExternalReference(ctx context.Context, arg UpdatePaymentStatusByExternalReferenceParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatusByExternalReference, arg.ExternalRef, arg.Status)
	return err
}

const updatePaymentStatusBySecretKey = `-- name: UpdatePaymentStatusBySecretKey :exec
UPDATE payments SET status = $2 WHERE order_secret_key = $1
`

type UpdatePaymentStatusBySecretKeyParams struct {
	OrderSecretKey *string `json:"order_secret_key"`
	Status         string  `json:"status"`
}

func (q *Queries) UpdatePaymentStatusBySecretKey(ctx context.Context, arg UpdatePaymentStatusBySecretKeyParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatusBySecretKey, arg.OrderSecretKey, arg.Status)
	return err
}
