// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	AggregateCommissionByReferrer(ctx context.Context, arg AggregateCommissionByReferrerParams) ([]AggregateCommissionByReferrerRow, error)
	BulkSettleCommissions(ctx context.Context, arg BulkSettleCommissionsParams) error
	BulkUpdateCommissionsPaymentReference(ctx context.Context, arg BulkUpdateCommissionsPaymentReferenceParams) error
	CountUniqueOrdersByReferrer(ctx context.Context, arg CountUniqueOrdersByReferrerParams) (int64, error)
	CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error)
	CreateDeliveryPoint(ctx context.Context, arg CreateDeliveryPointParams) (DeliveryPoint, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderAuditLog(ctx context.Context, arg CreateOrderAuditLogParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	DeleteDeliveryPoint(ctx context.Context, id string) error
	GetCommissionsByIDsForUpdate(ctx context.Context, commissionIds []string) ([]Commission, error)
	GetOrderByOrderNumber(ctx context.Context, orderNumber int64) (GetOrderByOrderNumberRow, error)
	GetOrderItemsByOrderNumber(ctx context.Context, orderNumber int32) ([]OrderItem, error)
	GetOrderStatsBetweenDates(ctx context.Context, arg GetOrderStatsBetweenDatesParams) (int64, error)
	GetOrdersGroupedByDay(ctx context.Context, arg GetOrdersGroupedByDayParams) ([]GetOrdersGroupedByDayRow, error)
	GetOrdersGroupedByMonth(ctx context.Context, arg GetOrdersGroupedByMonthParams) ([]GetOrdersGroupedByMonthRow, error)
	GetOrdersGroupedByYear(ctx context.Context, arg GetOrdersGroupedByYearParams) ([]GetOrdersGroupedByYearRow, error)
	GetPaymentByEntity(ctx context.Context, arg GetPaymentByEntityParams) (Payment, error)
	GetPaymentById(ctx context.Context, id string) (Payment, error)
	GetPaymentStatsBetweenDates(ctx context.Context, arg GetPaymentStatsBetweenDatesParams) (float64, error)
	GetUserOrderBySecretKey(ctx context.Context, secretKey *string) (GetUserOrderBySecretKeyRow, error)
	ListCommissionsByReferrer(ctx context.Context, arg ListCommissionsByReferrerParams) ([]Commission, error)
	ListDeliveryPoints(ctx context.Context, arg ListDeliveryPointsParams) ([]DeliveryPoint, error)
	ListFarmerOrders(ctx context.Context, arg ListFarmerOrdersParams) ([]ListFarmerOrdersRow, error)
	ListOrderAuditLogs(ctx context.Context, orderNumber int64) ([]OrdersAudit, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListUniqueCities(ctx context.Context) ([]string, error)
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]ListUserOrdersRow, error)
	ReviewOrder(ctx context.Context, arg ReviewOrderParams) error
	UpdateDeliveryPoint(ctx context.Context, arg UpdateDeliveryPointParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
