// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateDeliveryPoint(ctx context.Context, arg CreateDeliveryPointParams) (DeliveryPoint, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderAuditLog(ctx context.Context, arg CreateOrderAuditLogParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	GetOrderByOrderNumber(ctx context.Context, orderNumber int64) (Order, error)
	GetPaymentByEntity(ctx context.Context, arg GetPaymentByEntityParams) (Payment, error)
	GetPaymentById(ctx context.Context, id string) (Payment, error)
	GetUserOrderBySecretKey(ctx context.Context, arg GetUserOrderBySecretKeyParams) (Order, error)
	ListDeliveryPoints(ctx context.Context, arg ListDeliveryPointsParams) ([]DeliveryPoint, error)
	ListFarmerOrders(ctx context.Context, arg ListFarmerOrdersParams) ([]Order, error)
	ListOrderAuditLogs(ctx context.Context, orderNumber int64) ([]OrdersAudit, error)
	ListUniqueCities(ctx context.Context) ([]string, error)
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error)
	ReviewOrder(ctx context.Context, arg ReviewOrderParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
