// This file is auto-generated by @hey-api/openapi-ts

/**
 * Message that represents an arbitrary HTTP body. It should only be used for
 * payload formats that can't be represented as JSON, such as raw binary or
 * an HTML page.
 *
 *
 * This message can be used both in streaming and non-streaming API methods in
 * the request as well as the response.
 *
 * It can be used as a top-level request field, which is convenient if one
 * wants to extract parameters from either the URL or HTTP template into the
 * request fields and also want access to the raw HTTP body.
 *
 * Example:
 *
 * message GetResourceRequest {
 * // A unique request id.
 * string request_id = 1;
 *
 * // The raw HTTP body is bound to this field.
 * google.api.HttpBody http_body = 2;
 *
 * }
 *
 * service ResourceService {
 * rpc GetResource(GetResourceRequest)
 * returns (google.api.HttpBody);
 * rpc UpdateResource(google.api.HttpBody)
 * returns (google.protobuf.Empty);
 *
 * }
 *
 * Example with streaming methods:
 *
 * service CaldavService {
 * rpc GetCalendar(stream google.api.HttpBody)
 * returns (stream google.api.HttpBody);
 * rpc UpdateCalendar(stream google.api.HttpBody)
 * returns (stream google.api.HttpBody);
 *
 * }
 *
 * Use of this type only changes how the request and response bodies are
 * handled, all other features will continue to work unchanged.
 */
export type apiHttpBody = {
  /**
   * The HTTP Content-Type header value specifying the content type of the body.
   */
  contentType?: string;
  /**
   * The HTTP request/response body as raw binary.
   */
  data?: string;
  /**
   * Application specific response metadata. Must be set in the first response
   * for streaming APIs.
   */
  extensions?: Array<protobufAny>;
};

/**
 * `Any` contains an arbitrary serialized protocol buffer message along with a
 * URL that describes the type of the serialized message.
 *
 * Protobuf library provides support to pack/unpack Any values in the form
 * of utility functions or additional generated methods of the Any type.
 *
 * Example 1: Pack and unpack a message in C++.
 *
 * Foo foo = ...;
 * Any any;
 * any.PackFrom(foo);
 * ...
 * if (any.UnpackTo(&foo)) {
 * ...
 * }
 *
 * Example 2: Pack and unpack a message in Java.
 *
 * Foo foo = ...;
 * Any any = Any.pack(foo);
 * ...
 * if (any.is(Foo.class)) {
 * foo = any.unpack(Foo.class);
 * }
 *
 * Example 3: Pack and unpack a message in Python.
 *
 * foo = Foo(...)
 * any = Any()
 * any.Pack(foo)
 * ...
 * if any.Is(Foo.DESCRIPTOR):
 * any.Unpack(foo)
 * ...
 *
 * Example 4: Pack and unpack a message in Go
 *
 * foo := &pb.Foo{...}
 * any, err := anypb.New(foo)
 * if err != nil {
 * ...
 * }
 * ...
 * foo := &pb.Foo{}
 * if err := any.UnmarshalTo(foo); err != nil {
 * ...
 * }
 *
 * The pack methods provided by protobuf library will by default use
 * 'type.googleapis.com/full.type.name' as the type URL and the unpack
 * methods only use the fully qualified type name after the last '/'
 * in the type URL, for example "foo.bar.com/x/y.z" will yield type
 * name "y.z".
 *
 *
 * JSON
 *
 * The JSON representation of an `Any` value uses the regular
 * representation of the deserialized, embedded message, with an
 * additional field `@type` which contains the type URL. Example:
 *
 * package google.profile;
 * message Person {
 * string first_name = 1;
 * string last_name = 2;
 * }
 *
 * {
 * "@type": "type.googleapis.com/google.profile.Person",
 * "firstName": <string>,
 * "lastName": <string>
 * }
 *
 * If the embedded message type is well-known and has a custom JSON
 * representation, that representation will be embedded adding a field
 * `value` which holds the custom JSON in addition to the `@type`
 * field. Example (for message [google.protobuf.Duration][]):
 *
 * {
 * "@type": "type.googleapis.com/google.protobuf.Duration",
 * "value": "1.212s"
 * }
 */
export type protobufAny = {
  [key: string]: unknown;
};

export type rpcStatus = {
  code?: number;
  message?: string;
  details?: Array<protobufAny>;
};

export type typesPoint = {
  lon?: number;
  lat?: number;
  address?: string;
};

export type UsersCompleteRegistrationBody = {
  firstName?: string;
  lastName?: string;
  email?: string;
  address?: string;
  profileImage?: string;
  locationCoordinates?: typesPoint;
  referredBy?: string;
  phoneNumber?: string;
};

export type UsersCreateKYCBody = {
  identityDocumentUrl?: string;
  selfieUrl?: string;
  vehicleDocumentUrl?: string;
};

export type UsersGrantAdminBody = {
  phoneNumber?: string;
  residenceCountryIsoCode?: string;
  password?: string;
};

export type UsersGrantAgentBody = {
  phoneNumber?: string;
  residenceCountryIsoCode?: string;
  address?: string;
  email?: string;
  password?: string;
  role?: usersgrpcUserRole;
};

/**
 * Request and response messages for gRPC methods.
 */
export type usersgrpcAdditionalFactor = {
  factorType?: usersgrpcFactorType;
  requestId?: string;
  factorHint?: string;
};

export type usersgrpcAuthenticateRequest = {
  factors?: Array<usersgrpcAuthFactor>;
};

export type usersgrpcAuthenticateResponse = {
  loginComplete?: boolean;
  additionalFactor?: usersgrpcAdditionalFactor;
  tokens?: usersgrpcTokens;
  userId?: string;
};

export type usersgrpcAuthFactor = {
  type?: usersgrpcFactorType;
  id?: string;
  secretValue?: string;
};

export type usersgrpcChangePasswordRequest = {
  newPassword?: string;
  emailFactor?: usersgrpcAuthFactor;
};

export type usersgrpcChangePasswordResponse = {
  message?: string;
};

export type usersgrpcCompleteRegistrationResponse = {
  message?: string;
};

export type usersgrpcCreateKYCResponse = {
  kycVerification?: usersgrpcKYCVerification;
};

export type usersgrpcDeleteAgentResponse = unknown;

export type usersgrpcDeleteUserAccountResponse = unknown;

export type usersgrpcFactorType =
  | "FACTOR_TYPE_UNSPECIFIED"
  | "FACTOR_TYPE_EMAIL_PASSWORD"
  | "FACTOR_TYPE_SMS_OTP"
  | "FACTOR_TYPE_EMAIL_OTP"
  | "FACTOR_TYPE_EMAIL_PHONE_PASSWORD"
  | "FACTOR_TYPE_GOOGLE"
  | "FACTOR_TYPE_APPLE";

export type usersgrpcFarmerWithRating = {
  user?: usersgrpcUser;
  rating?: number;
};

export type usersgrpcGetFarmerByIDResponse = {
  user?: usersgrpcUser;
  rating?: number;
};

export type usersgrpcGetKYCByUserIDResponse = {
  kycVerification?: usersgrpcKYCVerification;
};

export type usersgrpcGetPublicUserResponse = {
  name?: string;
  profileImage?: string;
};

export type usersgrpcGetReferralByReferredIdResponse = {
  referral?: usersgrpcReferral;
};

export type usersgrpcGetUserByIDResponse = {
  user?: usersgrpcUser;
};

export type usersgrpcGetUserStatsResponse = {
  data?: Array<usersgrpcStatItem>;
};

export type usersgrpcGrantAdminResponse = {
  message?: string;
};

export type usersgrpcGrantAgentResponse = {
  message?: string;
};

export type usersgrpcHealthCheckResponse = unknown;

export type usersgrpcKYCStatus =
  | "KYC_STATUS_UNSPECIFIED"
  | "KYC_STATUS_PENDING"
  | "KYC_STATUS_VERIFIED"
  | "KYC_STATUS_REJECTED";

export type usersgrpcKYCVerification = {
  id?: string;
  userId?: string;
  identityDocumentUrl?: string;
  selfieUrl?: string;
  vehicleDocumentUrl?: string;
  status?: usersgrpcKYCStatus;
  rejectionReason?: string;
  verifiedAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type usersgrpcLastOtpForFactorResponse = {
  otp?: string;
};

export type usersgrpcListFarmersReivewsResponse = {
  reviews?: Array<usersgrpcReview>;
  nextKey?: string;
};

export type usersgrpcListFarmersResponse = {
  farmers?: Array<usersgrpcFarmerWithRating>;
  nextKey?: string;
};

export type usersgrpcListKYCVerificationsResponse = {
  kycVerifications?: Array<usersgrpcKYCVerification>;
  total?: string;
};

export type usersgrpcListUsersResponse = {
  users?: Array<usersgrpcUser>;
  nextKey?: string;
};

export type usersgrpcNotifyFarmerResponse = {
  success?: boolean;
};

export type usersgrpcOtpIntent =
  | "OTP_INTENT_UNSPECIFIED"
  | "OTP_INTENT_LOGIN"
  | "OTP_INTENT_RESET_PASSWORD"
  | "OTP_INTENT_SIGNUP"
  | "OTP_INTENT_VERIFY_EMAIL";

export type usersgrpcReactivateUserResponse = unknown;

export type usersgrpcReferral = {
  id?: string;
  referrerId?: string;
  referredId?: string;
  createdAt?: string;
};

export type usersgrpcRefreshAccessTokenRequest = {
  refreshToken?: string;
};

export type usersgrpcRefreshAccessTokenResponse = {
  accessToken?: string;
};

export type usersgrpcReview = {
  id?: string;
  farmerId?: string;
  orderId?: string;
  productId?: string;
  rating?: number;
  comment?: string;
  createdBy?: string;
  createdAt?: string;
};

export type usersgrpcReviewFarmerResponse = unknown;

export type usersgrpcRevokeRefreshTokenRequest = {
  refreshToken?: string;
};

export type usersgrpcRevokeRefreshTokenResponse = {
  message?: string;
};

export type usersgrpcSendEmailOtpRequest = {
  email?: string;
  intent?: usersgrpcOtpIntent;
};

export type usersgrpcSendEmailOtpResponse = {
  requestId?: string;
};

export type usersgrpcSendSignupSmsOtpRequest = {
  phoneNumber?: string;
  intent?: usersgrpcOtpIntent;
};

export type usersgrpcSendSignUpSmsOtpResponse = {
  requestId?: string;
};

export type usersgrpcSendSmsOtpRequest = {
  phoneNumber?: string;
  intent?: usersgrpcOtpIntent;
};

export type usersgrpcSendSmsOtpResponse = {
  requestId?: string;
};

export type usersgrpcSignupRequest = {
  phoneFactor?: usersgrpcAuthFactor;
  residenceCountryIsoCode?: string;
  password?: string;
  userType?: usersgrpcUserType;
  email?: string;
};

export type usersgrpcSignupResponse = {
  userId?: string;
  tokens?: usersgrpcTokens;
};

export type usersgrpcStatItem = {
  title?: string;
  value?: number;
  change?: number;
  description?: string;
};

export type usersgrpcSuspendUserResponse = unknown;

export type usersgrpcTokens = {
  accessToken?: string;
  refreshToken?: string;
};

export type usersgrpcUpdateKYCStatusResponse = {
  kycVerification?: usersgrpcKYCVerification;
};

export type usersgrpcUser = {
  userId?: string;
  role?: usersgrpcUserRole;
  phoneNumber?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  residenceCountryIsoCode?: string;
  locationCoordinates?: typesPoint;
  profileImage?: string;
  address?: string;
  createdAt?: string;
  updatedAt?: string;
  status?: usersgrpcUserStatus;
  referralCode?: string;
};

export type usersgrpcUserRole =
  | "USER_ROLE_UNSPECIFIED"
  | "USER_ROLE_FARMER"
  | "USER_ROLE_BUYER"
  | "USER_ROLE_ADMIN"
  | "USER_ROLE_AGENT"
  | "USER_ROLE_MARKETING_AGENT";

export type usersgrpcUserStatus =
  | "UserStatus_UNSPECIFIED"
  | "UserStatus_SUSPENDED"
  | "UserStatus_ACTIVE";

export type usersgrpcUserType =
  | "USER_TYPE_UNSPECIFIED"
  | "USER_TYPE_FARMER"
  | "USER_TYPE_BUYER"
  | "USER_TYPE_AGENT";

export type usersgrpcVerifyOtpRequest = {
  authFactor?: usersgrpcAuthFactor;
};

export type usersgrpcVerifyOtpResponse = {
  valid?: boolean;
};

export type UsersOAuthBody = {
  factor?: {
    type?: usersgrpcFactorType;
    secretValue?: string;
  };
  user?: usersgrpcUser;
  userType?: usersgrpcUserType;
};

export type UsersReactivateUserBody = unknown;

export type UsersReviewFarmerBody = {
  farmerId?: string;
  orderId?: string;
  productId?: string;
  rating?: number;
  comment?: string;
};

export type UsersSuspendUserBody = unknown;

export type UsersUpdateKYCStatusBody = {
  status?: usersgrpcKYCStatus;
  rejectionReason?: string;
};

export type UsersListKycVerificationsData = {
  query?: {
    limit?: number;
    offset?: number;
    status?:
      | "KYC_STATUS_UNSPECIFIED"
      | "KYC_STATUS_PENDING"
      | "KYC_STATUS_VERIFIED"
      | "KYC_STATUS_REJECTED";
  };
};

export type UsersListKycVerificationsResponse =
  usersgrpcListKYCVerificationsResponse;

export type UsersListKycVerificationsError = rpcStatus;

export type UsersUpdateKycStatusData = {
  body: UsersUpdateKYCStatusBody;
  path: {
    adminUserId: string;
    kycId: string;
  };
};

export type UsersUpdateKycStatusResponse = usersgrpcUpdateKYCStatusResponse;

export type UsersUpdateKycStatusError = rpcStatus;

export type UsersExportUsersPdfData = {
  path: {
    adminUserId: string;
  };
  query?: {
    /**
     * Optional keyword search (name/email/phone).
     */
    search?: string;
    /**
     * Filter by role (buyers vs farmers).
     */
    userRole?:
      | "USER_ROLE_UNSPECIFIED"
      | "USER_ROLE_FARMER"
      | "USER_ROLE_BUYER"
      | "USER_ROLE_ADMIN"
      | "USER_ROLE_AGENT"
      | "USER_ROLE_MARKETING_AGENT";
    /**
     * Optional status filter.
     */
    userStatus?:
      | "UserStatus_UNSPECIFIED"
      | "UserStatus_SUSPENDED"
      | "UserStatus_ACTIVE";
  };
};

export type UsersExportUsersPdfResponse = apiHttpBody;

export type UsersExportUsersPdfError = rpcStatus;

export type UsersGrantAdminData = {
  body: UsersGrantAdminBody;
  path: {
    adminUserId: string;
  };
};

export type UsersGrantAdminResponse = usersgrpcGrantAdminResponse;

export type UsersGrantAdminError = rpcStatus;

export type UsersGrantAgentData = {
  body: UsersGrantAgentBody;
  path: {
    adminUserId: string;
  };
};

export type UsersGrantAgentResponse = usersgrpcGrantAgentResponse;

export type UsersGrantAgentError = rpcStatus;

export type UsersListUsersData = {
  path: {
    adminUserId: string;
  };
  query?: {
    /**
     * Number of users to retrieve
     */
    count?: number;
    /**
     * keyword search for the users (could be name, or email)
     */
    search?: string;
    /**
     * Key for pagination, indicating where to start the list
     */
    startKey?: string;
    userRole?:
      | "USER_ROLE_UNSPECIFIED"
      | "USER_ROLE_FARMER"
      | "USER_ROLE_BUYER"
      | "USER_ROLE_ADMIN"
      | "USER_ROLE_AGENT"
      | "USER_ROLE_MARKETING_AGENT";
    userStatus?:
      | "UserStatus_UNSPECIFIED"
      | "UserStatus_SUSPENDED"
      | "UserStatus_ACTIVE";
  };
};

export type UsersListUsersResponse = usersgrpcListUsersResponse;

export type UsersListUsersError = rpcStatus;

export type UsersDeleteAgentData = {
  path: {
    adminUserId: string;
    userId: string;
  };
};

export type UsersDeleteAgentResponse = usersgrpcDeleteAgentResponse;

export type UsersDeleteAgentError = rpcStatus;

export type UsersReactivateUserData = {
  body: UsersReactivateUserBody;
  path: {
    adminUserId: string;
    userId: string;
  };
};

export type UsersReactivateUserResponse = usersgrpcReactivateUserResponse;

export type UsersReactivateUserError = rpcStatus;

export type UsersSuspendUserData = {
  body: UsersSuspendUserBody;
  path: {
    adminUserId: string;
    userId: string;
  };
};

export type UsersSuspendUserResponse = usersgrpcSuspendUserResponse;

export type UsersSuspendUserError = rpcStatus;

export type UsersOAuthData = {
  body: UsersOAuthBody;
  path: {
    /**
     * for OTPs this will be a request_id, for email_password this
     * will be the email address
     */
    "factor.id": string;
  };
};

export type UsersOAuthResponse = usersgrpcAuthenticateResponse;

export type UsersOAuthError = rpcStatus;

export type UsersRevokeRefreshTokenData = {
  body: usersgrpcRevokeRefreshTokenRequest;
};

export type UsersRevokeRefreshTokenResponse =
  usersgrpcRevokeRefreshTokenResponse;

export type UsersRevokeRefreshTokenError = rpcStatus;

export type UsersAuthenticateData = {
  body: usersgrpcAuthenticateRequest;
};

export type UsersAuthenticateResponse = usersgrpcAuthenticateResponse;

export type UsersAuthenticateError = rpcStatus;

export type UsersChangePasswordData = {
  body: usersgrpcChangePasswordRequest;
};

export type UsersChangePasswordResponse = usersgrpcChangePasswordResponse;

export type UsersChangePasswordError = rpcStatus;

export type UsersHealthCheckResponse = usersgrpcHealthCheckResponse;

export type UsersHealthCheckError = rpcStatus;

export type UsersLastOtpForFactorData = {
  query?: {
    factor?: string;
  };
};

export type UsersLastOtpForFactorResponse = usersgrpcLastOtpForFactorResponse;

export type UsersLastOtpForFactorError = rpcStatus;

export type UsersRefreshAccessTokenData = {
  body: usersgrpcRefreshAccessTokenRequest;
};

export type UsersRefreshAccessTokenResponse =
  usersgrpcRefreshAccessTokenResponse;

export type UsersRefreshAccessTokenError = rpcStatus;

export type UsersSendEmailOtpData = {
  body: usersgrpcSendEmailOtpRequest;
};

export type UsersSendEmailOtpResponse = usersgrpcSendEmailOtpResponse;

export type UsersSendEmailOtpError = rpcStatus;

export type UsersSendSignupSmsOtpData = {
  body: usersgrpcSendSignupSmsOtpRequest;
};

export type UsersSendSignupSmsOtpResponse = usersgrpcSendSignUpSmsOtpResponse;

export type UsersSendSignupSmsOtpError = rpcStatus;

export type UsersSendSmsOtpData = {
  body: usersgrpcSendSmsOtpRequest;
};

export type UsersSendSmsOtpResponse = usersgrpcSendSmsOtpResponse;

export type UsersSendSmsOtpError = rpcStatus;

export type UsersSignupData = {
  body: usersgrpcSignupRequest;
};

export type UsersSignupResponse = usersgrpcSignupResponse;

export type UsersSignupError = rpcStatus;

export type UsersVerifyOtpData = {
  body: usersgrpcVerifyOtpRequest;
};

export type UsersVerifyOtpResponse = usersgrpcVerifyOtpResponse;

export type UsersVerifyOtpError = rpcStatus;

export type UsersGetPublicUserData = {
  path: {
    userId: string;
  };
};

export type UsersGetPublicUserResponse = usersgrpcGetPublicUserResponse;

export type UsersGetPublicUserError = rpcStatus;

export type UsersCompleteRegistrationData = {
  body: UsersCompleteRegistrationBody;
  path: {
    userId: string;
  };
};

export type UsersCompleteRegistrationResponse =
  usersgrpcCompleteRegistrationResponse;

export type UsersCompleteRegistrationError = rpcStatus;

export type UsersDeleteUserAccountData = {
  path: {
    userId: string;
  };
};

export type UsersDeleteUserAccountResponse = usersgrpcDeleteUserAccountResponse;

export type UsersDeleteUserAccountError = rpcStatus;

export type UsersListFarmersData = {
  path: {
    userId: string;
  };
  query?: {
    count?: number;
    searchKey?: string;
    sortCreatedAtDesc?: boolean;
    startKey?: string;
    userStatus?:
      | "UserStatus_UNSPECIFIED"
      | "UserStatus_SUSPENDED"
      | "UserStatus_ACTIVE";
  };
};

export type UsersListFarmersResponse = usersgrpcListFarmersResponse;

export type UsersListFarmersError = rpcStatus;

export type UsersListFarmersReivewsData = {
  path: {
    farmerId: string;
    userId: string;
  };
  query?: {
    count?: number;
    startKey?: string;
  };
};

export type UsersListFarmersReivewsResponse =
  usersgrpcListFarmersReivewsResponse;

export type UsersListFarmersReivewsError = rpcStatus;

export type UsersGetUserByIdData = {
  path: {
    /**
     * ID of the user to fetch
     */
    userId: string;
  };
};

export type UsersGetUserByIdResponse = usersgrpcGetUserByIDResponse;

export type UsersGetUserByIdError = rpcStatus;

export type UsersGetKycByUserIdData = {
  path: {
    userId: string;
  };
};

export type UsersGetKycByUserIdResponse = usersgrpcGetKYCByUserIDResponse;

export type UsersGetKycByUserIdError = rpcStatus;

export type UsersCreateKycData = {
  body: UsersCreateKYCBody;
  path: {
    userId: string;
  };
};

export type UsersCreateKycResponse = usersgrpcCreateKYCResponse;

export type UsersCreateKycError = rpcStatus;

export type UsersReviewFarmerData = {
  body: UsersReviewFarmerBody;
  path: {
    userId: string;
  };
};

export type UsersReviewFarmerResponse = usersgrpcReviewFarmerResponse;

export type UsersReviewFarmerError = rpcStatus;

export type UsersGetFarmerByIdData = {
  path: {
    /**
     * ID of the farmer to be fetched
     */
    farmerId: string;
    /**
     * ID of the user fetching the farmer
     */
    userId: string;
  };
};

export type UsersGetFarmerByIdResponse = usersgrpcGetFarmerByIDResponse;

export type UsersGetFarmerByIdError = rpcStatus;
