// Code generated by MockGen. DO NOT EDIT.
// Source: ./sqlc (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination sqlc/mocks/querier.go -package mocks ./sqlc Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/foodhouse/foodhouseapp/products/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockQuerier) CreateCategory(ctx context.Context, arg sqlc.CreateCategoryParams) (sqlc.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, arg)
	ret0, _ := ret[0].(sqlc.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockQuerierMockRecorder) CreateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockQuerier)(nil).CreateCategory), ctx, arg)
}

// CreatePriceType mocks base method.
func (m *MockQuerier) CreatePriceType(ctx context.Context, arg sqlc.CreatePriceTypeParams) (sqlc.PriceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePriceType", ctx, arg)
	ret0, _ := ret[0].(sqlc.PriceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePriceType indicates an expected call of CreatePriceType.
func (mr *MockQuerierMockRecorder) CreatePriceType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePriceType", reflect.TypeOf((*MockQuerier)(nil).CreatePriceType), ctx, arg)
}

// CreateProduct mocks base method.
func (m *MockQuerier) CreateProduct(ctx context.Context, arg sqlc.CreateProductParams) (sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, arg)
	ret0, _ := ret[0].(sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockQuerierMockRecorder) CreateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockQuerier)(nil).CreateProduct), ctx, arg)
}

// CreateProductName mocks base method.
func (m *MockQuerier) CreateProductName(ctx context.Context, arg sqlc.CreateProductNameParams) (sqlc.ProductName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductName", ctx, arg)
	ret0, _ := ret[0].(sqlc.ProductName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductName indicates an expected call of CreateProductName.
func (mr *MockQuerierMockRecorder) CreateProductName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductName", reflect.TypeOf((*MockQuerier)(nil).CreateProductName), ctx, arg)
}

// DeletePriceType mocks base method.
func (m *MockQuerier) DeletePriceType(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePriceType", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePriceType indicates an expected call of DeletePriceType.
func (mr *MockQuerierMockRecorder) DeletePriceType(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePriceType", reflect.TypeOf((*MockQuerier)(nil).DeletePriceType), ctx, id)
}

// DeleteProduct mocks base method.
func (m *MockQuerier) DeleteProduct(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockQuerierMockRecorder) DeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockQuerier)(nil).DeleteProduct), ctx, id)
}

// DeleteProductName mocks base method.
func (m *MockQuerier) DeleteProductName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductName indicates an expected call of DeleteProductName.
func (mr *MockQuerierMockRecorder) DeleteProductName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductName", reflect.TypeOf((*MockQuerier)(nil).DeleteProductName), ctx, name)
}

// GetCategory mocks base method.
func (m *MockQuerier) GetCategory(ctx context.Context, id string) (sqlc.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, id)
	ret0, _ := ret[0].(sqlc.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockQuerierMockRecorder) GetCategory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockQuerier)(nil).GetCategory), ctx, id)
}

// GetProduct mocks base method.
func (m *MockQuerier) GetProduct(ctx context.Context, id string) (sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockQuerierMockRecorder) GetProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockQuerier)(nil).GetProduct), ctx, id)
}

// GetProductForUpdate mocks base method.
func (m *MockQuerier) GetProductForUpdate(ctx context.Context, id string) (sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductForUpdate", ctx, id)
	ret0, _ := ret[0].(sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductForUpdate indicates an expected call of GetProductForUpdate.
func (mr *MockQuerierMockRecorder) GetProductForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductForUpdate", reflect.TypeOf((*MockQuerier)(nil).GetProductForUpdate), ctx, id)
}

// GetProductWithCategory mocks base method.
func (m *MockQuerier) GetProductWithCategory(ctx context.Context, id string) (sqlc.GetProductWithCategoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductWithCategory", ctx, id)
	ret0, _ := ret[0].(sqlc.GetProductWithCategoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductWithCategory indicates an expected call of GetProductWithCategory.
func (mr *MockQuerierMockRecorder) GetProductWithCategory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductWithCategory", reflect.TypeOf((*MockQuerier)(nil).GetProductWithCategory), ctx, id)
}

// ListCategories mocks base method.
func (m *MockQuerier) ListCategories(ctx context.Context) ([]sqlc.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]sqlc.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockQuerierMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockQuerier)(nil).ListCategories), ctx)
}

// ListPriceTypesByCategory mocks base method.
func (m *MockQuerier) ListPriceTypesByCategory(ctx context.Context, categoryID string) ([]sqlc.PriceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPriceTypesByCategory", ctx, categoryID)
	ret0, _ := ret[0].([]sqlc.PriceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPriceTypesByCategory indicates an expected call of ListPriceTypesByCategory.
func (mr *MockQuerierMockRecorder) ListPriceTypesByCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPriceTypesByCategory", reflect.TypeOf((*MockQuerier)(nil).ListPriceTypesByCategory), ctx, categoryID)
}

// ListProductNamesByCategory mocks base method.
func (m *MockQuerier) ListProductNamesByCategory(ctx context.Context, categoryID string) ([]sqlc.ProductName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductNamesByCategory", ctx, categoryID)
	ret0, _ := ret[0].([]sqlc.ProductName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductNamesByCategory indicates an expected call of ListProductNamesByCategory.
func (mr *MockQuerierMockRecorder) ListProductNamesByCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductNamesByCategory", reflect.TypeOf((*MockQuerier)(nil).ListProductNamesByCategory), ctx, categoryID)
}

// ListProducts mocks base method.
func (m *MockQuerier) ListProducts(ctx context.Context, arg sqlc.ListProductsParams) ([]sqlc.ListProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockQuerierMockRecorder) ListProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockQuerier)(nil).ListProducts), ctx, arg)
}

// SumProductAmounts mocks base method.
func (m *MockQuerier) SumProductAmounts(ctx context.Context, arg sqlc.SumProductAmountsParams) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumProductAmounts", ctx, arg)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumProductAmounts indicates an expected call of SumProductAmounts.
func (mr *MockQuerierMockRecorder) SumProductAmounts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumProductAmounts", reflect.TypeOf((*MockQuerier)(nil).SumProductAmounts), ctx, arg)
}

// UpdateProduct mocks base method.
func (m *MockQuerier) UpdateProduct(ctx context.Context, arg sqlc.UpdateProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockQuerierMockRecorder) UpdateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockQuerier)(nil).UpdateProduct), ctx, arg)
}
