// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { ProductsCreateCategoryData, ProductsCreateCategoryError, ProductsCreateCategoryResponse, ProductsListCategoriesError, ProductsListCategoriesResponse, ProductsHealthCheckError, ProductsHealthCheckResponse, ProductsListProductsData, ProductsListProductsError, ProductsListProductsResponse, ProductsGetProductData, ProductsGetProductError, ProductsGetProductResponse, ProductsListFarmerProductsData, ProductsListFarmerProductsError, ProductsListFarmerProductsResponse, ProductsCreateProductData, ProductsCreateProductError, ProductsCreateProductResponse, ProductsDeleteProductData, ProductsDeleteProductError, ProductsDeleteProductResponse, ProductsGetFarmerProductData, ProductsGetFarmerProductError, ProductsGetFarmerProductResponse, ProductsUpdateProductData, ProductsUpdateProductError, ProductsUpdateProductResponse } from './types.gen';

export const client = createClient(createConfig());

export const productsCreateCategory = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProductsCreateCategoryData, ThrowOnError>) => {
    return (options?.client ?? client).post<ProductsCreateCategoryResponse, ProductsCreateCategoryError, ThrowOnError>({
        ...options,
        url: '/v1/admin/{userId}/products/create-category'
    });
};

export const productsListCategories = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ProductsListCategoriesResponse, ProductsListCategoriesError, ThrowOnError>({
        ...options,
        url: '/v1/public/products/get-categories'
    });
};

export const productsHealthCheck = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ProductsHealthCheckResponse, ProductsHealthCheckError, ThrowOnError>({
        ...options,
        url: '/v1/public/products/health-check'
    });
};

export const productsListProducts = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<ProductsListProductsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ProductsListProductsResponse, ProductsListProductsError, ThrowOnError>({
        ...options,
        url: '/v1/public/products/list-products'
    });
};

export const productsGetProduct = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProductsGetProductData, ThrowOnError>) => {
    return (options?.client ?? client).get<ProductsGetProductResponse, ProductsGetProductError, ThrowOnError>({
        ...options,
        url: '/v1/public/products/{productId}/get-product'
    });
};

export const productsListFarmerProducts = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProductsListFarmerProductsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ProductsListFarmerProductsResponse, ProductsListFarmerProductsError, ThrowOnError>({
        ...options,
        url: '/v1/user/{userId}/products/list-farmer-products'
    });
};

export const productsCreateProduct = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProductsCreateProductData, ThrowOnError>) => {
    return (options?.client ?? client).post<ProductsCreateProductResponse, ProductsCreateProductError, ThrowOnError>({
        ...options,
        url: '/v1/users/{userId}/products/create-product'
    });
};

export const productsDeleteProduct = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProductsDeleteProductData, ThrowOnError>) => {
    return (options?.client ?? client).delete<ProductsDeleteProductResponse, ProductsDeleteProductError, ThrowOnError>({
        ...options,
        url: '/v1/users/{userId}/products/{productId}/delete-product'
    });
};

export const productsGetFarmerProduct = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProductsGetFarmerProductData, ThrowOnError>) => {
    return (options?.client ?? client).get<ProductsGetFarmerProductResponse, ProductsGetFarmerProductError, ThrowOnError>({
        ...options,
        url: '/v1/users/{userId}/products/{productId}/get-farmer-product'
    });
};

export const productsUpdateProduct = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ProductsUpdateProductData, ThrowOnError>) => {
    return (options?.client ?? client).put<ProductsUpdateProductResponse, ProductsUpdateProductError, ThrowOnError>({
        ...options,
        url: '/v1/users/{userId}/products/{productId}/update-product'
    });
};