/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}/create-new-password` | `/create-new-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}/verify-otp` | `/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/order-details` | `/order-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/product-details` | `/product-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(index)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(index)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}/create-new-password` | `/create-new-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}/verify-otp` | `/verify-otp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/order-details` | `/order-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/product-details` | `/product-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(index)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(index)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(forgot-password)'}/create-new-password${`?${string}` | `#${string}` | ''}` | `/create-new-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(forgot-password)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${'/(forgot-password)'}/verify-otp${`?${string}` | `#${string}` | ''}` | `/verify-otp${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/order-details${`?${string}` | `#${string}` | ''}` | `/order-details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/product-details${`?${string}` | `#${string}` | ''}` | `/product-details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(index)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(index)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}/create-new-password` | `/create-new-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}${'/(forgot-password)'}/verify-otp` | `/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/order-details` | `/order-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/product-details` | `/product-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(index)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(index)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
