// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID              string             `json:"id"`
	ExternalRef     string             `json:"external_ref"`
	Amount          int64              `json:"amount"`
	Status          string             `json:"status"`
	CurrencyIsoCode string             `json:"currency_iso_code"`
	Method          string             `json:"method"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	Token     string             `json:"token"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type SentOtp struct {
	RequestID        string             `json:"request_id"`
	Factor           string             `json:"factor"`
	MaxAttempts      int32              `json:"max_attempts"`
	NumberOfAttempts int32              `json:"number_of_attempts"`
	FactorType       string             `json:"factor_type"`
	SecretValue      string             `json:"secret_value"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID              string          `json:"id"`
	Title           string          `json:"title"`
	Description     string          `json:"description"`
	Duration        pgtype.Interval `json:"duration"`
	Amount          int64           `json:"amount"`
	CurrencyIsoCode string          `json:"currency_iso_code"`
}

type User struct {
	ID                      string             `json:"id"`
	Role                    string             `json:"role"`
	PhoneNumber             string             `json:"phone_number"`
	Email                   *string            `json:"email"`
	FirstName               *string            `json:"first_name"`
	LastName                *string            `json:"last_name"`
	ResidenceCountryIsoCode string             `json:"residence_country_iso_code"`
	Address                 *string            `json:"address"`
	LocationCoordinates     pgtype.Point       `json:"location_coordinates"`
	ProfileImage            *string            `json:"profile_image"`
	Password                string             `json:"password"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type UserPaymentMethod struct {
	ID       string  `json:"id"`
	UserID   string  `json:"user_id"`
	Method   string  `json:"method"`
	MethodID *string `json:"method_id"`
}

type UserSubscription struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	SubscriptionID string             `json:"subscription_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt      time.Time          `json:"expires_at"`
}
