// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sent_otps.sql

package sqlc

import (
	"context"
)

const countSentOtpsToFactorToday = `-- name: CountSentOtpsToFactorToday :one
SELECT COUNT(*) FROM sent_otps
WHERE factor = $1
  AND DATE(created_at) = CURRENT_DATE
`

func (q *Queries) CountSentOtpsToFactorToday(ctx context.Context, factor string) (int64, error) {
	row := q.db.QueryRow(ctx, countSentOtpsToFactorToday, factor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSentOtp = `-- name: CreateSentOtp :one
INSERT INTO sent_otps (factor_type, factor, secret_value, max_attempts)
VALUES ($1, $2, $3, $4)
RETURNING request_id, factor, max_attempts, number_of_attempts, factor_type, secret_value, created_at, updated_at
`

type CreateSentOtpParams struct {
	FactorType  string `json:"factor_type"`
	Factor      string `json:"factor"`
	SecretValue string `json:"secret_value"`
	MaxAttempts int32  `json:"max_attempts"`
}

func (q *Queries) CreateSentOtp(ctx context.Context, arg CreateSentOtpParams) (SentOtp, error) {
	row := q.db.QueryRow(ctx, createSentOtp,
		arg.FactorType,
		arg.Factor,
		arg.SecretValue,
		arg.MaxAttempts,
	)
	var i SentOtp
	err := row.Scan(
		&i.RequestID,
		&i.Factor,
		&i.MaxAttempts,
		&i.NumberOfAttempts,
		&i.FactorType,
		&i.SecretValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSentOtpByFactor = `-- name: GetLatestSentOtpByFactor :many
SELECT request_id, factor, max_attempts, number_of_attempts, factor_type, secret_value, created_at, updated_at FROM sent_otps WHERE factor = $1 ORDER BY created_at DESC LIMIT $2
`

type GetLatestSentOtpByFactorParams struct {
	Factor string `json:"factor"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetLatestSentOtpByFactor(ctx context.Context, arg GetLatestSentOtpByFactorParams) ([]SentOtp, error) {
	rows, err := q.db.Query(ctx, getLatestSentOtpByFactor, arg.Factor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SentOtp{}
	for rows.Next() {
		var i SentOtp
		if err := rows.Scan(
			&i.RequestID,
			&i.Factor,
			&i.MaxAttempts,
			&i.NumberOfAttempts,
			&i.FactorType,
			&i.SecretValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentOtpByRequestId = `-- name: GetSentOtpByRequestId :one
SELECT request_id, factor, max_attempts, number_of_attempts, factor_type, secret_value, created_at, updated_at FROM sent_otps WHERE request_id = $1
`

func (q *Queries) GetSentOtpByRequestId(ctx context.Context, requestID string) (SentOtp, error) {
	row := q.db.QueryRow(ctx, getSentOtpByRequestId, requestID)
	var i SentOtp
	err := row.Scan(
		&i.RequestID,
		&i.Factor,
		&i.MaxAttempts,
		&i.NumberOfAttempts,
		&i.FactorType,
		&i.SecretValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSentOtp = `-- name: UpdateSentOtp :exec
UPDATE sent_otps
SET
    number_of_attempts = $1
WHERE
    request_id = $2
`

type UpdateSentOtpParams struct {
	NumberOfAttempts int32  `json:"number_of_attempts"`
	RequestID        string `json:"request_id"`
}

func (q *Queries) UpdateSentOtp(ctx context.Context, arg UpdateSentOtpParams) error {
	_, err := q.db.Exec(ctx, updateSentOtp, arg.NumberOfAttempts, arg.RequestID)
	return err
}
