// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_subscriptions.sql

package sqlc

import (
	"context"
	"time"
)

const activateUserSubscription = `-- name: ActivateUserSubscription :exec
UPDATE user_subscriptions
SET active = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) ActivateUserSubscription(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, activateUserSubscription, id)
	return err
}

const createUserSubscription = `-- name: CreateUserSubscription :one
INSERT INTO user_subscriptions (user_id, subscription_id, active, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, subscription_id, active, created_at, updated_at, expires_at
`

type CreateUserSubscriptionParams struct {
	UserID         string    `json:"user_id"`
	SubscriptionID string    `json:"subscription_id"`
	Active         bool      `json:"active"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, createUserSubscription,
		arg.UserID,
		arg.SubscriptionID,
		arg.Active,
		arg.ExpiresAt,
	)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteUserSubscription = `-- name: DeleteUserSubscription :exec
DELETE from user_subscriptions WHERE id = $1
`

func (q *Queries) DeleteUserSubscription(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserSubscription, id)
	return err
}

const getAllUserSubscriptions = `-- name: GetAllUserSubscriptions :many
SELECT id, user_id, subscription_id, active, created_at, updated_at, expires_at FROM user_subscriptions
`

func (q *Queries) GetAllUserSubscriptions(ctx context.Context) ([]UserSubscription, error) {
	rows, err := q.db.Query(ctx, getAllUserSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSubscription{}
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActiveSubscription = `-- name: GetUserActiveSubscription :one
SELECT id, user_id, subscription_id, active, created_at, updated_at, expires_at 
FROM user_subscriptions 
WHERE user_id = $1 
AND active = TRUE 
LIMIT 1
`

func (q *Queries) GetUserActiveSubscription(ctx context.Context, userID string) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, getUserActiveSubscription, userID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserSubscriptionByID = `-- name: GetUserSubscriptionByID :one
SELECT id, user_id, subscription_id, active, created_at, updated_at, expires_at FROM user_subscriptions WHERE id = $1
`

func (q *Queries) GetUserSubscriptionByID(ctx context.Context, id string) (UserSubscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionByID, id)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
