// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE created_at >= $1 AND created_at < $2
`

type CountUsersParams struct {
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_number, email, "password", first_name, last_name, residence_country_iso_code, "address", location_coordinates, profile_image, "role")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at
`

type CreateUserParams struct {
	PhoneNumber             string       `json:"phone_number"`
	Email                   *string      `json:"email"`
	Password                string       `json:"password"`
	FirstName               *string      `json:"first_name"`
	LastName                *string      `json:"last_name"`
	ResidenceCountryIsoCode string       `json:"residence_country_iso_code"`
	Address                 *string      `json:"address"`
	LocationCoordinates     pgtype.Point `json:"location_coordinates"`
	ProfileImage            string       `json:"profile_image"`
	Role                    string       `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PhoneNumber,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.ResidenceCountryIsoCode,
		arg.Address,
		arg.LocationCoordinates,
		arg.ProfileImage,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFarmer = `-- name: GetFarmer :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at FROM users WHERE id = $1 AND role = 'USER_ROLE_FARMER'
`

func (q *Queries) GetFarmer(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getFarmer, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByNationalNumber = `-- name: GetUserByNationalNumber :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at
FROM users
WHERE RIGHT(phone_number, CHAR_LENGTH($1::TEXT)) = $1::TEXT
  AND CHAR_LENGTH(phone_number) - CHAR_LENGTH($1::TEXT) BETWEEN 1 AND 5
`

func (q *Queries) GetUserByNationalNumber(ctx context.Context, nationalNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByNationalNumber, nationalNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at FROM users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFarmersByRating = `-- name: ListFarmersByRating :many
SELECT
    f.id,
    f.first_name,
    f.last_name,
    f.profile_image,
    f.created_at,
    COALESCE(fr.average_rating, 0) AS average_rating
FROM
    users f
LEFT JOIN (
    SELECT
        farmer_id,
        AVG(rating) AS average_rating
    FROM
        farmers_reviews
    GROUP BY
        farmer_id
) AS fr ON f.id = fr.farmer_id
WHERE
    (
        $1::float = 0.0
        OR COALESCE(fr.average_rating, 0) < $1::float
    )
    AND role = 'USER_ROLE_FARMER'
    AND (
        $2 = ''
        OR (
            LOWER(f.first_name) LIKE LOWER('%' || $2 || '%')
            OR LOWER(f.last_name) LIKE LOWER('%' || $2 || '%')
        )
    )
ORDER BY
    average_rating DESC,
    f.created_at ASC -- Oldest farmers take precedence if ratings are tied
LIMIT $3
`

type ListFarmersByRatingParams struct {
	CursorAverageRating float64     `json:"cursor_average_rating"`
	SearchKey           interface{} `json:"search_key"`
	Count               int32       `json:"count"`
}

type ListFarmersByRatingRow struct {
	ID            string             `json:"id"`
	FirstName     *string            `json:"first_name"`
	LastName      *string            `json:"last_name"`
	ProfileImage  string             `json:"profile_image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AverageRating float64            `json:"average_rating"`
}

func (q *Queries) ListFarmersByRating(ctx context.Context, arg ListFarmersByRatingParams) ([]ListFarmersByRatingRow, error) {
	rows, err := q.db.Query(ctx, listFarmersByRating, arg.CursorAverageRating, arg.SearchKey, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFarmersByRatingRow{}
	for rows.Next() {
		var i ListFarmersByRatingRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ProfileImage,
			&i.CreatedAt,
			&i.AverageRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    (first_name, last_name, email, "address", location_coordinates, profile_image, updated_at) =
    ($1,         $2,        $3,    $4,        $5,                   $6,            now())
WHERE
    id = $7
RETURNING
    id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at
`

type UpdateUserParams struct {
	FirstName           *string      `json:"first_name"`
	LastName            *string      `json:"last_name"`
	Email               *string      `json:"email"`
	Address             *string      `json:"address"`
	LocationCoordinates pgtype.Point `json:"location_coordinates"`
	ProfileImage        string       `json:"profile_image"`
	ID                  string       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Address,
		arg.LocationCoordinates,
		arg.ProfileImage,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec

UPDATE users SET password = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	ID       string `json:"id"`
}

// ensures a valid country code
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $1 WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
