// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE created_at >= $1 AND created_at < $2 AND delete_requested_at IS NULL AND deleted_at IS NULL
`

type CountUsersParams struct {
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKYC = `-- name: CreateKYC :one

INSERT INTO kyc_verifications (user_id, identity_document_urls, selfie_urls, vehicle_document_urls, status)
VALUES ($1, $2, $3, $4, 'KYC_STATUS_PENDING')
ON CONFLICT (user_id) DO UPDATE
SET identity_document_urls = EXCLUDED.identity_document_urls,
    selfie_urls = EXCLUDED.selfie_urls,
    vehicle_document_urls = EXCLUDED.vehicle_document_urls,
    status = 'KYC_STATUS_PENDING',
    updated_at = now()
RETURNING id, user_id, status, rejection_reason, verified_at, created_at, updated_at, identity_document_urls, selfie_urls, vehicle_document_urls
`

type CreateKYCParams struct {
	UserID               string   `json:"user_id"`
	IdentityDocumentUrls []string `json:"identity_document_urls"`
	SelfieUrls           []string `json:"selfie_urls"`
	VehicleDocumentUrls  []string `json:"vehicle_document_urls"`
}

// KYC Queries
func (q *Queries) CreateKYC(ctx context.Context, arg CreateKYCParams) (KycVerification, error) {
	row := q.db.QueryRow(ctx, createKYC,
		arg.UserID,
		arg.IdentityDocumentUrls,
		arg.SelfieUrls,
		arg.VehicleDocumentUrls,
	)
	var i KycVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityDocumentUrls,
		&i.SelfieUrls,
		&i.VehicleDocumentUrls,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_number, email, "password", first_name, last_name, residence_country_iso_code, "address", location_coordinates, profile_image, "role", user_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'UserStatus_ACTIVE')
RETURNING id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at
`

type CreateUserParams struct {
	PhoneNumber             string       `json:"phone_number"`
	Email                   *string      `json:"email"`
	Password                string       `json:"password"`
	FirstName               *string      `json:"first_name"`
	LastName                *string      `json:"last_name"`
	ResidenceCountryIsoCode string       `json:"residence_country_iso_code"`
	Address                 *string      `json:"address"`
	LocationCoordinates     pgtype.Point `json:"location_coordinates"`
	ProfileImage            string       `json:"profile_image"`
	Role                    string       `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PhoneNumber,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.ResidenceCountryIsoCode,
		arg.Address,
		arg.LocationCoordinates,
		arg.ProfileImage,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET delete_requested_at = NOW(),
    deleted_at = NOW() + INTERVAL '90 days'
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getFarmer = `-- name: GetFarmer :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at FROM users WHERE id = $1 AND role = 'USER_ROLE_FARMER'
`

func (q *Queries) GetFarmer(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getFarmer, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getKYCByID = `-- name: GetKYCByID :one
SELECT id, user_id, status, rejection_reason, verified_at, created_at, updated_at, identity_document_urls, selfie_urls, vehicle_document_urls FROM kyc_verifications WHERE id = $1
`

func (q *Queries) GetKYCByID(ctx context.Context, id string) (KycVerification, error) {
	row := q.db.QueryRow(ctx, getKYCByID, id)
	var i KycVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityDocumentUrls,
		&i.SelfieUrls,
		&i.VehicleDocumentUrls,
	)
	return i, err
}

const getKYCByUserID = `-- name: GetKYCByUserID :one
SELECT id, user_id, status, rejection_reason, verified_at, created_at, updated_at, identity_document_urls, selfie_urls, vehicle_document_urls FROM kyc_verifications WHERE user_id = $1
`

func (q *Queries) GetKYCByUserID(ctx context.Context, userID string) (KycVerification, error) {
	row := q.db.QueryRow(ctx, getKYCByUserID, userID)
	var i KycVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityDocumentUrls,
		&i.SelfieUrls,
		&i.VehicleDocumentUrls,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at FROM users WHERE email = $1 AND delete_requested_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByNationalNumber = `-- name: GetUserByNationalNumber :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at
FROM users
WHERE 
  phone_number = $1::TEXT
  OR
  (
    RIGHT(phone_number, CHAR_LENGTH($1::TEXT)) = $1::TEXT
    AND CHAR_LENGTH(phone_number) - CHAR_LENGTH($1::TEXT) BETWEEN 1 AND 5 -- ensures a valid country code
  )
`

func (q *Queries) GetUserByNationalNumber(ctx context.Context, nationalNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByNationalNumber, nationalNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at FROM users WHERE phone_number = $1 AND delete_requested_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one

SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at FROM users WHERE referral_code = $1
`

// -- name: DeleteUser :exec
// DELETE FROM users where id = $1;
func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByReferralCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at FROM users WHERE id = $1 AND delete_requested_at IS NULL AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserStatsBetweenDates = `-- name: GetUserStatsBetweenDates :one
SELECT
  COUNT(*) FILTER (WHERE role = 'USER_ROLE_USER') AS total_users,
  COUNT(*) FILTER (WHERE role = 'USER_ROLE_FARMER') AS total_farmers
FROM users
WHERE created_at >= $1::timestamptz
  AND created_at <= $2::timestamptz
`

type GetUserStatsBetweenDatesParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetUserStatsBetweenDatesRow struct {
	TotalUsers   int64 `json:"total_users"`
	TotalFarmers int64 `json:"total_farmers"`
}

func (q *Queries) GetUserStatsBetweenDates(ctx context.Context, arg GetUserStatsBetweenDatesParams) (GetUserStatsBetweenDatesRow, error) {
	row := q.db.QueryRow(ctx, getUserStatsBetweenDates, arg.StartDate, arg.EndDate)
	var i GetUserStatsBetweenDatesRow
	err := row.Scan(&i.TotalUsers, &i.TotalFarmers)
	return i, err
}

const listFarmersByRating = `-- name: ListFarmersByRating :many
SELECT
    f.id,
    f.first_name,
    f.last_name,
    f.profile_image,
    f.created_at,
    f.user_status,
    f.address,
    f.phone_number,
    f.email,
    COALESCE(fr.average_rating, 0) AS average_rating
FROM
    users f
LEFT JOIN (
    SELECT
        farmer_id,
        AVG(rating) AS average_rating
    FROM
        farmers_reviews
    GROUP BY
        farmer_id
) AS fr ON f.id = fr.farmer_id
WHERE
    ( $1::TEXT = 'UserStatus_UNSPECIFIED' OR (f.user_status = $1::TEXT) )
    AND role = 'USER_ROLE_FARMER'
    AND (
      (
        $2::float = 0
        AND COALESCE(fr.average_rating, 0) = 0
        AND (
          CASE WHEN $3 THEN
            f.created_at < $4::timestamptz
          ELSE
            f.created_at > $4::timestamptz
          END
        )
      )
      OR (
        $2::float != 0
        AND (
          COALESCE(fr.average_rating, 0) < $2::float
          OR (
            COALESCE(fr.average_rating, 0) = $2::float
            AND (
              CASE WHEN $3 THEN
                f.created_at < $4::timestamptz
              ELSE
                f.created_at > $4::timestamptz
              END
            )
          )
        )
      )
      OR $2::float > 5.0
    )
    AND (
    $5 = ''
    OR (
        LOWER(f.first_name) LIKE LOWER('%' || $5 || '%')
        OR LOWER(f.last_name) LIKE LOWER('%' || $5 || '%')
        OR LOWER(f.email) LIKE LOWER('%' || $5 || '%')
        OR (
            regexp_replace(phone_number, '[^0-9]', '', 'g')
            LIKE '%' || regexp_replace($5::text, '[^0-9]', '', 'g') || '%'
        )
    )
    )
    AND delete_requested_at IS NULL AND deleted_at IS NULL
ORDER BY
    COALESCE(fr.average_rating, 0) DESC,
    CASE WHEN $3 THEN f.created_at END DESC,
    CASE WHEN NOT $3 THEN f.created_at END ASC
LIMIT $6
`

type ListFarmersByRatingParams struct {
	UserStatus          string      `json:"user_status"`
	CursorAverageRating float64     `json:"cursor_average_rating"`
	SortCreatedAtDesc   interface{} `json:"sort_created_at_desc"`
	CursorCreatedAt     time.Time   `json:"cursor_created_at"`
	SearchKey           interface{} `json:"search_key"`
	Count               int32       `json:"count"`
}

type ListFarmersByRatingRow struct {
	ID            string             `json:"id"`
	FirstName     *string            `json:"first_name"`
	LastName      *string            `json:"last_name"`
	ProfileImage  string             `json:"profile_image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserStatus    string             `json:"user_status"`
	Address       *string            `json:"address"`
	PhoneNumber   string             `json:"phone_number"`
	Email         *string            `json:"email"`
	AverageRating float64            `json:"average_rating"`
}

func (q *Queries) ListFarmersByRating(ctx context.Context, arg ListFarmersByRatingParams) ([]ListFarmersByRatingRow, error) {
	rows, err := q.db.Query(ctx, listFarmersByRating,
		arg.UserStatus,
		arg.CursorAverageRating,
		arg.SortCreatedAtDesc,
		arg.CursorCreatedAt,
		arg.SearchKey,
		arg.Count,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFarmersByRatingRow{}
	for rows.Next() {
		var i ListFarmersByRatingRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ProfileImage,
			&i.CreatedAt,
			&i.UserStatus,
			&i.Address,
			&i.PhoneNumber,
			&i.Email,
			&i.AverageRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKYCVerifications = `-- name: ListKYCVerifications :many
SELECT id, user_id, status, rejection_reason, verified_at, created_at, updated_at, identity_document_urls, selfie_urls, vehicle_document_urls FROM kyc_verifications 
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListKYCVerificationsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListKYCVerifications(ctx context.Context, arg ListKYCVerificationsParams) ([]KycVerification, error) {
	rows, err := q.db.Query(ctx, listKYCVerifications, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycVerification{}
	for rows.Next() {
		var i KycVerification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.RejectionReason,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityDocumentUrls,
			&i.SelfieUrls,
			&i.VehicleDocumentUrls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at
FROM users 
WHERE
    ( $2::TEXT = 'UserStatus_UNSPECIFIED' OR (user_status = $2::TEXT) )
    AND role = $3::TEXT
   AND (
        $4 = ''
        OR (
            LOWER(first_name) LIKE LOWER('%' || $4 || '%')
            OR LOWER(last_name) LIKE LOWER('%' || $4 || '%')
            OR LOWER(email) LIKE LOWER('%' || $4 || '%')
            OR (
                    regexp_replace(phone_number, '[^0-9]', '', 'g')
                    LIKE '%' || regexp_replace($4::text, '[^0-9]', '', 'g') || '%'
                )
        )
    )
    AND created_at < $5::timestamptz
    AND delete_requested_at IS NULL AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
`

type ListUsersParams struct {
	Limit      int32       `json:"limit"`
	UserStatus string      `json:"user_status"`
	UserRole   string      `json:"user_role"`
	SearchKey  interface{} `json:"search_key"`
	Before     time.Time   `json:"before"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.UserStatus,
		arg.UserRole,
		arg.SearchKey,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.PhoneNumber,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ResidenceCountryIsoCode,
			&i.Address,
			&i.LocationCoordinates,
			&i.ProfileImage,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserStatus,
			&i.ReferralCode,
			&i.DeleteRequestedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users
SET user_status = 'UserStatus_ACTIVE'
WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const suspendUser = `-- name: SuspendUser :exec
UPDATE users
SET user_status = 'UserStatus_SUSPENDED'
WHERE id = $1
`

func (q *Queries) SuspendUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, suspendUser, id)
	return err
}

const updateKYCStatus = `-- name: UpdateKYCStatus :one
UPDATE kyc_verifications
SET status = $1::text,
    rejection_reason = $2::text,
    verified_at = CASE
        WHEN $1::text = 'KYC_STATUS_VERIFIED' THEN now()
        ELSE NULL::timestamptz
    END,
    updated_at = now()
WHERE id = $3::text
RETURNING id, user_id, status, rejection_reason, verified_at, created_at, updated_at, identity_document_urls, selfie_urls, vehicle_document_urls
`

type UpdateKYCStatusParams struct {
	Status          string `json:"status"`
	RejectionReason string `json:"rejection_reason"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateKYCStatus(ctx context.Context, arg UpdateKYCStatusParams) (KycVerification, error) {
	row := q.db.QueryRow(ctx, updateKYCStatus, arg.Status, arg.RejectionReason, arg.ID)
	var i KycVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityDocumentUrls,
		&i.SelfieUrls,
		&i.VehicleDocumentUrls,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    (first_name, last_name, email, "address", location_coordinates, profile_image, phone_number, updated_at) =
    ($1,         $2,        $3,    $4,        $5,                   $6,            $7,           now())
WHERE
    id = $8
AND delete_requested_at IS NULL AND deleted_at IS NULL
RETURNING
    id, role, phone_number, email, first_name, last_name, residence_country_iso_code, address, location_coordinates, profile_image, password, created_at, updated_at, user_status, referral_code, delete_requested_at, deleted_at
`

type UpdateUserParams struct {
	FirstName           *string      `json:"first_name"`
	LastName            *string      `json:"last_name"`
	Email               *string      `json:"email"`
	Address             *string      `json:"address"`
	LocationCoordinates pgtype.Point `json:"location_coordinates"`
	ProfileImage        string       `json:"profile_image"`
	PhoneNumber         string       `json:"phone_number"`
	ID                  string       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Address,
		arg.LocationCoordinates,
		arg.ProfileImage,
		arg.PhoneNumber,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PhoneNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ResidenceCountryIsoCode,
		&i.Address,
		&i.LocationCoordinates,
		&i.ProfileImage,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.ReferralCode,
		&i.DeleteRequestedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $1 WHERE id = $2 AND delete_requested_at IS NULL AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $1 WHERE id = $2 AND delete_requested_at IS NULL AND deleted_at IS NULL
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
