- envId: dev
  name: Development
  gitRefName: release/updated-prod
  awsAccountId: 694364706342
  domainName: foodhousetesting.xyz
  
- envId: testing
  name: Testing
  gitRefName: main
  awsAccountId: 844670296881
  domainName: dev.foodhousetesting.xyz

