- envId: dev
  name: Development
  gitRefName: release/testing/v1.1.0
  awsAccountId: 694364706342
  domainName: foodhousetesting.xyz
  
- envId: testing
  name: Testing
  gitRefName: main
  awsAccountId: 844670296881
  domainName: dev.foodhousetesting.xyz

