// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from '@hey-api/client-axios';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { UsersCreateSubscriptionData, UsersCreateSubscriptionError, UsersCreateSubscriptionResponse, UsersDeleteSubscriptionData, UsersDeleteSubscriptionError, UsersDeleteSubscriptionResponse, UsersUpdateSubscriptionData, UsersUpdateSubscriptionError, UsersUpdateSubscriptionResponse, UsersGrantAdminData, UsersGrantAdminError, UsersGrantAdminResponse, UsersListUsersData, UsersRevokeRefreshTokenData, UsersRevokeRefreshTokenError, UsersRevokeRefreshTokenResponse, UsersAuthenticateData, UsersAuthenticateError, UsersAuthenticateResponse, UsersChangePasswordData, UsersChangePasswordError, UsersChangePasswordResponse, UsersLastOtpForFactorData, UsersRefreshAccessTokenData, UsersRefreshAccessTokenError, UsersRefreshAccessTokenResponse, UsersSendEmailOtpData, UsersSendEmailOtpError, UsersSendEmailOtpResponse, UsersSendSignupSmsOtpData, UsersSendSignupSmsOtpError, UsersSendSignupSmsOtpResponse, UsersSendSmsOtpData, UsersSendSmsOtpError, UsersSendSmsOtpResponse, UsersSignupData, UsersSignupError, UsersSignupResponse, UsersVerifyOtpData, UsersVerifyOtpError, UsersVerifyOtpResponse, UsersCompleteRegistrationData, UsersCompleteRegistrationError, UsersCompleteRegistrationResponse, UsersDeleteUserPaymentMethodData, UsersDeleteUserPaymentMethodError, UsersDeleteUserPaymentMethodResponse, UsersGetUserByIdData, UsersSubscribeData, UsersSubscribeError, UsersSubscribeResponse, UsersGetUserActiveSubscriptionData, UsersGetUserSubscriptionsData, UsersGetUserSubscriptionByIdData, UsersGetUserPaymentMethodsByUserIdData, UsersGetFarmerByIdData } from '../types.gen';
import type { AxiosError } from 'axios';
import { client, usersCreateSubscription, usersDeleteSubscription, usersUpdateSubscription, usersGrantAdmin, usersListUsers, usersRevokeRefreshToken, usersAuthenticate, usersChangePassword, usersHealthCheck, usersLastOtpForFactor, usersRefreshAccessToken, usersSendEmailOtp, usersSendSignupSmsOtp, usersSendSmsOtp, usersSignup, usersVerifyOtp, usersCompleteRegistration, usersDeleteUserPaymentMethod, usersGetUserById, usersSubscribe, usersGetUserActiveSubscription, usersGetUserSubscriptions, usersGetUserSubscriptionById, usersGetUserPaymentMethodsByUserId, usersGetFarmerById } from '../sdk.gen';

type QueryKey<TOptions extends OptionsLegacyParser> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};

export const usersCreateSubscriptionQueryKey = (options: OptionsLegacyParser<UsersCreateSubscriptionData>) => [
    createQueryKey('usersCreateSubscription', options)
];

export const usersCreateSubscriptionOptions = (options: OptionsLegacyParser<UsersCreateSubscriptionData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersCreateSubscription({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersCreateSubscriptionQueryKey(options)
    });
};

export const usersCreateSubscriptionMutation = (options?: Partial<OptionsLegacyParser<UsersCreateSubscriptionData>>) => {
    const mutationOptions: UseMutationOptions<UsersCreateSubscriptionResponse, AxiosError<UsersCreateSubscriptionError>, OptionsLegacyParser<UsersCreateSubscriptionData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersCreateSubscription({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersDeleteSubscriptionMutation = (options?: Partial<OptionsLegacyParser<UsersDeleteSubscriptionData>>) => {
    const mutationOptions: UseMutationOptions<UsersDeleteSubscriptionResponse, AxiosError<UsersDeleteSubscriptionError>, OptionsLegacyParser<UsersDeleteSubscriptionData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersDeleteSubscription({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersUpdateSubscriptionMutation = (options?: Partial<OptionsLegacyParser<UsersUpdateSubscriptionData>>) => {
    const mutationOptions: UseMutationOptions<UsersUpdateSubscriptionResponse, AxiosError<UsersUpdateSubscriptionError>, OptionsLegacyParser<UsersUpdateSubscriptionData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersUpdateSubscription({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersGrantAdminQueryKey = (options: OptionsLegacyParser<UsersGrantAdminData>) => [
    createQueryKey('usersGrantAdmin', options)
];

export const usersGrantAdminOptions = (options: OptionsLegacyParser<UsersGrantAdminData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersGrantAdmin({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersGrantAdminQueryKey(options)
    });
};

export const usersGrantAdminMutation = (options?: Partial<OptionsLegacyParser<UsersGrantAdminData>>) => {
    const mutationOptions: UseMutationOptions<UsersGrantAdminResponse, AxiosError<UsersGrantAdminError>, OptionsLegacyParser<UsersGrantAdminData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersGrantAdmin({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersListUsersQueryKey = (options: OptionsLegacyParser<UsersListUsersData>) => [
    createQueryKey('usersListUsers', options)
];

export const usersListUsersOptions = (options: OptionsLegacyParser<UsersListUsersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersListUsers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersListUsersQueryKey(options)
    });
};

export const usersRevokeRefreshTokenQueryKey = (options: OptionsLegacyParser<UsersRevokeRefreshTokenData>) => [
    createQueryKey('usersRevokeRefreshToken', options)
];

export const usersRevokeRefreshTokenOptions = (options: OptionsLegacyParser<UsersRevokeRefreshTokenData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersRevokeRefreshToken({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersRevokeRefreshTokenQueryKey(options)
    });
};

export const usersRevokeRefreshTokenMutation = (options?: Partial<OptionsLegacyParser<UsersRevokeRefreshTokenData>>) => {
    const mutationOptions: UseMutationOptions<UsersRevokeRefreshTokenResponse, AxiosError<UsersRevokeRefreshTokenError>, OptionsLegacyParser<UsersRevokeRefreshTokenData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersRevokeRefreshToken({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersAuthenticateQueryKey = (options: OptionsLegacyParser<UsersAuthenticateData>) => [
    createQueryKey('usersAuthenticate', options)
];

export const usersAuthenticateOptions = (options: OptionsLegacyParser<UsersAuthenticateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersAuthenticate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersAuthenticateQueryKey(options)
    });
};

export const usersAuthenticateMutation = (options?: Partial<OptionsLegacyParser<UsersAuthenticateData>>) => {
    const mutationOptions: UseMutationOptions<UsersAuthenticateResponse, AxiosError<UsersAuthenticateError>, OptionsLegacyParser<UsersAuthenticateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersAuthenticate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersChangePasswordQueryKey = (options: OptionsLegacyParser<UsersChangePasswordData>) => [
    createQueryKey('usersChangePassword', options)
];

export const usersChangePasswordOptions = (options: OptionsLegacyParser<UsersChangePasswordData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersChangePassword({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersChangePasswordQueryKey(options)
    });
};

export const usersChangePasswordMutation = (options?: Partial<OptionsLegacyParser<UsersChangePasswordData>>) => {
    const mutationOptions: UseMutationOptions<UsersChangePasswordResponse, AxiosError<UsersChangePasswordError>, OptionsLegacyParser<UsersChangePasswordData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersChangePassword({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersHealthCheckQueryKey = (options?: OptionsLegacyParser) => [
    createQueryKey('usersHealthCheck', options)
];

export const usersHealthCheckOptions = (options?: OptionsLegacyParser) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersHealthCheck({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersHealthCheckQueryKey(options)
    });
};

export const usersLastOtpForFactorQueryKey = (options?: OptionsLegacyParser<UsersLastOtpForFactorData>) => [
    createQueryKey('usersLastOtpForFactor', options)
];

export const usersLastOtpForFactorOptions = (options?: OptionsLegacyParser<UsersLastOtpForFactorData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersLastOtpForFactor({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersLastOtpForFactorQueryKey(options)
    });
};

export const usersRefreshAccessTokenQueryKey = (options: OptionsLegacyParser<UsersRefreshAccessTokenData>) => [
    createQueryKey('usersRefreshAccessToken', options)
];

export const usersRefreshAccessTokenOptions = (options: OptionsLegacyParser<UsersRefreshAccessTokenData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersRefreshAccessToken({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersRefreshAccessTokenQueryKey(options)
    });
};

export const usersRefreshAccessTokenMutation = (options?: Partial<OptionsLegacyParser<UsersRefreshAccessTokenData>>) => {
    const mutationOptions: UseMutationOptions<UsersRefreshAccessTokenResponse, AxiosError<UsersRefreshAccessTokenError>, OptionsLegacyParser<UsersRefreshAccessTokenData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersRefreshAccessToken({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersSendEmailOtpQueryKey = (options: OptionsLegacyParser<UsersSendEmailOtpData>) => [
    createQueryKey('usersSendEmailOtp', options)
];

export const usersSendEmailOtpOptions = (options: OptionsLegacyParser<UsersSendEmailOtpData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersSendEmailOtp({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersSendEmailOtpQueryKey(options)
    });
};

export const usersSendEmailOtpMutation = (options?: Partial<OptionsLegacyParser<UsersSendEmailOtpData>>) => {
    const mutationOptions: UseMutationOptions<UsersSendEmailOtpResponse, AxiosError<UsersSendEmailOtpError>, OptionsLegacyParser<UsersSendEmailOtpData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersSendEmailOtp({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersSendSignupSmsOtpQueryKey = (options: OptionsLegacyParser<UsersSendSignupSmsOtpData>) => [
    createQueryKey('usersSendSignupSmsOtp', options)
];

export const usersSendSignupSmsOtpOptions = (options: OptionsLegacyParser<UsersSendSignupSmsOtpData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersSendSignupSmsOtp({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersSendSignupSmsOtpQueryKey(options)
    });
};

export const usersSendSignupSmsOtpMutation = (options?: Partial<OptionsLegacyParser<UsersSendSignupSmsOtpData>>) => {
    const mutationOptions: UseMutationOptions<UsersSendSignupSmsOtpResponse, AxiosError<UsersSendSignupSmsOtpError>, OptionsLegacyParser<UsersSendSignupSmsOtpData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersSendSignupSmsOtp({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersSendSmsOtpQueryKey = (options: OptionsLegacyParser<UsersSendSmsOtpData>) => [
    createQueryKey('usersSendSmsOtp', options)
];

export const usersSendSmsOtpOptions = (options: OptionsLegacyParser<UsersSendSmsOtpData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersSendSmsOtp({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersSendSmsOtpQueryKey(options)
    });
};

export const usersSendSmsOtpMutation = (options?: Partial<OptionsLegacyParser<UsersSendSmsOtpData>>) => {
    const mutationOptions: UseMutationOptions<UsersSendSmsOtpResponse, AxiosError<UsersSendSmsOtpError>, OptionsLegacyParser<UsersSendSmsOtpData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersSendSmsOtp({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersSignupQueryKey = (options: OptionsLegacyParser<UsersSignupData>) => [
    createQueryKey('usersSignup', options)
];

export const usersSignupOptions = (options: OptionsLegacyParser<UsersSignupData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersSignup({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersSignupQueryKey(options)
    });
};

export const usersSignupMutation = (options?: Partial<OptionsLegacyParser<UsersSignupData>>) => {
    const mutationOptions: UseMutationOptions<UsersSignupResponse, AxiosError<UsersSignupError>, OptionsLegacyParser<UsersSignupData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersSignup({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersVerifyOtpQueryKey = (options: OptionsLegacyParser<UsersVerifyOtpData>) => [
    createQueryKey('usersVerifyOtp', options)
];

export const usersVerifyOtpOptions = (options: OptionsLegacyParser<UsersVerifyOtpData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersVerifyOtp({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersVerifyOtpQueryKey(options)
    });
};

export const usersVerifyOtpMutation = (options?: Partial<OptionsLegacyParser<UsersVerifyOtpData>>) => {
    const mutationOptions: UseMutationOptions<UsersVerifyOtpResponse, AxiosError<UsersVerifyOtpError>, OptionsLegacyParser<UsersVerifyOtpData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersVerifyOtp({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersCompleteRegistrationQueryKey = (options: OptionsLegacyParser<UsersCompleteRegistrationData>) => [
    createQueryKey('usersCompleteRegistration', options)
];

export const usersCompleteRegistrationOptions = (options: OptionsLegacyParser<UsersCompleteRegistrationData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersCompleteRegistration({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersCompleteRegistrationQueryKey(options)
    });
};

export const usersCompleteRegistrationMutation = (options?: Partial<OptionsLegacyParser<UsersCompleteRegistrationData>>) => {
    const mutationOptions: UseMutationOptions<UsersCompleteRegistrationResponse, AxiosError<UsersCompleteRegistrationError>, OptionsLegacyParser<UsersCompleteRegistrationData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersCompleteRegistration({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersDeleteUserPaymentMethodMutation = (options?: Partial<OptionsLegacyParser<UsersDeleteUserPaymentMethodData>>) => {
    const mutationOptions: UseMutationOptions<UsersDeleteUserPaymentMethodResponse, AxiosError<UsersDeleteUserPaymentMethodError>, OptionsLegacyParser<UsersDeleteUserPaymentMethodData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersDeleteUserPaymentMethod({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersGetUserByIdQueryKey = (options: OptionsLegacyParser<UsersGetUserByIdData>) => [
    createQueryKey('usersGetUserById', options)
];

export const usersGetUserByIdOptions = (options: OptionsLegacyParser<UsersGetUserByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersGetUserById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersGetUserByIdQueryKey(options)
    });
};

export const usersSubscribeQueryKey = (options: OptionsLegacyParser<UsersSubscribeData>) => [
    createQueryKey('usersSubscribe', options)
];

export const usersSubscribeOptions = (options: OptionsLegacyParser<UsersSubscribeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersSubscribe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersSubscribeQueryKey(options)
    });
};

export const usersSubscribeMutation = (options?: Partial<OptionsLegacyParser<UsersSubscribeData>>) => {
    const mutationOptions: UseMutationOptions<UsersSubscribeResponse, AxiosError<UsersSubscribeError>, OptionsLegacyParser<UsersSubscribeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersSubscribe({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersGetUserActiveSubscriptionQueryKey = (options: OptionsLegacyParser<UsersGetUserActiveSubscriptionData>) => [
    createQueryKey('usersGetUserActiveSubscription', options)
];

export const usersGetUserActiveSubscriptionOptions = (options: OptionsLegacyParser<UsersGetUserActiveSubscriptionData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersGetUserActiveSubscription({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersGetUserActiveSubscriptionQueryKey(options)
    });
};

export const usersGetUserSubscriptionsQueryKey = (options: OptionsLegacyParser<UsersGetUserSubscriptionsData>) => [
    createQueryKey('usersGetUserSubscriptions', options)
];

export const usersGetUserSubscriptionsOptions = (options: OptionsLegacyParser<UsersGetUserSubscriptionsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersGetUserSubscriptions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersGetUserSubscriptionsQueryKey(options)
    });
};

export const usersGetUserSubscriptionByIdQueryKey = (options: OptionsLegacyParser<UsersGetUserSubscriptionByIdData>) => [
    createQueryKey('usersGetUserSubscriptionById', options)
];

export const usersGetUserSubscriptionByIdOptions = (options: OptionsLegacyParser<UsersGetUserSubscriptionByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersGetUserSubscriptionById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersGetUserSubscriptionByIdQueryKey(options)
    });
};

export const usersGetUserPaymentMethodsByUserIdQueryKey = (options: OptionsLegacyParser<UsersGetUserPaymentMethodsByUserIdData>) => [
    createQueryKey('usersGetUserPaymentMethodsByUserId', options)
];

export const usersGetUserPaymentMethodsByUserIdOptions = (options: OptionsLegacyParser<UsersGetUserPaymentMethodsByUserIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersGetUserPaymentMethodsByUserId({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersGetUserPaymentMethodsByUserIdQueryKey(options)
    });
};

export const usersGetFarmerByIdQueryKey = (options: OptionsLegacyParser<UsersGetFarmerByIdData>) => [
    createQueryKey('usersGetFarmerById', options)
];

export const usersGetFarmerByIdOptions = (options: OptionsLegacyParser<UsersGetFarmerByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersGetFarmerById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersGetFarmerByIdQueryKey(options)
    });
};