// This file is auto-generated by @hey-api/openapi-ts

import type { OptionsLegacyParser } from '@hey-api/client-axios';
import {
  queryOptions,
  infiniteQueryOptions,
  type InfiniteData,
  type UseMutationOptions,
} from '@tanstack/react-query';
import type {
  UsersListKycVerificationsData,
  UsersListKycVerificationsError,
  UsersListKycVerificationsResponse,
  UsersExportUsersPdfData,
  UsersGrantAdminData,
  UsersGrantAdminError,
  UsersGrantAdminResponse,
  UsersGrantAgentData,
  UsersGrantAgentError,
  UsersGrantAgentResponse,
  UsersListUsersData,
  UsersDeleteAgentData,
  UsersDeleteAgentError,
  UsersDeleteAgentResponse,
  UsersReactivateUserData,
  UsersReactivateUserError,
  UsersReactivateUserResponse,
  UsersSuspendUserData,
  UsersSuspendUserError,
  UsersSuspendUserResponse,
  UsersUpdateKycStatusData,
  UsersUpdateKycStatusError,
  UsersUpdateKycStatusResponse,
  UsersOAuthData,
  UsersOAuthError,
  UsersOAuthResponse,
  UsersRevokeRefreshTokenData,
  UsersRevokeRefreshTokenError,
  UsersRevokeRefreshTokenResponse,
  UsersAuthenticateData,
  UsersAuthenticateError,
  UsersAuthenticateResponse,
  UsersChangePasswordData,
  UsersChangePasswordError,
  UsersChangePasswordResponse,
  UsersLastOtpForFactorData,
  UsersRefreshAccessTokenData,
  UsersRefreshAccessTokenError,
  UsersRefreshAccessTokenResponse,
  UsersSendEmailOtpData,
  UsersSendEmailOtpError,
  UsersSendEmailOtpResponse,
  UsersSendSignupSmsOtpData,
  UsersSendSignupSmsOtpError,
  UsersSendSignupSmsOtpResponse,
  UsersSendSmsOtpData,
  UsersSendSmsOtpError,
  UsersSendSmsOtpResponse,
  UsersSignupData,
  UsersSignupError,
  UsersSignupResponse,
  UsersVerifyOtpData,
  UsersVerifyOtpError,
  UsersVerifyOtpResponse,
  UsersGetPublicUserData,
  UsersCompleteRegistrationData,
  UsersCompleteRegistrationError,
  UsersCompleteRegistrationResponse,
  UsersDeleteUserAccountData,
  UsersListFarmersData,
  UsersListFarmersReivewsData,
  UsersGetKycByUserIdData,
  UsersGetUserByIdData,
  UsersReviewFarmerData,
  UsersReviewFarmerError,
  UsersReviewFarmerResponse,
  UsersCreateKycData,
  UsersCreateKycError,
  UsersCreateKycResponse,
  UsersGetFarmerByIdData,
} from '../types.gen';
import type { AxiosError } from 'axios';
import {
  client,
  usersListKycVerifications,
  usersExportUsersPdf,
  usersGrantAdmin,
  usersGrantAgent,
  usersListUsers,
  usersDeleteAgent,
  usersReactivateUser,
  usersSuspendUser,
  usersUpdateKycStatus,
  usersOAuth,
  usersRevokeRefreshToken,
  usersAuthenticate,
  usersChangePassword,
  usersHealthCheck,
  usersLastOtpForFactor,
  usersRefreshAccessToken,
  usersSendEmailOtp,
  usersSendSignupSmsOtp,
  usersSendSmsOtp,
  usersSignup,
  usersVerifyOtp,
  usersGetPublicUser,
  usersCompleteRegistration,
  usersDeleteUserAccount,
  usersListFarmers,
  usersListFarmersReivews,
  usersGetKycByUserId,
  usersGetUserById,
  usersReviewFarmer,
  usersCreateKyc,
  usersGetFarmerById,
} from '../sdk.gen';

type QueryKey<TOptions extends OptionsLegacyParser> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends OptionsLegacyParser>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const usersListKycVerificationsQueryKey = (
  options: OptionsLegacyParser<UsersListKycVerificationsData>,
) => [createQueryKey('usersListKycVerifications', options)];

export const usersListKycVerificationsOptions = (
  options: OptionsLegacyParser<UsersListKycVerificationsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersListKycVerifications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersListKycVerificationsQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<
    QueryKey<OptionsLegacyParser>[0],
    'body' | 'headers' | 'path' | 'query'
  >,
>(
  queryKey: QueryKey<OptionsLegacyParser>,
  page: K,
) => {
  const params = queryKey[0];
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path,
      ...page.path,
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query,
      ...page.query,
    };
  }
  return params as unknown as typeof page;
};

export const usersListKycVerificationsInfiniteQueryKey = (
  options: OptionsLegacyParser<UsersListKycVerificationsData>,
): QueryKey<OptionsLegacyParser<UsersListKycVerificationsData>> => [
  createQueryKey('usersListKycVerifications', options, true),
];

export const usersListKycVerificationsInfiniteOptions = (
  options: OptionsLegacyParser<UsersListKycVerificationsData>,
) => {
  return infiniteQueryOptions<
    UsersListKycVerificationsResponse,
    AxiosError<UsersListKycVerificationsError>,
    InfiniteData<UsersListKycVerificationsResponse>,
    QueryKey<OptionsLegacyParser<UsersListKycVerificationsData>>,
    | number
    | Pick<
        QueryKey<OptionsLegacyParser<UsersListKycVerificationsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<OptionsLegacyParser<UsersListKycVerificationsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await usersListKycVerifications({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: usersListKycVerificationsInfiniteQueryKey(options),
    },
  );
};

export const usersExportUsersPdfQueryKey = (
  options: OptionsLegacyParser<UsersExportUsersPdfData>,
) => [createQueryKey('usersExportUsersPdf', options)];

export const usersExportUsersPdfOptions = (
  options: OptionsLegacyParser<UsersExportUsersPdfData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersExportUsersPdf({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersExportUsersPdfQueryKey(options),
  });
};

export const usersGrantAdminQueryKey = (
  options: OptionsLegacyParser<UsersGrantAdminData>,
) => [createQueryKey('usersGrantAdmin', options)];

export const usersGrantAdminOptions = (
  options: OptionsLegacyParser<UsersGrantAdminData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersGrantAdmin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGrantAdminQueryKey(options),
  });
};

export const usersGrantAdminMutation = (
  options?: Partial<OptionsLegacyParser<UsersGrantAdminData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersGrantAdminResponse,
    AxiosError<UsersGrantAdminError>,
    OptionsLegacyParser<UsersGrantAdminData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersGrantAdmin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersGrantAgentQueryKey = (
  options: OptionsLegacyParser<UsersGrantAgentData>,
) => [createQueryKey('usersGrantAgent', options)];

export const usersGrantAgentOptions = (
  options: OptionsLegacyParser<UsersGrantAgentData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersGrantAgent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGrantAgentQueryKey(options),
  });
};

export const usersGrantAgentMutation = (
  options?: Partial<OptionsLegacyParser<UsersGrantAgentData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersGrantAgentResponse,
    AxiosError<UsersGrantAgentError>,
    OptionsLegacyParser<UsersGrantAgentData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersGrantAgent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersListUsersQueryKey = (
  options: OptionsLegacyParser<UsersListUsersData>,
) => [createQueryKey('usersListUsers', options)];

export const usersListUsersOptions = (
  options: OptionsLegacyParser<UsersListUsersData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersListUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersListUsersQueryKey(options),
  });
};

export const usersDeleteAgentMutation = (
  options?: Partial<OptionsLegacyParser<UsersDeleteAgentData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersDeleteAgentResponse,
    AxiosError<UsersDeleteAgentError>,
    OptionsLegacyParser<UsersDeleteAgentData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersDeleteAgent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersReactivateUserMutation = (
  options?: Partial<OptionsLegacyParser<UsersReactivateUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersReactivateUserResponse,
    AxiosError<UsersReactivateUserError>,
    OptionsLegacyParser<UsersReactivateUserData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersReactivateUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersSuspendUserMutation = (
  options?: Partial<OptionsLegacyParser<UsersSuspendUserData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersSuspendUserResponse,
    AxiosError<UsersSuspendUserError>,
    OptionsLegacyParser<UsersSuspendUserData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersSuspendUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersUpdateKycStatusMutation = (
  options?: Partial<OptionsLegacyParser<UsersUpdateKycStatusData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersUpdateKycStatusResponse,
    AxiosError<UsersUpdateKycStatusError>,
    OptionsLegacyParser<UsersUpdateKycStatusData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersUpdateKycStatus({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersOAuthQueryKey = (
  options: OptionsLegacyParser<UsersOAuthData>,
) => [createQueryKey('usersOAuth', options)];

export const usersOAuthOptions = (
  options: OptionsLegacyParser<UsersOAuthData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersOAuth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersOAuthQueryKey(options),
  });
};

export const usersOAuthMutation = (
  options?: Partial<OptionsLegacyParser<UsersOAuthData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersOAuthResponse,
    AxiosError<UsersOAuthError>,
    OptionsLegacyParser<UsersOAuthData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersOAuth({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersRevokeRefreshTokenQueryKey = (
  options: OptionsLegacyParser<UsersRevokeRefreshTokenData>,
) => [createQueryKey('usersRevokeRefreshToken', options)];

export const usersRevokeRefreshTokenOptions = (
  options: OptionsLegacyParser<UsersRevokeRefreshTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersRevokeRefreshToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersRevokeRefreshTokenQueryKey(options),
  });
};

export const usersRevokeRefreshTokenMutation = (
  options?: Partial<OptionsLegacyParser<UsersRevokeRefreshTokenData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersRevokeRefreshTokenResponse,
    AxiosError<UsersRevokeRefreshTokenError>,
    OptionsLegacyParser<UsersRevokeRefreshTokenData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersRevokeRefreshToken({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersAuthenticateQueryKey = (
  options: OptionsLegacyParser<UsersAuthenticateData>,
) => [createQueryKey('usersAuthenticate', options)];

export const usersAuthenticateOptions = (
  options: OptionsLegacyParser<UsersAuthenticateData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersAuthenticate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersAuthenticateQueryKey(options),
  });
};

export const usersAuthenticateMutation = (
  options?: Partial<OptionsLegacyParser<UsersAuthenticateData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersAuthenticateResponse,
    AxiosError<UsersAuthenticateError>,
    OptionsLegacyParser<UsersAuthenticateData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersAuthenticate({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersChangePasswordQueryKey = (
  options: OptionsLegacyParser<UsersChangePasswordData>,
) => [createQueryKey('usersChangePassword', options)];

export const usersChangePasswordOptions = (
  options: OptionsLegacyParser<UsersChangePasswordData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersChangePassword({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersChangePasswordQueryKey(options),
  });
};

export const usersChangePasswordMutation = (
  options?: Partial<OptionsLegacyParser<UsersChangePasswordData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersChangePasswordResponse,
    AxiosError<UsersChangePasswordError>,
    OptionsLegacyParser<UsersChangePasswordData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersChangePassword({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersHealthCheckQueryKey = (options?: OptionsLegacyParser) => [
  createQueryKey('usersHealthCheck', options),
];

export const usersHealthCheckOptions = (options?: OptionsLegacyParser) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersHealthCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersHealthCheckQueryKey(options),
  });
};

export const usersLastOtpForFactorQueryKey = (
  options?: OptionsLegacyParser<UsersLastOtpForFactorData>,
) => [createQueryKey('usersLastOtpForFactor', options)];

export const usersLastOtpForFactorOptions = (
  options?: OptionsLegacyParser<UsersLastOtpForFactorData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersLastOtpForFactor({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersLastOtpForFactorQueryKey(options),
  });
};

export const usersRefreshAccessTokenQueryKey = (
  options: OptionsLegacyParser<UsersRefreshAccessTokenData>,
) => [createQueryKey('usersRefreshAccessToken', options)];

export const usersRefreshAccessTokenOptions = (
  options: OptionsLegacyParser<UsersRefreshAccessTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersRefreshAccessToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersRefreshAccessTokenQueryKey(options),
  });
};

export const usersRefreshAccessTokenMutation = (
  options?: Partial<OptionsLegacyParser<UsersRefreshAccessTokenData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersRefreshAccessTokenResponse,
    AxiosError<UsersRefreshAccessTokenError>,
    OptionsLegacyParser<UsersRefreshAccessTokenData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersRefreshAccessToken({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersSendEmailOtpQueryKey = (
  options: OptionsLegacyParser<UsersSendEmailOtpData>,
) => [createQueryKey('usersSendEmailOtp', options)];

export const usersSendEmailOtpOptions = (
  options: OptionsLegacyParser<UsersSendEmailOtpData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersSendEmailOtp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersSendEmailOtpQueryKey(options),
  });
};

export const usersSendEmailOtpMutation = (
  options?: Partial<OptionsLegacyParser<UsersSendEmailOtpData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersSendEmailOtpResponse,
    AxiosError<UsersSendEmailOtpError>,
    OptionsLegacyParser<UsersSendEmailOtpData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersSendEmailOtp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersSendSignupSmsOtpQueryKey = (
  options: OptionsLegacyParser<UsersSendSignupSmsOtpData>,
) => [createQueryKey('usersSendSignupSmsOtp', options)];

export const usersSendSignupSmsOtpOptions = (
  options: OptionsLegacyParser<UsersSendSignupSmsOtpData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersSendSignupSmsOtp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersSendSignupSmsOtpQueryKey(options),
  });
};

export const usersSendSignupSmsOtpMutation = (
  options?: Partial<OptionsLegacyParser<UsersSendSignupSmsOtpData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersSendSignupSmsOtpResponse,
    AxiosError<UsersSendSignupSmsOtpError>,
    OptionsLegacyParser<UsersSendSignupSmsOtpData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersSendSignupSmsOtp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersSendSmsOtpQueryKey = (
  options: OptionsLegacyParser<UsersSendSmsOtpData>,
) => [createQueryKey('usersSendSmsOtp', options)];

export const usersSendSmsOtpOptions = (
  options: OptionsLegacyParser<UsersSendSmsOtpData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersSendSmsOtp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersSendSmsOtpQueryKey(options),
  });
};

export const usersSendSmsOtpMutation = (
  options?: Partial<OptionsLegacyParser<UsersSendSmsOtpData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersSendSmsOtpResponse,
    AxiosError<UsersSendSmsOtpError>,
    OptionsLegacyParser<UsersSendSmsOtpData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersSendSmsOtp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersSignupQueryKey = (
  options: OptionsLegacyParser<UsersSignupData>,
) => [createQueryKey('usersSignup', options)];

export const usersSignupOptions = (
  options: OptionsLegacyParser<UsersSignupData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersSignup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersSignupQueryKey(options),
  });
};

export const usersSignupMutation = (
  options?: Partial<OptionsLegacyParser<UsersSignupData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersSignupResponse,
    AxiosError<UsersSignupError>,
    OptionsLegacyParser<UsersSignupData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersSignup({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersVerifyOtpQueryKey = (
  options: OptionsLegacyParser<UsersVerifyOtpData>,
) => [createQueryKey('usersVerifyOtp', options)];

export const usersVerifyOtpOptions = (
  options: OptionsLegacyParser<UsersVerifyOtpData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersVerifyOtp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersVerifyOtpQueryKey(options),
  });
};

export const usersVerifyOtpMutation = (
  options?: Partial<OptionsLegacyParser<UsersVerifyOtpData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersVerifyOtpResponse,
    AxiosError<UsersVerifyOtpError>,
    OptionsLegacyParser<UsersVerifyOtpData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersVerifyOtp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersGetPublicUserQueryKey = (
  options: OptionsLegacyParser<UsersGetPublicUserData>,
) => [createQueryKey('usersGetPublicUser', options)];

export const usersGetPublicUserOptions = (
  options: OptionsLegacyParser<UsersGetPublicUserData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersGetPublicUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetPublicUserQueryKey(options),
  });
};

export const usersCompleteRegistrationQueryKey = (
  options: OptionsLegacyParser<UsersCompleteRegistrationData>,
) => [createQueryKey('usersCompleteRegistration', options)];

export const usersCompleteRegistrationOptions = (
  options: OptionsLegacyParser<UsersCompleteRegistrationData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersCompleteRegistration({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersCompleteRegistrationQueryKey(options),
  });
};

export const usersCompleteRegistrationMutation = (
  options?: Partial<OptionsLegacyParser<UsersCompleteRegistrationData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersCompleteRegistrationResponse,
    AxiosError<UsersCompleteRegistrationError>,
    OptionsLegacyParser<UsersCompleteRegistrationData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersCompleteRegistration({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersDeleteUserAccountQueryKey = (
  options: OptionsLegacyParser<UsersDeleteUserAccountData>,
) => [createQueryKey('usersDeleteUserAccount', options)];

export const usersDeleteUserAccountOptions = (
  options: OptionsLegacyParser<UsersDeleteUserAccountData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersDeleteUserAccount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersDeleteUserAccountQueryKey(options),
  });
};

export const usersListFarmersQueryKey = (
  options: OptionsLegacyParser<UsersListFarmersData>,
) => [createQueryKey('usersListFarmers', options)];

export const usersListFarmersOptions = (
  options: OptionsLegacyParser<UsersListFarmersData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersListFarmers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersListFarmersQueryKey(options),
  });
};

export const usersListFarmersReivewsQueryKey = (
  options: OptionsLegacyParser<UsersListFarmersReivewsData>,
) => [createQueryKey('usersListFarmersReivews', options)];

export const usersListFarmersReivewsOptions = (
  options: OptionsLegacyParser<UsersListFarmersReivewsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersListFarmersReivews({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersListFarmersReivewsQueryKey(options),
  });
};

export const usersGetKycByUserIdQueryKey = (
  options: OptionsLegacyParser<UsersGetKycByUserIdData>,
) => [createQueryKey('usersGetKycByUserId', options)];

export const usersGetKycByUserIdOptions = (
  options: OptionsLegacyParser<UsersGetKycByUserIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersGetKycByUserId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetKycByUserIdQueryKey(options),
  });
};

export const usersGetUserByIdQueryKey = (
  options: OptionsLegacyParser<UsersGetUserByIdData>,
) => [createQueryKey('usersGetUserById', options)];

export const usersGetUserByIdOptions = (
  options: OptionsLegacyParser<UsersGetUserByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersGetUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetUserByIdQueryKey(options),
  });
};

export const usersReviewFarmerQueryKey = (
  options: OptionsLegacyParser<UsersReviewFarmerData>,
) => [createQueryKey('usersReviewFarmer', options)];

export const usersReviewFarmerOptions = (
  options: OptionsLegacyParser<UsersReviewFarmerData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersReviewFarmer({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersReviewFarmerQueryKey(options),
  });
};

export const usersReviewFarmerMutation = (
  options?: Partial<OptionsLegacyParser<UsersReviewFarmerData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersReviewFarmerResponse,
    AxiosError<UsersReviewFarmerError>,
    OptionsLegacyParser<UsersReviewFarmerData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersReviewFarmer({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersCreateKycQueryKey = (
  options: OptionsLegacyParser<UsersCreateKycData>,
) => [createQueryKey('usersCreateKyc', options)];

export const usersCreateKycOptions = (
  options: OptionsLegacyParser<UsersCreateKycData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersCreateKyc({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersCreateKycQueryKey(options),
  });
};

export const usersCreateKycMutation = (
  options?: Partial<OptionsLegacyParser<UsersCreateKycData>>,
) => {
  const mutationOptions: UseMutationOptions<
    UsersCreateKycResponse,
    AxiosError<UsersCreateKycError>,
    OptionsLegacyParser<UsersCreateKycData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await usersCreateKyc({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersGetFarmerByIdQueryKey = (
  options: OptionsLegacyParser<UsersGetFarmerByIdData>,
) => [createQueryKey('usersGetFarmerById', options)];

export const usersGetFarmerByIdOptions = (
  options: OptionsLegacyParser<UsersGetFarmerByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await usersGetFarmerById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetFarmerByIdQueryKey(options),
  });
};
