// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  OrdersListAllActiveSubscriptionsData,
  OrdersListAllActiveSubscriptionsError,
  OrdersListAllActiveSubscriptionsResponse,
  OrdersBulkSettleCommissionsData,
  OrdersBulkSettleCommissionsError,
  OrdersBulkSettleCommissionsResponse,
  OrdersListCommissionsByReferrerData,
  OrdersListCommissionsByReferrerError,
  OrdersListCommissionsByReferrerResponse,
  OrdersListTotalComissionAmountByReferrerData,
  OrdersListTotalComissionAmountByReferrerError,
  OrdersListTotalComissionAmountByReferrerResponse,
  OrdersCreateSubscriptionPlanData,
  OrdersCreateSubscriptionPlanError,
  OrdersCreateSubscriptionPlanResponse,
  OrdersListOrdersDueSoonData,
  OrdersListOrdersDueSoonError,
  OrdersListOrdersDueSoonResponse,
  OrdersUpdateSubscriptionPlanData,
  OrdersUpdateSubscriptionPlanError,
  OrdersUpdateSubscriptionPlanResponse,
  OrdersCreateDeliveryPointData,
  OrdersCreateDeliveryPointError,
  OrdersCreateDeliveryPointResponse,
  OrdersGetAdminStatsData,
  OrdersGetAdminStatsError,
  OrdersGetAdminStatsResponse,
  OrdersListOrdersData,
  OrdersListOrdersError,
  OrdersListOrdersResponse,
  OrdersListPaymentsData,
  OrdersListPaymentsError,
  OrdersListPaymentsResponse,
  OrdersDeleteDeliveryPointData,
  OrdersDeleteDeliveryPointError,
  OrdersDeleteDeliveryPointResponse,
  OrdersUpdateDeliveryPointData,
  OrdersUpdateDeliveryPointError,
  OrdersUpdateDeliveryPointResponse,
  OrdersConfirmPaymentData,
  OrdersConfirmPaymentError,
  OrdersConfirmPaymentResponse,
  OrdersHealthCheckError,
  OrdersHealthCheckResponse,
  OrdersListSubscriptionPlansData,
  OrdersListSubscriptionPlansError,
  OrdersListSubscriptionPlansResponse,
  OrdersGetFarmerEarningsData,
  OrdersGetFarmerEarningsError,
  OrdersGetFarmerEarningsResponse,
  OrdersListFarmerOrdersData,
  OrdersListFarmerOrdersError,
  OrdersListFarmerOrdersResponse,
  OrdersGetAgentRatingSummaryData,
  OrdersGetAgentRatingSummaryError,
  OrdersGetAgentRatingSummaryResponse,
  OrdersCreateCustomSubscriptionData,
  OrdersCreateCustomSubscriptionError,
  OrdersCreateCustomSubscriptionResponse,
  OrdersCreateOrderData,
  OrdersCreateOrderError,
  OrdersCreateOrderResponse,
  OrdersEstimateDeliveryFeeData,
  OrdersEstimateDeliveryFeeError,
  OrdersEstimateDeliveryFeeResponse,
  OrdersGetAgentStatsData,
  OrdersGetAgentStatsError,
  OrdersGetAgentStatsResponse,
  OrdersInitiatePaymentData,
  OrdersInitiatePaymentError,
  OrdersInitiatePaymentResponse,
  OrdersListAgentAvailableOrdersData,
  OrdersListAgentAvailableOrdersError,
  OrdersListAgentAvailableOrdersResponse,
  OrdersListAgentDeliveredOrdersData,
  OrdersListAgentDeliveredOrdersError,
  OrdersListAgentDeliveredOrdersResponse,
  OrdersListAgentOngoingOrdersData,
  OrdersListAgentOngoingOrdersError,
  OrdersListAgentOngoingOrdersResponse,
  OrdersListDeliveryCitiesData,
  OrdersListDeliveryCitiesError,
  OrdersListDeliveryCitiesResponse,
  OrdersListDeliveryPointsData,
  OrdersListDeliveryPointsError,
  OrdersListDeliveryPointsResponse,
  OrdersListUserOrdersData,
  OrdersListUserOrdersError,
  OrdersListUserOrdersResponse,
  OrdersSubscribeData,
  OrdersSubscribeError,
  OrdersSubscribeResponse,
  OrdersListUserSubscriptionsData,
  OrdersListUserSubscriptionsError,
  OrdersListUserSubscriptionsResponse,
  OrdersGetUserSubscriptionDetailsData,
  OrdersGetUserSubscriptionDetailsError,
  OrdersGetUserSubscriptionDetailsResponse,
  OrdersApproveOrderData,
  OrdersApproveOrderError,
  OrdersApproveOrderResponse,
  OrdersRejectOrderData,
  OrdersRejectOrderError,
  OrdersRejectOrderResponse,
  OrdersCreateDeliveryRatingData,
  OrdersCreateDeliveryRatingError,
  OrdersCreateDeliveryRatingResponse,
  OrdersDispatchOrderData,
  OrdersDispatchOrderError,
  OrdersDispatchOrderResponse,
  OrdersGetOrderDetailsData,
  OrdersGetOrderDetailsError,
  OrdersGetOrderDetailsResponse,
  OrdersCheckPaymentStatusData,
  OrdersCheckPaymentStatusError,
  OrdersCheckPaymentStatusResponse,
  OrdersConfirmDeliveryData,
  OrdersConfirmDeliveryError,
  OrdersConfirmDeliveryResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export const ordersListAllActiveSubscriptions = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    OrdersListAllActiveSubscriptionsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    OrdersListAllActiveSubscriptionsResponse,
    OrdersListAllActiveSubscriptionsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{adminUserId}/orders/all-active-subscriptions",
  });
};

export const ordersBulkSettleCommissions = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersBulkSettleCommissionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersBulkSettleCommissionsResponse,
    OrdersBulkSettleCommissionsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{adminUserId}/orders/commission/bulk-settle-commissions",
  });
};

export const ordersListCommissionsByReferrer = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    OrdersListCommissionsByReferrerData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    OrdersListCommissionsByReferrerResponse,
    OrdersListCommissionsByReferrerError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{adminUserId}/orders/commission/{referrerId}/list-commissions-by-referrer",
  });
};

export const ordersListTotalComissionAmountByReferrer = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    OrdersListTotalComissionAmountByReferrerData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    OrdersListTotalComissionAmountByReferrerResponse,
    OrdersListTotalComissionAmountByReferrerError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{adminUserId}/orders/commission/{referrerId}/list-total-commission-amount-by-referrer",
  });
};

export const ordersCreateSubscriptionPlan = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersCreateSubscriptionPlanData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersCreateSubscriptionPlanResponse,
    OrdersCreateSubscriptionPlanError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{adminUserId}/orders/create-subscription-plan",
  });
};

export const ordersListOrdersDueSoon = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersListOrdersDueSoonData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListOrdersDueSoonResponse,
    OrdersListOrdersDueSoonError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{adminUserId}/orders/due-soon",
  });
};

export const ordersUpdateSubscriptionPlan = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersUpdateSubscriptionPlanData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    OrdersUpdateSubscriptionPlanResponse,
    OrdersUpdateSubscriptionPlanError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{adminUserId}/orders/{subscriptionPlanId}/update-subscription-plan",
  });
};

export const ordersCreateDeliveryPoint = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersCreateDeliveryPointData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersCreateDeliveryPointResponse,
    OrdersCreateDeliveryPointError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{userId}/orders/create-delivery-point",
  });
};

export const ordersGetAdminStats = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersGetAdminStatsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetAdminStatsResponse,
    OrdersGetAdminStatsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{userId}/orders/get-admin-stats",
  });
};

export const ordersListOrders = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersListOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListOrdersResponse,
    OrdersListOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{userId}/orders/list-orders",
  });
};

export const ordersListPayments = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersListPaymentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListPaymentsResponse,
    OrdersListPaymentsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{userId}/orders/list-payments",
  });
};

export const ordersDeleteDeliveryPoint = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersDeleteDeliveryPointData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    OrdersDeleteDeliveryPointResponse,
    OrdersDeleteDeliveryPointError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{userId}/orders/{id}/delete-delivery-point",
  });
};

export const ordersUpdateDeliveryPoint = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersUpdateDeliveryPointData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    OrdersUpdateDeliveryPointResponse,
    OrdersUpdateDeliveryPointError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/admin/{userId}/orders/{id}/update-delivery-point",
  });
};

export const ordersConfirmPayment = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersConfirmPaymentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersConfirmPaymentResponse,
    OrdersConfirmPaymentError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/public/confirm-payment",
  });
};

export const ordersHealthCheck = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersHealthCheckResponse,
    OrdersHealthCheckError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/public/orders/health-check",
  });
};

export const ordersListSubscriptionPlans = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersListSubscriptionPlansData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListSubscriptionPlansResponse,
    OrdersListSubscriptionPlansError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/user/{userId}/orders/list-subscription-plans",
  });
};

export const ordersGetFarmerEarnings = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersGetFarmerEarningsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetFarmerEarningsResponse,
    OrdersGetFarmerEarningsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{farmerId}/orders/get-farmer-earnings",
  });
};

export const ordersListFarmerOrders = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersListFarmerOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListFarmerOrdersResponse,
    OrdersListFarmerOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{farmerId}/orders/list-farmer-orders",
  });
};

export const ordersGetAgentRatingSummary = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersGetAgentRatingSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetAgentRatingSummaryResponse,
    OrdersGetAgentRatingSummaryError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/agents/{agentId}/get-delivery-rating-summary",
  });
};

export const ordersCreateCustomSubscription = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    OrdersCreateCustomSubscriptionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    OrdersCreateCustomSubscriptionResponse,
    OrdersCreateCustomSubscriptionError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/create-custom-subscription",
  });
};

export const ordersCreateOrder = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersCreateOrderData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersCreateOrderResponse,
    OrdersCreateOrderError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/create-order",
  });
};

export const ordersEstimateDeliveryFee = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersEstimateDeliveryFeeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersEstimateDeliveryFeeResponse,
    OrdersEstimateDeliveryFeeError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/estimate-delivery-fee",
  });
};

export const ordersGetAgentStats = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersGetAgentStatsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetAgentStatsResponse,
    OrdersGetAgentStatsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/get-agent-stats",
  });
};

export const ordersInitiatePayment = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersInitiatePaymentData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersInitiatePaymentResponse,
    OrdersInitiatePaymentError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/initiate-payment",
  });
};

export const ordersListAgentAvailableOrders = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    OrdersListAgentAvailableOrdersData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    OrdersListAgentAvailableOrdersResponse,
    OrdersListAgentAvailableOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/list-agent-available-orders",
  });
};

export const ordersListAgentDeliveredOrders = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    OrdersListAgentDeliveredOrdersData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    OrdersListAgentDeliveredOrdersResponse,
    OrdersListAgentDeliveredOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/list-agent-delivered-orders",
  });
};

export const ordersListAgentOngoingOrders = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersListAgentOngoingOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListAgentOngoingOrdersResponse,
    OrdersListAgentOngoingOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/list-agent-ongoing-orders",
  });
};

export const ordersListDeliveryCities = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersListDeliveryCitiesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListDeliveryCitiesResponse,
    OrdersListDeliveryCitiesError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/list-delivery-cities",
  });
};

export const ordersListDeliveryPoints = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersListDeliveryPointsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListDeliveryPointsResponse,
    OrdersListDeliveryPointsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/list-delivery-points",
  });
};

export const ordersListUserOrders = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersListUserOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListUserOrdersResponse,
    OrdersListUserOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/list-user-orders",
  });
};

export const ordersSubscribe = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersSubscribeData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersSubscribeResponse,
    OrdersSubscribeError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/subscribe",
  });
};

export const ordersListUserSubscriptions = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersListUserSubscriptionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersListUserSubscriptionsResponse,
    OrdersListUserSubscriptionsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/subscriptions",
  });
};

export const ordersGetUserSubscriptionDetails = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    OrdersGetUserSubscriptionDetailsData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    OrdersGetUserSubscriptionDetailsResponse,
    OrdersGetUserSubscriptionDetailsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/subscriptions/{subscriptionId}",
  });
};

export const ordersApproveOrder = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersApproveOrderData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    OrdersApproveOrderResponse,
    OrdersApproveOrderError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/{orderId}/approve-order",
  });
};

export const ordersRejectOrder = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersRejectOrderData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    OrdersRejectOrderResponse,
    OrdersRejectOrderError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/{orderId}/reject-order",
  });
};

export const ordersCreateDeliveryRating = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<OrdersCreateDeliveryRatingData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersCreateDeliveryRatingResponse,
    OrdersCreateDeliveryRatingError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/{orderNumber}/create-delivery-rating",
  });
};

export const ordersDispatchOrder = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersDispatchOrderData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    OrdersDispatchOrderResponse,
    OrdersDispatchOrderError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/{orderNumber}/dispatch-order",
  });
};

export const ordersGetOrderDetails = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersGetOrderDetailsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetOrderDetailsResponse,
    OrdersGetOrderDetailsError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/{orderNumber}/get-order-details",
  });
};

export const ordersCheckPaymentStatus = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersCheckPaymentStatusData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersCheckPaymentStatusResponse,
    OrdersCheckPaymentStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/{paymentId}/check-payment-status",
  });
};

export const ordersConfirmDelivery = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<OrdersConfirmDeliveryData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    OrdersConfirmDeliveryResponse,
    OrdersConfirmDeliveryError,
    ThrowOnError
  >({
    ...options,
    url: "/v1/users/{userId}/orders/{secretKey}/confirm-delivery",
  });
};
