import { Colors } from "@/constants";
import { StyleSheet } from "react-native";

export const phoneNumberInputStyles = StyleSheet.create({
  mainContainer: {
    flexDirection: "row",
    columnGap: 12,
  },
  inputContainer: {
    borderWidth: 1,
    width: "100%",
    borderColor: Colors.grey["bg"],
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 52,
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.grey["fa"],
    position: "relative",
  },
  label: {
    position: "absolute",
    left: 16,
    fontSize: 17,
    backgroundColor: Colors.grey["fa"],
    paddingHorizontal: 6,
    zIndex: 1,
  },
  countryCodeContainer: {
    backgroundColor: Colors.grey["ea"],
    flexDirection: "row",
    columnGap: 8,
    alignItems: "center",
    height: 58,
    justifyContent: "center",
    padding: 16,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: Colors.primary["300"],
  },
  countryCodeText: {
    fontSize: 16,
    marginLeft: 2,
    // color: Colors.grey["surface"],
  },
  divider: {
    height: "100%",
    width: 2,
    // backgroundColor: Colors.grey[20],
  },
  errorInput: {
    borderWidth: 1,
    borderColor: Colors.error,
  },
  focusedMode: {
    borderWidth: 2,
    // borderColor: Colors.grey['79'],
  },
  input: {
    backgroundColor: Colors.grey["ea"],
    flexGrow: 1,
    height: 56,
    fontSize: 16,
    borderRadius: 10,
    paddingHorizontal: 16,
    bottom: 6,
    // marginLeft: 20,
  },
  outlineInput: {
    borderWidth: 0.5,
    borderColor: Colors.primary["300"],
  },
  searchInput: {
    backgroundColor: "transparent",
    flexGrow: 1,
    height: 48,
    fontSize: 18,
    color: Colors.dark[0],
  },
  backgroundDark: {
    backgroundColor: Colors.light[0],
    flex: 1,
  },
  modalContainer: {
    padding: 24,
    rowGap: 16,
  },
  searchcontainer: {
    flexDirection: "row",
    columnGap: 8,
    marginRight: 4,
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 14,
    padding: 8,
  },
  countryItem: {
    paddingVertical: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.grey["3c"],
  },
  texts: {
    flexDirection: "row",
    columnGap: 8,
    alignItems: "center",
  },
  emoji: {
    fontSize: 24,
  },
  countryName: {
    fontSize: 18,
    color: Colors.dark[0],
  },
  countryContainer: {
    backgroundColor: Colors.grey["fa"],
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    height: 52,
    justifyContent: "space-between",
    paddingRight: 12,
    paddingLeft: 24,
    borderRadius: 10,
    borderColor: Colors.grey["border"],
    borderWidth: 1,
  },
  flexContainer: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    height: 64,
    justifyContent: "space-between",
    padding: 16,
    borderRadius: 4,
  },
  flexSmallContainer: {
    flexDirection: "row",
    columnGap: 16,
    width: '100%',
    paddingHorizontal: 16,
  },
});
