// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Slug      string  `json:"slug"`
	CreatedBy *string `json:"created_by"`
}

type PriceType struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Slug       string  `json:"slug"`
	CategoryID *string `json:"category_id"`
}

type Product struct {
	ID              string             `json:"id"`
	CategoryID      *string            `json:"category_id"`
	Name            string             `json:"name"`
	UnitType        string             `json:"unit_type"`
	Value           float64            `json:"value"`
	CurrencyIsoCode string             `json:"currency_iso_code"`
	Description     string             `json:"description"`
	Image           string             `json:"image"`
	CreatedBy       *string            `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WholeSale       bool               `json:"whole_sale"`
}

type ProductName struct {
	Name       string  `json:"name"`
	Slug       string  `json:"slug"`
	CategoryID *string `json:"category_id"`
}
