// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"
	"time"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_by
`

type CreateCategoryParams struct {
	Name      string  `json:"name"`
	Slug      string  `json:"slug"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug, arg.CreatedBy)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
	)
	return i, err
}

const createPriceType = `-- name: CreatePriceType :one
INSERT INTO price_types (name, slug, category_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, category_id
`

type CreatePriceTypeParams struct {
	Name       string  `json:"name"`
	Slug       string  `json:"slug"`
	CategoryID *string `json:"category_id"`
}

func (q *Queries) CreatePriceType(ctx context.Context, arg CreatePriceTypeParams) (PriceType, error) {
	row := q.db.QueryRow(ctx, createPriceType, arg.Name, arg.Slug, arg.CategoryID)
	var i PriceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CategoryID,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  category_id, name, unit_type, value, currency_iso_code,
  description, image, created_by, whole_sale
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9
)
RETURNING id, category_id, name, unit_type, value, currency_iso_code, description, image, created_by, created_at, updated_at, whole_sale, deleted_at
`

type CreateProductParams struct {
	CategoryID      *string `json:"category_id"`
	Name            string  `json:"name"`
	UnitType        string  `json:"unit_type"`
	Value           float64 `json:"value"`
	CurrencyIsoCode string  `json:"currency_iso_code"`
	Description     string  `json:"description"`
	Image           string  `json:"image"`
	CreatedBy       *string `json:"created_by"`
	WholeSale       bool    `json:"whole_sale"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.UnitType,
		arg.Value,
		arg.CurrencyIsoCode,
		arg.Description,
		arg.Image,
		arg.CreatedBy,
		arg.WholeSale,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.UnitType,
		&i.Value,
		&i.CurrencyIsoCode,
		&i.Description,
		&i.Image,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WholeSale,
		&i.DeletedAt,
	)
	return i, err
}

const createProductName = `-- name: CreateProductName :one
INSERT INTO product_names (name, slug, category_id)
VALUES ($1, $2, $3)
RETURNING name, slug, category_id
`

type CreateProductNameParams struct {
	Name       string  `json:"name"`
	Slug       string  `json:"slug"`
	CategoryID *string `json:"category_id"`
}

func (q *Queries) CreateProductName(ctx context.Context, arg CreateProductNameParams) (ProductName, error) {
	row := q.db.QueryRow(ctx, createProductName, arg.Name, arg.Slug, arg.CategoryID)
	var i ProductName
	err := row.Scan(&i.Name, &i.Slug, &i.CategoryID)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deletePriceType = `-- name: DeletePriceType :exec
DELETE FROM price_types WHERE id = $1
`

func (q *Queries) DeletePriceType(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePriceType, id)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteProductName = `-- name: DeleteProductName :exec
DELETE FROM product_names WHERE name = $1
`

func (q *Queries) DeleteProductName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteProductName, name)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, slug, created_by FROM categories where id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, category_id, name, unit_type, value, currency_iso_code, description, image, created_by, created_at, updated_at, whole_sale, deleted_at FROM products where id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.UnitType,
		&i.Value,
		&i.CurrencyIsoCode,
		&i.Description,
		&i.Image,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WholeSale,
		&i.DeletedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, category_id, name, unit_type, value, currency_iso_code, description, image, created_by, created_at, updated_at, whole_sale, deleted_at FROM products WHERE   
deleted_at IS NULL AND  
id = $1 FOR UPDATE
`

func (q *Queries) GetProductForUpdate(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.UnitType,
		&i.Value,
		&i.CurrencyIsoCode,
		&i.Description,
		&i.Image,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WholeSale,
		&i.DeletedAt,
	)
	return i, err
}

const getProductStatsBetweenDates = `-- name: GetProductStatsBetweenDates :one
SELECT
  COUNT(*) AS total_products
FROM products
WHERE created_at >= $1::timestamptz
  AND created_at <= $2::timestamptz
`

type GetProductStatsBetweenDatesParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetProductStatsBetweenDates(ctx context.Context, arg GetProductStatsBetweenDatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, getProductStatsBetweenDates, arg.StartDate, arg.EndDate)
	var total_products int64
	err := row.Scan(&total_products)
	return total_products, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, created_by FROM categories
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTypes = `-- name: ListPriceTypes :many
SELECT id, name, slug, category_id FROM price_types
WHERE ($1::text = '' OR category_id = $1)
ORDER BY slug ASC
`

func (q *Queries) ListPriceTypes(ctx context.Context, categoryID string) ([]PriceType, error) {
	rows, err := q.db.Query(ctx, listPriceTypes, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceType{}
	for rows.Next() {
		var i PriceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductNames = `-- name: ListProductNames :many
SELECT name, slug, category_id FROM product_names 
WHERE ($1::text = '' OR category_id = $1)
ORDER BY slug ASC
`

func (q *Queries) ListProductNames(ctx context.Context, categoryID string) ([]ProductName, error) {
	rows, err := q.db.Query(ctx, listProductNames, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductName{}
	for rows.Next() {
		var i ProductName
		if err := rows.Scan(&i.Name, &i.Slug, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, unit_type, value, currency_iso_code, description, image, created_by, created_at, updated_at, whole_sale, deleted_at FROM products
WHERE
  deleted_at IS NULL AND
  ($1::varchar = '' OR created_by = $1::varchar) AND
  ($2::varchar = '' OR category_id = $2::varchar) AND
  ($3::float = 0 OR value >= $3::float) AND
  (
    $4::float = 0 OR value <= COALESCE($4::float, 9223372036854775807)
  ) AND
  (
    $5::text = '' OR
    name ILIKE '%' || $5::text || '%' OR
    description ILIKE '%' || $5::text || '%'
  ) AND
  ($6::timestamptz = '0001-01-01 00:00:00+00'::timestamptz OR created_at < $6::timestamptz)
ORDER BY created_at DESC
LIMIT $7::int
`

type ListProductsParams struct {
	CreatedBy     string    `json:"created_by"`
	CategoryID    string    `json:"category_id"`
	MinValue      float64   `json:"min_value"`
	MaxValue      float64   `json:"max_value"`
	Search        string    `json:"search"`
	CreatedBefore time.Time `json:"created_before"`
	Count         int32     `json:"count"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CreatedBy,
		arg.CategoryID,
		arg.MinValue,
		arg.MaxValue,
		arg.Search,
		arg.CreatedBefore,
		arg.Count,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.UnitType,
			&i.Value,
			&i.CurrencyIsoCode,
			&i.Description,
			&i.Image,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WholeSale,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumProductAmounts = `-- name: SumProductAmounts :one
SELECT 
  COALESCE(SUM(p.value * t.quantity), 0)::double precision AS total
FROM (
  SELECT 
    UNNEST($1::text[]) AS id,
    UNNEST($2::bigint[]) AS quantity
) AS t
JOIN products p ON p.id = t.id
`

type SumProductAmountsParams struct {
	ProductIds []string `json:"product_ids"`
	Quantities []int64  `json:"quantities"`
}

func (q *Queries) SumProductAmounts(ctx context.Context, arg SumProductAmountsParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumProductAmounts, arg.ProductIds, arg.Quantities)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET name = $2,
    slug = $3
WHERE id = $1
`

type UpdateCategoryParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.Exec(ctx, updateCategory, arg.ID, arg.Name, arg.Slug)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET category_id = $3,
    name = $4,
    unit_type = $5,
    value = $6,
    currency_iso_code = $7,
    description = $8,
    image = $9,
    whole_sale = $10,
    updated_at = now()
WHERE id = $2 AND created_by = $1
`

type UpdateProductParams struct {
	CreatedBy       *string `json:"created_by"`
	ID              string  `json:"id"`
	CategoryID      *string `json:"category_id"`
	Name            string  `json:"name"`
	UnitType        string  `json:"unit_type"`
	Value           float64 `json:"value"`
	CurrencyIsoCode string  `json:"currency_iso_code"`
	Description     string  `json:"description"`
	Image           string  `json:"image"`
	WholeSale       bool    `json:"whole_sale"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.CreatedBy,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.UnitType,
		arg.Value,
		arg.CurrencyIsoCode,
		arg.Description,
		arg.Image,
		arg.WholeSale,
	)
	return err
}
