// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package sqlc

import (
	"context"
	"time"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_by
`

type CreateCategoryParams struct {
	Name      string  `json:"name"`
	Slug      string  `json:"slug"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug, arg.CreatedBy)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (
  category_id, name, unit_type, value, currency_iso_code,
  description, image, created_by
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8
)
RETURNING id, category_id, name, unit_type, value, currency_iso_code, description, image, created_by, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID      string  `json:"category_id"`
	Name            string  `json:"name"`
	UnitType        string  `json:"unit_type"`
	Value           int64   `json:"value"`
	CurrencyIsoCode string  `json:"currency_iso_code"`
	Description     string  `json:"description"`
	Image           string  `json:"image"`
	CreatedBy       *string `json:"created_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.UnitType,
		arg.Value,
		arg.CurrencyIsoCode,
		arg.Description,
		arg.Image,
		arg.CreatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.UnitType,
		&i.Value,
		&i.CurrencyIsoCode,
		&i.Description,
		&i.Image,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, unit_type, value, currency_iso_code, description, image, created_by, created_at, updated_at
FROM product
WHERE
  ($1::varchar IS NULL OR created_by = $1) AND
  ($2::varchar IS NULL OR category_id = $2) AND
  (value >= COALESCE($3, 0)) AND
  (value <= COALESCE($4, 9223372036854775807)) AND
  ($5::text IS NULL OR name ILIKE '%' || $5 || '%' OR description ILIKE '%' || $5 || '%') AND
  ($6::timestamptz IS NULL OR created_at < $6)
ORDER BY created_at DESC
LIMIT COALESCE($7, 50)
`

type ListProductsParams struct {
	Column1 string      `json:"column_1"`
	Column2 string      `json:"column_2"`
	Value   int64       `json:"value"`
	Value_2 int64       `json:"value_2"`
	Column5 string      `json:"column_5"`
	Column6 time.Time   `json:"column_6"`
	Column7 interface{} `json:"column_7"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Column1,
		arg.Column2,
		arg.Value,
		arg.Value_2,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.UnitType,
			&i.Value,
			&i.CurrencyIsoCode,
			&i.Description,
			&i.Image,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET category_id = $3,
    name = $4,
    unit_type = $5,
    value = $6,
    currency_iso_code = $7,
    description = $8,
    image = $9,
    updated_at = now()
WHERE id = $2 AND created_by = $1
`

type UpdateProductParams struct {
	CreatedBy       *string `json:"created_by"`
	ID              string  `json:"id"`
	CategoryID      string  `json:"category_id"`
	Name            string  `json:"name"`
	UnitType        string  `json:"unit_type"`
	Value           int64   `json:"value"`
	CurrencyIsoCode string  `json:"currency_iso_code"`
	Description     string  `json:"description"`
	Image           string  `json:"image"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.CreatedBy,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.UnitType,
		arg.Value,
		arg.CurrencyIsoCode,
		arg.Description,
		arg.Image,
	)
	return err
}
