name: Build and Test android

on:
  push:
    branches:
      - preview/android/*
  workflow_dispatch:

jobs:
  build-and-submit-main-app:
    name: Build and submit main app
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      # The EXPO_APPLE_APP_SPECIFIC_PASSWORD and EXPO_APPLE_ID are required for Apple builds.
      # They're used for testflight and appstore submission.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Trying to install dependencies from cache
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('mobile/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        working-directory: mobile
        run: yarn list

      - name: Install dependencies
        working-directory: mobile
        run: yarn install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # With the flag --auto-submit the build will be submitted to testflight / playstore automatically.
      # The app will not be released without manual action
      - name: Build and Submit
        working-directory: mobile
        run: eas build --platform android --profile preview-device --no-wait

  build-and-submit-agent-app:
    name: Build and submit agent app
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      # The EXPO_APPLE_APP_SPECIFIC_PASSWORD and EXPO_APPLE_ID are required for Apple builds.
      # They're used for testflight and appstore submission.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Trying to install dependencies from cache
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('agentsApp/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        working-directory: agentsApp
        run: yarn list

      - name: Install dependencies
        working-directory: agentsApp
        run: yarn install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # With the flag --auto-submit the build will be submitted to testflight / playstore automatically.
      # The app will not be released without manual action
      - name: Build and Submit
        working-directory: agentsApp
        run: eas build --platform android --profile preview-device --no-wait
