name: Publish Build Artifacts

on:
  workflow_call: {}
  push:
    branches:
      - main
      - "release/*"
    tags:
      - "*"
    ## Make sure to include all subdirectories that have build artifacts
    paths:
      - ".github/workflows/publish_build_artifacts.yaml"
      - "infra/**"
      - "users/**"
      - "products/**"
      - "jsonproxy/**"
  workflow_run:
    ## Re-run this workflow if the artifact repositories have changed
    workflows:
      - Artifact Account Setup
    types:
      - completed

# Necessary permissions for workflow
permissions:
  id-token: write
  contents: read

jobs:
  config:
    name: Read workflow configuration
    runs-on: ubuntu-latest
    outputs:
      artifact_account_id: ${{ steps.read_artifact_account_id.outputs.artifact_account_id }}
      infra_bucket_name: ${{ steps.read_artifact_stack_config.outputs.infra_bucket_name }}
      users_ecr_repo_arn: ${{ steps.read_artifact_stack_config.outputs.users_ecr_repo_arn }}
      products_ecr_repo_arn: ${{ steps.read_artifact_stack_config.outputs.products_ecr_repo_arn }}
      jsonproxy_ecr_repo_arn: ${{ steps.read_artifact_stack_config.outputs.jsonproxy_ecr_repo_arn }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: mikefarah/yq@v4.44.3
        with:
          cmd: yq -V

      - name: Read the account id of the Artifact account
        id: read_artifact_account_id
        run: |
          ARTIFACT_ACCOUNT_ID=$(yq eval '.aws_account_id' cd/artifact-account/config.yaml)
          echo "artifact_account_id=$ARTIFACT_ACCOUNT_ID"
          echo "artifact_account_id=$ARTIFACT_ACCOUNT_ID" >> $GITHUB_OUTPUT

      - name: Assume the OIDC Role to get temporary credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ steps.read_artifact_account_id.outputs.artifact_account_id }}:role/deploy

      - name: Read Configuration from Artifact Account Stack
        id: read_artifact_stack_config
        run: |
          artifacts_stack_name='artifact-account-setup'
          infra_bucket_name=$(aws cloudformation describe-stacks --stack-name "$artifacts_stack_name" --query "Stacks[0].Outputs[?OutputKey=='InfraArtifactsBucket'].OutputValue" --output text )
          users_ecr_repo_arn=$(aws cloudformation describe-stacks --stack-name "$artifacts_stack_name" --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryusersArn'].OutputValue" --output text )
          products_ecr_repo_arn=$(aws cloudformation describe-stacks --stack-name "$artifacts_stack_name" --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryproductsArn'].OutputValue" --output text )
          jsonproxy_ecr_repo_arn=$(aws cloudformation describe-stacks --stack-name "$artifacts_stack_name" --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryjsonproxyArn'].OutputValue" --output text )

            echo "infra_bucket_name=$infra_bucket_name" >> $GITHUB_OUTPUT
            echo "users_ecr_repo_arn=$users_ecr_repo_arn" >> $GITHUB_OUTPUT
            echo "products_ecr_repo_arn=$users_ecr_repo_arn" >> $GITHUB_OUTPUT
            echo "jsonproxy_ecr_repo_arn=$jsonproxy_ecr_repo_arn" >> $GITHUB_OUTPUT


  users:
    name: Build and Publish Users Docker Image
    needs: [config]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ needs.config.outputs.artifact_account_id }}:role/deploy

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image and Push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # We need to get the last commit hash of the users directory and the grpc directory.
          # If either change we need ot push a new image.
          commit_hash=$(find ./users/ ./grpc/ -type f -exec sha256sum {} + | sort | sha256sum | cut -f 1 -d ' ')
          users_ecr_repo_arn="${{ needs.config.outputs.users_ecr_repo_arn }}"
          users_ecr_repo_name=$(echo $users_ecr_repo_arn | cut -d'/' -f2)
          full_image_tag=$ECR_REGISTRY/$users_ecr_repo_name:$commit_hash 

          # Check if this tag already exists if so, we can skip the build.
          if [ -z "$(docker manifest inspect "$full_image_tag" 2> /dev/null)" ]; then
            cd users
            make build full_image_tag="$full_image_tag"
            make publish full_image_tag="$full_image_tag"
          else
              echo "Image already exists, skipping build"
          fi
          aws ssm put-parameter --name "/build-artifact/users/$GITHUB_REF_NAME" --value "$full_image_tag"  --type "String" --overwrite

  products:
    name: Build and Publish Products Docker Image
    needs: [config]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ needs.config.outputs.artifact_account_id }}:role/deploy

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image and Push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # We need to get the last commit hash of the products directory and the grpc directory.
          # If either change we need ot push a new image.
          commit_hash=$(find ./products/ ./grpc/ -type f -exec sha256sum {} + | sort | sha256sum | cut -f 1 -d ' ')
          products_ecr_repo_arn="${{ needs.config.outputs.products_ecr_repo_arn }}"
          products_ecr_repo_name=$(echo $products_ecr_repo_arn | cut -d'/' -f2)
          full_image_tag=$ECR_REGISTRY/$products_ecr_repo_name:$commit_hash 

          # Check if this tag already exists if so, we can skip the build.
          if [ -z "$(docker manifest inspect "$full_image_tag" 2> /dev/null)" ]; then
            cd products
            make build full_image_tag="$full_image_tag"
            make publish full_image_tag="$full_image_tag"
          else
              echo "Image already exists, skipping build"
          fi
          aws ssm put-parameter --name "/build-artifact/products/$GITHUB_REF_NAME" --value "$full_image_tag"  --type "String" --overwrite


  jsonproxy:
    name: Build and Publish Jsonproxy Docker Image
    needs: [config]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ needs.config.outputs.artifact_account_id }}:role/deploy

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image and Push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # We need to hash the contents of the jsonproxy directory and the grpc directory.
          # If either change we need to push a new image.
          commit_hash=$(find ./jsonproxy/ ./grpc/ -type f -exec sha256sum {} + | sort | sha256sum | cut -f 1 -d ' ')
          jsonproxy_ecr_repo_arn="${{ needs.config.outputs.jsonproxy_ecr_repo_arn }}"
          jsonproxy_ecr_repo_name=$(echo $jsonproxy_ecr_repo_arn | cut -d'/' -f2)
          full_image_tag=$ECR_REGISTRY/$jsonproxy_ecr_repo_name:$commit_hash 

          # Check if this tag already exists if so, we can skip the build.
          if [ -z "$(docker manifest inspect "$full_image_tag" 2> /dev/null)" ]; then
            cd jsonproxy
            make build full_image_tag="$full_image_tag"
            make publish full_image_tag="$full_image_tag"
          else
            echo "Image already exists, skipping build"
          fi

          aws ssm put-parameter --name "/build-artifact/jsonproxy/$GITHUB_REF_NAME" --value "$full_image_tag"  --type "String" --overwrite
  

  infra:
    name: Publish Infra Artifacts
    runs-on: ubuntu-latest
    needs: [config]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Assume the OIDC Role to get temporary credentials
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ needs.config.outputs.artifact_account_id }}:role/deploy

      - name: Upload Cloudformation Templates to S3
        env:
          CF_DIR: "cloudformation"
        run: |
          ## Get the last commit hash of the infra directory
          commit_hash=$(find ./infra/  -type f -exec sha256sum {} + | sort | sha256sum | cut -f 1 -d ' ')

          bucket_name="${{ needs.config.outputs.infra_bucket_name }}"
          cd infra && \
          make publish bucket_name="$bucket_name" artifact_hash="$commit_hash" CF_DIR="$CF_DIR"
          aws ssm put-parameter --name "/build-artifact/infra/$GITHUB_REF_NAME" --value "$commit_hash"  --type "String" --overwrite
