// This file is auto-generated by @hey-api/openapi-ts

export type OrdersApproveOrderBody = unknown;

export type OrdersConfirmDeliveryBody = unknown;

export type OrdersCreateDeliveryPointBody = {
    address?: typesPoint;
    city?: string;
    deliveryPointName?: string;
};

export type OrdersCreateOrderBody = {
    productId?: string;
    quantity?: string;
    deliveryLocation?: typesPoint;
};

export type OrdersDispatchOrderBody = unknown;

export type ordersgrpcAccount = {
    paymentMethod?: ordersgrpcPaymentMethodType;
    accountNumber?: string;
};

export type ordersgrpcApproveOrderResponse = unknown;

export type ordersgrpcConfirmDeliveryResponse = unknown;

export type ordersgrpcConfirmPaymentResponse = unknown;

export type ordersgrpcCreateDeliveryPointResponse = {
    deliveryPoint?: ordersgrpcDeliveryPoint;
};

export type ordersgrpcCreateOrderResponse = {
    order?: ordersgrpcOrder;
};

export type ordersgrpcDeliveryPoint = {
    id?: string;
    address?: typesPoint;
    deliveryPointName?: string;
    city?: string;
    createdAt?: string;
};

export type ordersgrpcDispatchOrderResponse = unknown;

export type ordersgrpcGetOrderDetailsResponse = {
    order?: ordersgrpcOrder;
    auditLog?: Array<ordersgrpcOrderAuditLog>;
};

export type ordersgrpcHealthCheckResponse = unknown;

export type ordersgrpcInitiatePaymentResponse = {
    payment?: ordersgrpcPayment;
};

export type ordersgrpcListDeliveryCitiesResponse = {
    cities?: Array<(string)>;
    nextKey?: string;
};

export type ordersgrpcListDeliveryPointsResponse = {
    deliveryPoints?: Array<ordersgrpcDeliveryPoint>;
    nextKey?: string;
};

export type ordersgrpcListFarmerOrdersResponse = {
    orders?: Array<ordersgrpcOrder>;
    nextKey?: string;
};

export type ordersgrpcListUserOrdersResponse = {
    orders?: Array<ordersgrpcOrder>;
    nextKey?: string;
};

export type ordersgrpcOrder = {
    orderNumber?: string;
    deliveryLocation?: typesPoint;
    price?: typesAmount;
    status?: ordersgrpcOrderStatus;
    rating?: number;
    review?: string;
    product?: string;
    createdBy?: string;
    createdAt?: string;
    updatedAt?: string;
    secretKey?: string;
    productOwner?: string;
    payoutPhoneNumber?: string;
};

export type ordersgrpcOrderAuditLog = {
    timestamp?: string;
    actor?: string;
    action?: string;
    reason?: string;
    before?: ordersgrpcOrder;
    after?: ordersgrpcOrder;
};

export type ordersgrpcOrderStatus = 'OrderStatus_UNSPECIFIED' | 'OrderStatus_CREATED' | 'OrderStatus_PAYMENT_SUCCESSFUL' | 'OrderStatus_PAYMENT_FAILED' | 'OrderStatus_IN_TRANSIT' | 'OrderStatus_DELIVERED' | 'OrderStatus_APPROVED';

export type ordersgrpcPayment = {
    id?: string;
    paymentEntity?: ordersgrpcPaymentEntity;
    entityId?: string;
    amount?: typesAmount;
    createdBy?: string;
    createdAt?: string;
    expiresAt?: string;
    updatedAt?: string;
    status?: ordersgrpcPaymentStatus;
    account?: ordersgrpcAccount;
};

export type ordersgrpcPaymentEntity = 'PaymentEntity_UNSPECIFIED' | 'PaymentEntity_ORDER' | 'PaymentEntity_SUBSCRIPTION';

export type ordersgrpcPaymentMethodType = 'PaymentMethodType_UNSPECIFIED' | 'PaymentMethodType_MOBILE_MONEY' | 'PaymentMethodType_ORANGE_MONEY' | 'PaymentMethodType_CREDIT_CARD';

export type ordersgrpcPaymentStatus = 'PaymentStatus_UNSPECIFIED' | 'PaymentStatus_INITIATED' | 'PaymentStatus_COMPLETED' | 'PaymentStatus_FAILED' | 'PaymentStatus_CANCELED';

export type OrdersInitiatePaymentBody = {
    paymentEntity?: ordersgrpcPaymentEntity;
    entityId?: string;
    amount?: typesAmount;
    account?: ordersgrpcAccount;
};

export type protobufAny = {
    [key: string]: unknown;
};

export type rpcStatus = {
    code?: number;
    message?: string;
    details?: Array<protobufAny>;
};

export type typesAmount = {
    value?: number;
    currencyIsoCode?: string;
};

export type typesPoint = {
    lon?: number;
    lat?: number;
    address?: string;
};

export type OrdersCreateDeliveryPointData = {
    body: OrdersCreateDeliveryPointBody;
    path: {
        userId: string;
    };
};

export type OrdersCreateDeliveryPointResponse = (ordersgrpcCreateDeliveryPointResponse);

export type OrdersCreateDeliveryPointError = (rpcStatus);

export type OrdersConfirmPaymentData = {
    query?: {
        /**
         * "Transaction amount",
         */
        amount?: string;
        /**
         * "CamPay Reference",
         */
        code?: string;
        /**
         * "Transaction currency",
         */
        currency?: string;
        /**
         * "collect" or "withdraw". This shows the kind of
         */
        endpoint?: string;
        /**
         * The reference on the platform that initiated the transaction.
         */
        externalReference?: string;
        /**
         * "MTN or ORANGE",
         */
        operator?: string;
        /**
         * "Mobile Operator Reference"
         */
        operatorReference?: string;
        /**
         * The phone number that initiated the transaction
         */
        phoneNumber?: string;
        /**
         * "Reference of the transaction. A valid UUID4",
         */
        reference?: string;
        /**
         * "jwt token. You can validate this request that is coming from
         */
        signature?: string;
        /**
         * "SUCCESSFUL" or "FAILED",
         */
        status?: string;
    };
};

export type OrdersConfirmPaymentResponse = (ordersgrpcConfirmPaymentResponse);

export type OrdersConfirmPaymentError = (rpcStatus);

export type OrdersHealthCheckResponse = (ordersgrpcHealthCheckResponse);

export type OrdersHealthCheckError = (rpcStatus);

export type OrdersListFarmerOrdersData = {
    path: {
        farmerId: string;
    };
    query?: {
        count?: number;
        startKey?: string;
    };
};

export type OrdersListFarmerOrdersResponse = (ordersgrpcListFarmerOrdersResponse);

export type OrdersListFarmerOrdersError = (rpcStatus);

export type OrdersCreateOrderData = {
    body: OrdersCreateOrderBody;
    path: {
        userId: string;
    };
};

export type OrdersCreateOrderResponse = (ordersgrpcCreateOrderResponse);

export type OrdersCreateOrderError = (rpcStatus);

export type OrdersInitiatePaymentData = {
    body: OrdersInitiatePaymentBody;
    path: {
        userId: string;
    };
};

export type OrdersInitiatePaymentResponse = (ordersgrpcInitiatePaymentResponse);

export type OrdersInitiatePaymentError = (rpcStatus);

export type OrdersListDeliveryCitiesData = {
    path: {
        userId: string;
    };
    query?: {
        count?: number;
        startKey?: string;
    };
};

export type OrdersListDeliveryCitiesResponse = (ordersgrpcListDeliveryCitiesResponse);

export type OrdersListDeliveryCitiesError = (rpcStatus);

export type OrdersListDeliveryPointsData = {
    path: {
        userId: string;
    };
    query?: {
        city?: string;
        count?: number;
        startKey?: string;
    };
};

export type OrdersListDeliveryPointsResponse = (ordersgrpcListDeliveryPointsResponse);

export type OrdersListDeliveryPointsError = (rpcStatus);

export type OrdersListUserOrdersData = {
    path: {
        userId: string;
    };
    query?: {
        count?: number;
        startKey?: string;
    };
};

export type OrdersListUserOrdersResponse = (ordersgrpcListUserOrdersResponse);

export type OrdersListUserOrdersError = (rpcStatus);

export type OrdersApproveOrderData = {
    body: OrdersApproveOrderBody;
    path: {
        orderId: string;
        userId: string;
    };
};

export type OrdersApproveOrderResponse = (ordersgrpcApproveOrderResponse);

export type OrdersApproveOrderError = (rpcStatus);

export type OrdersDispatchOrderData = {
    body: OrdersDispatchOrderBody;
    path: {
        orderNumber: string;
        userId: string;
    };
};

export type OrdersDispatchOrderResponse = (ordersgrpcDispatchOrderResponse);

export type OrdersDispatchOrderError = (rpcStatus);

export type OrdersGetOrderDetailsData = {
    path: {
        orderNumber: string;
        userId: string;
    };
};

export type OrdersGetOrderDetailsResponse = (ordersgrpcGetOrderDetailsResponse);

export type OrdersGetOrderDetailsError = (rpcStatus);

export type OrdersConfirmDeliveryData = {
    body: OrdersConfirmDeliveryBody;
    path: {
        secretKey: string;
        userId: string;
    };
};

export type OrdersConfirmDeliveryResponse = (ordersgrpcConfirmDeliveryResponse);

export type OrdersConfirmDeliveryError = (rpcStatus);