// This file is auto-generated by @hey-api/openapi-ts

export type OrdersApproveOrderBody = unknown;

export type OrdersConfirmDeliveryBody = unknown;

export type OrdersCreateDeliveryPointBody = {
    address?: typesPoint;
    city?: string;
    deliveryPointName?: string;
};

export type OrdersCreateOrderBody = {
    productId?: string;
    quantity?: string;
    deliveryLocation?: typesPoint;
};

export type OrdersDispatchOrderBody = {
    payoutPhoneNumber?: string;
};

export type ordersgrpcAccount = {
    paymentMethod?: ordersgrpcPaymentMethodType;
    accountNumber?: string;
};

export type ordersgrpcApproveOrderResponse = unknown;

export type ordersgrpcCheckPaymentStatusResponse = {
    status?: ordersgrpcPaymentStatus;
};

export type ordersgrpcConfirmDeliveryResponse = unknown;

export type ordersgrpcConfirmPaymentRequest = {
    status?: string;
    reference?: string;
    amount?: string;
    currency?: string;
    operator?: string;
    code?: string;
    operatorReference?: string;
    signature?: string;
    endpoint?: string;
    /**
     * The reference on the platform that initiated the transaction.
     */
    externalReference?: string;
    phoneNumber?: string;
    orderId?: string;
};

export type ordersgrpcConfirmPaymentResponse = unknown;

export type ordersgrpcCreateDeliveryPointResponse = {
    deliveryPoint?: ordersgrpcDeliveryPoint;
};

export type ordersgrpcCreateOrderResponse = {
    order?: ordersgrpcOrder;
};

export type ordersgrpcDeleteDeliveryPointResponse = unknown;

export type ordersgrpcDeliveryPoint = {
    id?: string;
    address?: typesPoint;
    deliveryPointName?: string;
    city?: string;
    createdAt?: string;
};

export type ordersgrpcDispatchOrderResponse = unknown;

export type ordersgrpcFarmerEarningsData = {
    date?: string;
    value?: number;
};

export type ordersgrpcFilterType = 'FilterType_UNSPECIFIED' | 'FilterType_THIS_WEEK' | 'FilterType_THIS_MONTH' | 'FilterType_THIS_YEAR' | 'FilterType_ALL_TIME';

export type ordersgrpcGetAdminStatsResponse = {
    data?: Array<ordersgrpcStatItem>;
};

export type ordersgrpcGetFarmerEarningsResponse = {
    data?: Array<ordersgrpcFarmerEarningsData>;
};

export type ordersgrpcGetOrderDetailsResponse = {
    order?: ordersgrpcOrder;
    auditLog?: Array<ordersgrpcOrderAuditLog>;
};

export type ordersgrpcHealthCheckResponse = unknown;

export type ordersgrpcInitiatePaymentResponse = {
    payment?: ordersgrpcPayment;
};

export type ordersgrpcListDeliveryCitiesResponse = {
    cities?: Array<(string)>;
    nextKey?: string;
};

export type ordersgrpcListDeliveryPointsResponse = {
    deliveryPoints?: Array<ordersgrpcDeliveryPoint>;
    nextKey?: string;
};

export type ordersgrpcListFarmerOrdersResponse = {
    orders?: Array<ordersgrpcOrder>;
    nextKey?: string;
};

export type ordersgrpcListOrdersResponse = {
    orders?: Array<ordersgrpcOrder>;
    nextKey?: string;
};

export type ordersgrpcListPaymentsResponse = {
    payments?: Array<ordersgrpcPayment>;
    nextKey?: string;
};

export type ordersgrpcListUserOrdersResponse = {
    orders?: Array<ordersgrpcOrder>;
    nextKey?: string;
};

export type ordersgrpcOrder = {
    orderNumber?: string;
    deliveryLocation?: typesPoint;
    price?: typesAmount;
    status?: ordersgrpcOrderStatus;
    rating?: number;
    review?: string;
    product?: string;
    createdBy?: string;
    createdAt?: string;
    updatedAt?: string;
    secretKey?: string;
    productOwner?: string;
    payoutPhoneNumber?: string;
    quantity?: string;
    dispatchedBy?: string;
};

export type ordersgrpcOrderAuditLog = {
    timestamp?: string;
    actor?: string;
    action?: string;
    reason?: string;
    before?: ordersgrpcOrder;
    after?: ordersgrpcOrder;
};

export type ordersgrpcOrderStatus = 'OrderStatus_UNSPECIFIED' | 'OrderStatus_CREATED' | 'OrderStatus_PAYMENT_SUCCESSFUL' | 'OrderStatus_PAYMENT_FAILED' | 'OrderStatus_IN_TRANSIT' | 'OrderStatus_DELIVERED' | 'OrderStatus_APPROVED' | 'OrderStatus_REJECTED';

export type ordersgrpcPayment = {
    id?: string;
    paymentEntity?: ordersgrpcPaymentEntity;
    entityId?: string;
    amount?: typesAmount;
    createdBy?: string;
    createdAt?: string;
    expiresAt?: string;
    updatedAt?: string;
    status?: ordersgrpcPaymentStatus;
    account?: ordersgrpcAccount;
    type?: ordersgrpcPaymentType;
};

export type ordersgrpcPaymentEntity = 'PaymentEntity_UNSPECIFIED' | 'PaymentEntity_ORDER' | 'PaymentEntity_SUBSCRIPTION' | 'PaymentEntity_COMMISSION';

export type ordersgrpcPaymentMethodType = 'PaymentMethodType_UNSPECIFIED' | 'PaymentMethodType_MOBILE_MONEY' | 'PaymentMethodType_ORANGE_MONEY' | 'PaymentMethodType_CREDIT_CARD';

export type ordersgrpcPaymentStatus = 'PaymentStatus_UNSPECIFIED' | 'PaymentStatus_INITIATED' | 'PaymentStatus_COMPLETED' | 'PaymentStatus_FAILED' | 'PaymentStatus_CANCELED';

export type ordersgrpcPaymentType = 'PaymentType_UNSPECIFIED' | 'PaymentType_CREDIT' | 'PaymentType_DEBIT';

export type ordersgrpcRejectOrderResponse = unknown;

export type ordersgrpcStatItem = {
    title?: string;
    value?: number;
    change?: number;
    description?: string;
    currency?: string;
};

export type ordersgrpcUpdateDeliveryPointResponse = unknown;

export type OrdersInitiatePaymentBody = {
    paymentEntity?: ordersgrpcPaymentEntity;
    entityId?: string;
    amount?: typesAmount;
    account?: ordersgrpcAccount;
};

export type OrdersRejectOrderBody = {
    reason?: string;
};

export type OrdersUpdateDeliveryPointBody = {
    address?: typesPoint;
    city?: string;
    deliveryPointName?: string;
};

export type protobufAny = {
    [key: string]: unknown;
};

export type rpcStatus = {
    code?: number;
    message?: string;
    details?: Array<protobufAny>;
};

export type typesAmount = {
    value?: number;
    currencyIsoCode?: string;
};

export type typesPoint = {
    lon?: number;
    lat?: number;
    address?: string;
};

export type OrdersCreateDeliveryPointData = {
    body: OrdersCreateDeliveryPointBody;
    path: {
        userId: string;
    };
};

export type OrdersCreateDeliveryPointResponse = (ordersgrpcCreateDeliveryPointResponse);

export type OrdersCreateDeliveryPointError = (rpcStatus);

export type OrdersGetAdminStatsData = {
    path: {
        userId: string;
    };
};

export type OrdersGetAdminStatsResponse = (ordersgrpcGetAdminStatsResponse);

export type OrdersGetAdminStatsError = (rpcStatus);

export type OrdersListOrdersData = {
    path: {
        userId: string;
    };
    query?: {
        count?: number;
        searchKey?: string;
        startKey?: string;
        statuses?: Array<string>;
    };
};

export type OrdersListOrdersResponse = (ordersgrpcListOrdersResponse);

export type OrdersListOrdersError = (rpcStatus);

export type OrdersListPaymentsData = {
    path: {
        userId: string;
    };
    query?: {
        count?: number;
        paymentEntity?: 'PaymentEntity_UNSPECIFIED' | 'PaymentEntity_ORDER' | 'PaymentEntity_SUBSCRIPTION' | 'PaymentEntity_COMMISSION';
        paymentStatus?: 'PaymentStatus_UNSPECIFIED' | 'PaymentStatus_INITIATED' | 'PaymentStatus_COMPLETED' | 'PaymentStatus_FAILED' | 'PaymentStatus_CANCELED';
        paymentType?: 'PaymentType_UNSPECIFIED' | 'PaymentType_CREDIT' | 'PaymentType_DEBIT';
        searchKey?: string;
        startKey?: string;
    };
};

export type OrdersListPaymentsResponse = (ordersgrpcListPaymentsResponse);

export type OrdersListPaymentsError = (rpcStatus);

export type OrdersDeleteDeliveryPointData = {
    path: {
        id: string;
        userId: string;
    };
};

export type OrdersDeleteDeliveryPointResponse = (ordersgrpcDeleteDeliveryPointResponse);

export type OrdersDeleteDeliveryPointError = (rpcStatus);

export type OrdersUpdateDeliveryPointData = {
    body: OrdersUpdateDeliveryPointBody;
    path: {
        id: string;
        userId: string;
    };
};

export type OrdersUpdateDeliveryPointResponse = (ordersgrpcUpdateDeliveryPointResponse);

export type OrdersUpdateDeliveryPointError = (rpcStatus);

export type OrdersConfirmPaymentData = {
    body: ordersgrpcConfirmPaymentRequest;
};

export type OrdersConfirmPaymentResponse = (ordersgrpcConfirmPaymentResponse);

export type OrdersConfirmPaymentError = (rpcStatus);

export type OrdersHealthCheckResponse = (ordersgrpcHealthCheckResponse);

export type OrdersHealthCheckError = (rpcStatus);

export type OrdersGetFarmerEarningsData = {
    path: {
        farmerId: string;
    };
    query?: {
        /**
         * "this_week", "this_month", etc.
         */
        filter?: 'FilterType_UNSPECIFIED' | 'FilterType_THIS_WEEK' | 'FilterType_THIS_MONTH' | 'FilterType_THIS_YEAR' | 'FilterType_ALL_TIME';
    };
};

export type OrdersGetFarmerEarningsResponse = (ordersgrpcGetFarmerEarningsResponse);

export type OrdersGetFarmerEarningsError = (rpcStatus);

export type OrdersListFarmerOrdersData = {
    path: {
        farmerId: string;
    };
    query?: {
        count?: number;
        searchKey?: string;
        startKey?: string;
        statuses?: Array<string>;
    };
};

export type OrdersListFarmerOrdersResponse = (ordersgrpcListFarmerOrdersResponse);

export type OrdersListFarmerOrdersError = (rpcStatus);

export type OrdersCreateOrderData = {
    body: OrdersCreateOrderBody;
    path: {
        userId: string;
    };
};

export type OrdersCreateOrderResponse = (ordersgrpcCreateOrderResponse);

export type OrdersCreateOrderError = (rpcStatus);

export type OrdersInitiatePaymentData = {
    body: OrdersInitiatePaymentBody;
    path: {
        userId: string;
    };
};

export type OrdersInitiatePaymentResponse = (ordersgrpcInitiatePaymentResponse);

export type OrdersInitiatePaymentError = (rpcStatus);

export type OrdersListDeliveryCitiesData = {
    path: {
        userId: string;
    };
    query?: {
        count?: number;
        startKey?: string;
    };
};

export type OrdersListDeliveryCitiesResponse = (ordersgrpcListDeliveryCitiesResponse);

export type OrdersListDeliveryCitiesError = (rpcStatus);

export type OrdersListDeliveryPointsData = {
    path: {
        userId: string;
    };
    query?: {
        city?: string;
        count?: number;
        startKey?: string;
    };
};

export type OrdersListDeliveryPointsResponse = (ordersgrpcListDeliveryPointsResponse);

export type OrdersListDeliveryPointsError = (rpcStatus);

export type OrdersListUserOrdersData = {
    path: {
        userId: string;
    };
    query?: {
        count?: number;
        searchKey?: string;
        startKey?: string;
        statuses?: Array<string>;
    };
};

export type OrdersListUserOrdersResponse = (ordersgrpcListUserOrdersResponse);

export type OrdersListUserOrdersError = (rpcStatus);

export type OrdersApproveOrderData = {
    body: OrdersApproveOrderBody;
    path: {
        orderId: string;
        userId: string;
    };
};

export type OrdersApproveOrderResponse = (ordersgrpcApproveOrderResponse);

export type OrdersApproveOrderError = (rpcStatus);

export type OrdersRejectOrderData = {
    body: OrdersRejectOrderBody;
    path: {
        orderId: string;
        userId: string;
    };
};

export type OrdersRejectOrderResponse = (ordersgrpcRejectOrderResponse);

export type OrdersRejectOrderError = (rpcStatus);

export type OrdersDispatchOrderData = {
    body: OrdersDispatchOrderBody;
    path: {
        orderNumber: string;
        userId: string;
    };
};

export type OrdersDispatchOrderResponse = (ordersgrpcDispatchOrderResponse);

export type OrdersDispatchOrderError = (rpcStatus);

export type OrdersGetOrderDetailsData = {
    path: {
        orderNumber: string;
        userId: string;
    };
};

export type OrdersGetOrderDetailsResponse = (ordersgrpcGetOrderDetailsResponse);

export type OrdersGetOrderDetailsError = (rpcStatus);

export type OrdersCheckPaymentStatusData = {
    path: {
        paymentId: string;
        userId: string;
    };
};

export type OrdersCheckPaymentStatusResponse = (ordersgrpcCheckPaymentStatusResponse);

export type OrdersCheckPaymentStatusError = (rpcStatus);

export type OrdersConfirmDeliveryData = {
    body: OrdersConfirmDeliveryBody;
    path: {
        secretKey: string;
        userId: string;
    };
};

export type OrdersConfirmDeliveryResponse = (ordersgrpcConfirmDeliveryResponse);

export type OrdersConfirmDeliveryError = (rpcStatus);